### ISSUE TITLE
如何使用附加代码模式？

### ISSUE THREAD

**Issue by merckliu** [zhblue/hustoj#102]
想给学生写几道函数题，请问应该如何添加这类题目？

**Comment by zhblue** [comment]
比如c语言，想让学生输入helloworld几个字符就完成任务，在源码目录增加这几个文件：
prepend.c
```
#include<stdio.h>
int main(){

```
template.c
`    printf("");// 请在这里的双引号里输入helloworld`
append.c
`}`

**Comment by merckliu** [comment]
Thanks!
