### ISSUE TITLE
请问是否可以将“远程等待 得分0”的提交自动再进行一次判题？

### ISSUE THREAD

**Issue by Swcmb** [zhblue/hustoj#1028]
部分题目提交出现“远程等待 得分0”的情况，我该如何处理？
我知道可以在后台进行特定提交编号的重判，但是感觉一个个重判过于复杂，有无其他方法？
请问是否可以将“远程等待 得分0”的提交自动再进行一次判题？我希望系统能够自动检测到这种情况，并在一段时间后自动重新提交用户的代码进行判题。

**Comment by zhblue** [comment]
请更新include/remote_bas.php
并去https://www.ssoier.cn/api/index.php 激活之前申请的账户

**Comment by Swcmb** [comment]
也就是说我需要同时启用远程判题系统？

**Comment by Swcmb** [comment]
非常感谢您！
