### ISSUE TITLE
界面太丑

### ISSUE THREAD

**Issue by li-sky** [zhblue/hustoj#104]
>*本人的建议仅供参考,不对其做任何保证.*

　　个人认为，这个OJ实在是……**太丑了**。  
　　毕竟，一个好看的OJ能够有效**提高做题者的刷题愿望**，同时还可以*增加页面访问量（不对此保证）*。又有谁愿意看到一个不好看的网页呢？  
　　其实，只要改一改CSS，就能将其扁平化，可以让它变得更好看。  
　　以上是我的一点建议，希望采纳！

**Comment by zhblue** [comment]
欢迎在这里贴出你改好的CSS代码

**Comment by li-sky** [comment]
不是说了不保证吗？
算了，还是搞一搞吧。:-)

**Comment by kingxiaofire** [comment]
所以想请教一下主页面是放在哪里的，可以修改吗？？

**Comment by zhblue** [comment]
参考 http://www.hustoj.com/?p=11
主页有很多种版本，都在template目录下，默认是bs3
建议将bs3复制一份，命名为你自己的名字（如 beauty），然后修改配置文件$OJ_TEMPLATE变量，从bs3修改为你自己的模板名字(beauty)，然后修改新目录（beauty）下的文件。
