### ISSUE TITLE
关于运行时选择Clang的问题

### ISSUE THREAD

**Issue by ryanlee2014** [zhblue/hustoj#107]
我用Language:Clang/Clang++运行时出现了无限等待的情况。

![qq 20170125130653](https://cloud.githubusercontent.com/assets/10142214/22278563/5a468596-e2ff-11e6-84a1-6455fda1cc52.jpg)

这种情况是什么设置出了问题呢？Clang/Clang++已经安装了。
操作系统是Ubuntu 14.04 x86_64

**Comment by zhblue** [comment]
检查judge.conf，OJ_LANG_SET增加13,14

**Comment by ryanlee2014** [comment]
谢谢您！问题解决了
