### ISSUE TITLE
Nginx + hustoj

### ISSUE THREAD

**Issue by as535364** [zhblue/hustoj#110]
網上查了很多關於 Nginx 搭配 hustoj 的文章，但幾乎沒提到細節，這邊想問下老師如果要用 LNMP 架構，可能需要注意什麼嗎？

**Comment by zhblue** [comment]
https://mp.weixin.qq.com/s?__biz=MzI1MTAwMTI2NA==&mid=2656402051&idx=1&sn=c5bb009f00a78103bdd503d4ac5dee9e&scene=37&key=a5ed1300fc919324e89a6999c8bdd400c641f5a7ce70d8f018c78f25586873172cf8fb90c33c798a70b2845dff8e6b26295d700da5bf78e3ab49e4afe3c5fc94899f5dda5fa982e755dac6764497db77&ascene=3&uin=MTMzMjIxODQwMw%3D%3D&devicetype=android-22&version=26050431&nettype=WIFI&abtest_cookie=AQABAAgAAQBFhh4AAAA%3D&pass_ticket=7DmaUxmKbKn4EdpO8C4dRdo3ZdkD9GYz4lJ%2FzKsUEmgMayjjmJRx3T7iSXULJEAJ&wx_header=1

**Comment by as535364** [comment]
感激不盡
