### ISSUE TITLE
判题机一直卡在编译中

### ISSUE THREAD

**Issue by ryanlee2014** [zhblue/hustoj#118]
系统是CentOS 7
用之前AC的代码做测试，全部都卡在编译中，检查log发现显示compile error,在judge_client测试过程发现提示段错误，这应该怎么解决呢？
![qq 20170310192139](https://cloud.githubusercontent.com/assets/10142214/23793646/4c6134d6-05c7-11e7-8b6d-4af091d97b8b.jpg)
![qq 20170310192225](https://cloud.githubusercontent.com/assets/10142214/23793648/4fb0acb6-05c7-11e7-93eb-e148408c5b3d.jpg)
![qq 20170310192201](https://cloud.githubusercontent.com/assets/10142214/23793649/4fed6084-05c7-11e7-9d9a-d1cc29a63a3b.jpg)

**Comment by zhblue** [comment]
后台更新一下数据库

**Comment by zhblue** [comment]
后台更新一下数据库

**Comment by ryanlee2014** [comment]
怎样更新数据库

**Comment by zhblue** [comment]
登录后台，有个菜单“更新数据库”

**Comment by ryanlee2014** [comment]
问题解决了，数据库的字段有些问题，排查了数据库的内容以后就没问题了。非常感谢！

**Comment by xia0ji233** [comment]
但是我这里点了之后再提交还是卡在编译中
