### ISSUE TITLE
Special Judge 在WA能顯示Judge Message（顯示被WA的原因）嗎？

### ISSUE THREAD

**Issue by tico88612** [zhblue/hustoj#123]
Special Judge 在WA的時候能顯示Judge Message（顯示被WA的原因）嗎？

**Comment by zhblue** [comment]
打开SHOW_DIFF

**Comment by tico88612** [comment]
SHOW_DIFF只有一般Judge才有，Special Judge 如果要印出訊息給使用者看，要如何做

**Comment by zhblue** [comment]
试试让spj程序输出到diff.out

**Comment by tico88612** [comment]
spj代碼需要加什麼嗎？

**Comment by zhblue** [comment]
spj代碼需要加：
freopen("diff.out","w",stdout);

**Comment by tico88612** [comment]
還是無法，有其他方式嗎？

**Comment by zhblue** [comment]
那就自己改一改judge_clientd源码看？
