### ISSUE TITLE
有几个建议

### ISSUE THREAD

**Issue by ryanlee2014** [zhblue/hustoj#125]
1.在php7以上分支使用TestData会因为eregi()和ereg()函数不存在而报500，这个可以把所有的这两个函数替换成preg_match(),功能是一样的。
2.MySQL5.7以后的版本对于/web/problemstatus.php下
`select * from
(

SELECT count(*) att ,user_id, min(10000000000000000000+time *100000000000 + memory *100000 + code_length ) score
FROM solution
WHERE problem_id =$id
AND result =4
GROUP BY user_id
ORDER BY score, in_date

)c
left join
(
SELECT solution_id ,user_id,language,10000000000000000000+time *100000000000 + memory *100000 + code_length  score, in_date
FROM solution
WHERE problem_id =$id
AND result =4

ORDER BY score, in_date
)b
on b.user_id=c.user_id and b.score=c.score
order by c.score,in_date
 limit $start,100";
`
会触发GROUP BY错误
网上对于[该问题](http://www.520sz.com/mysql-5-7-10-group-by-error.html)的分析
如果暂时不更改这段查询语句可以在/etc/my.cnf文件中加入这样一行
sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
就可以解决问题了。

这两个地方可以改改

**Comment by zhblue** [comment]
非常感谢，稍后我有空进行修补

**Comment by ryanlee2014** [comment]
好的
另外我刚才发现的一个问题
在OpenJDK 1.8版本以后提交Java代码会报错:
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=192M; support was removed in 8.0
研究以后应该注释掉[judge_client.cc:1629](https://github.com/zhblue/hustoj/blob/master/trunk/core/judge_client/judge_client.cc#L1629)
这样就可以正常使用了

**Comment by zhblue** [comment]
请问是否方便推送成PR，我直接merge掉，最近忙其他事情，无暇处理。
