### ISSUE TITLE
service judged status卡在activating

### ISSUE THREAD

**Issue by KaitoHH** [zhblue/hustoj#127]
service judged start启动不了 ，status只提示`Starting HUSTOJ Judged`，然后Active就一直显示`activating`。请问是什么原因呢？谢谢！或者是否有办法可以重新安装judged? `Ubuntu 16.04 Server`系统
![qq20170318-200935](https://cloud.githubusercontent.com/assets/13927774/24071857/de11cb5c-0c16-11e7-94f9-90b122d4bdfa.png)

**Comment by zhblue** [comment]
16.04？
sudo judged

**Comment by KaitoHH** [comment]
Thanks a lot! It really works!
