### ISSUE TITLE
新版oj系统无法添加测试用例

### ISSUE THREAD

**Issue by ruanjianwyc** [zhblue/hustoj#130]
新版TestData点进去后无法添加测试用例只有一个下载按钮

**Comment by zhblue** [comment]
给个图？

**Comment by zhblue** [comment]
![123](https://cloud.githubusercontent.com/assets/3926566/24354723/90d6ba1c-1325-11e7-861e-3429eca169a5.png)
![456](https://cloud.githubusercontent.com/assets/3926566/24354724/912c9cf2-1325-11e7-830e-166d338885cf.png)

**Comment by ruanjianwyc** [comment]
就是编辑那块不显示

**Comment by ruanjianwyc** [comment]
我已经把旧版的那块代码帖过去了，目前已经能用了

**Comment by ruanjianwyc** [comment]
![image](https://cloud.githubusercontent.com/assets/17509110/26059503/90331c8a-39b4-11e7-83fa-83ed33312562.png)

**Comment by li-sky** [comment]
请关闭Issue.
