### ISSUE TITLE
重启服务器之后，java一直是永久pending？

### ISSUE THREAD

**Issue by zzhy1996** [zhblue/hustoj#132]
重启之前是正常的，C/C++也是正常的。
也尝试重启判题机，没有效果，正常情况下页面上的java判题机会显示是admin，但是现在却显示LOCAL

**Comment by zhblue** [comment]
检查/home/judge/etc/judge.conf
OJ_LANG_SET中是否有3

**Comment by zzhy1996** [comment]
感谢！确实没有3，但是我加上3之后，怎样才能使他生效？我sudo judged 之后没有效果

**Comment by zhblue** [comment]
重启

**Comment by zzhy1996** [comment]
非常感谢！
