### ISSUE TITLE
关于数据库的问题

### ISSUE THREAD

**Issue by ryanlee2014** [zhblue/hustoj#136]
solution表里面的ip设置的长度过小，导致当ipv6地址访问OJ提交的时候无法执行
if (!isset($pid)){
	$sql="INSERT INTO solution(problem_id,user_id,in_date,language,ip,code_length)
		VALUES('$id','$user_id',NOW(),'$language','$ip','$len')";
	}
else{
	$sql="INSERT INTO solution(problem_id,user_id,in_date,language,ip,code_length,contest_id,num)
		VALUES('$id','$user_id',NOW(),'$language','$ip','$len','$cid','$pid')";
	}
	mysqli_query($mysqli,$sql);
而出错。
可以适当调整那个导入用的sql文件

**Comment by zhblue** [comment]
-_-!
没用过ipv6，无法测试,，先盲改吧

**Comment by hsxfjames** [comment]
我觉得可以加长一下，应该没有区分v4还是v6的必要，也不需要做奇怪的匹配验证，加到v6地址的最大长度就好了
