### ISSUE TITLE
Judge 测出时间超过正常时间

### ISSUE THREAD

**Issue by li-sky** [zhblue/hustoj#144]
在一台Ubuntu的电脑上使用，OJ运行时间是正常运行时间(同机)的**5倍**。

**Comment by zhblue** [comment]
ptrace的代价

**Comment by tony1312** [comment]
请问这有什么解决方法吗？

**Comment by zhblue** [comment]
如果内网，或者在docker中，可尝试设置OJ_USE_PTRACE=0
注意这样做会有安全隐患，公网慎用

**Comment by li-sky** [comment]
多谢！（其实就是本校的OJ，事实上可以通过编译时禁止一些操作，如调用汇编等来解决该问题。）
