### ISSUE TITLE
评测获得的时间和内存

### ISSUE THREAD

**Issue by tony1312** [zhblue/hustoj#151]
评测获得的时间和内存具体指的是？
每个测试点所用还是所有测试点一共用时？

**Comment by zhblue** [comment]
时间取决于OJ_USE_MAX_TIME的设置
https://github.com/zhblue/hustoj/blob/master/trunk/install/judge.conf#L26
当设为1时，是最长时间的一个。
当设置为0时，是所有的。
内存为检测到的峰值

**Comment by tony1312** [comment]
谢谢：)
