### ISSUE TITLE
新增的loj爬取功能里面的一些问题

### ISSUE THREAD

**Issue by ryanlee2014** [zhblue/hustoj#152]
在数据库表中时间限制是一个整数，judge_client.cc也是整数，但是有些loj的题目是浮点数的限时。是否可以修改一下sql文件的一些参数
同时，由于爬取下来的测试数据有.ans文件而不是.out文件，我这边已经写了一个能够在CentOS环境能够修改后缀的命令，但是在Ubuntu下还没有找到解决的方法-_-
我看到时候是不是可以pr一下

**Comment by zhblue** [comment]
个人认为OJ的测试精度达不到100ms，因此设置浮点数不是非常合理，当然需要的话也可以自己改。
windows下可以ren *.ans *.out
bash可以
 for i in `find -name "*.ans"`;do mv $i `basename $i .ans`.out;done

**Comment by ryanlee2014** [comment]
![image](https://user-images.githubusercontent.com/10142214/27420328-fecf57d8-5757-11e7-9dc7-337bd10858a8.png)
我个人在这里改成了这个
目前看是有效的(CentOS)
