### ISSUE TITLE
新版hustoj跟旧版有什么区别呢，为什么同一个比赛结果会不一样呢？

### ISSUE THREAD

**Issue by ruanjianwyc** [zhblue/hustoj#156]
新版的比赛人数比旧版的少两个人，比赛人数不是都显示么？

**Comment by zhblue** [comment]
交叉对比一下，少了谁，再看他们都干了什么

**Comment by zhblue** [comment]
这是一个bug，已修复，请更新db_info.inc.php，或搜索limit 100修改为limit 10000
