### ISSUE TITLE
请问能否将运行错误信息输出？

### ISSUE THREAD

**Issue by tony1312** [zhblue/hustoj#157]
RT
比如运行错误202 之类的

**Comment by zhblue** [comment]
![re](https://user-images.githubusercontent.com/3926566/27632580-a359464e-5c2e-11e7-9780-5192da166423.png)
![re2](https://user-images.githubusercontent.com/3926566/27632597-acb005c0-5c2e-11e7-9de1-d83ed5079874.png)

**Comment by tony1312** [comment]
请问空的运行错误是smg?

**Comment by tony1312** [comment]
![capture](https://user-images.githubusercontent.com/21166787/27736118-54fcaf92-5dd5-11e7-9139-c95e949aabf6.PNG)

**Comment by zhblue** [comment]
检查代码，可能被屏蔽了或改皮肤改没了。

**Comment by tony1312** [comment]
被屏蔽了是指？

**Comment by tony1312** [comment]
使用最初备份的刚装好的也不行唉
![capture](https://user-images.githubusercontent.com/21166787/27737080-6d752258-5dd9-11e7-8fb9-ff346c717c44.PNG)

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/blob/master/trunk/web/reinfo.php#L16

有的版本没有这一行return 1，为防止有人利用RE信息窃取测试数据，这里有简单的屏蔽。

数字超过一定比例则不显示。

**Comment by tony1312** [comment]
好像没屏蔽？
![capture](https://user-images.githubusercontent.com/21166787/27737298-3a188732-5dda-11e7-976b-edf1f09c1c99.PNG)

**Comment by tony1312** [comment]
是judger的配置问题？

**Comment by tony1312** [comment]
有好几次运行错误，不过只有下面这一次显示了相关信息，其他的运行错误信息都是空的
是忘记注释掉文件输入输出
=============
Runtime Error:[ERROR] A Not allowed system call: runid:1047 CALLID:330
 TO FIX THIS , ask admin to add the CALLID into corresponding LANG_XXV[] located at okcalls32/64.h ,
and recompile judge_client. 
if you are admin and you don't know what to do ,
chinese explaination can be found on https://zhuanlan.zhihu.com/p/24498599

辅助解释：
A Not allowed system call: runid:1047 :使用了系统禁止的操作系统调用，看看是否越权访问了文件或进程等资源

**Comment by zhblue** [comment]
有时是会这样，RE过于严重，以致来不及保存出错信息就退出了，考虑一下是否主机内存太小或者是否是在docker中运行。

**Comment by tony1312** [comment]
2GB应该不算小把？

**Comment by zhblue** [comment]
应该不算小，你可以试试交到这里看看会怎样
http://115.159.210.66/

**Comment by tony1312** [comment]
已经将测试数据用你OJ的短消息发给您了，谢谢

**Comment by zhblue** [comment]
从发来的数据看，你的测试数据有一组缺少输出文件。

**Comment by tony1312** [comment]
哦，好像是这样的【逃】，真是抱歉，
谢谢您啦
