### ISSUE TITLE
PDO出错的问题

### ISSUE THREAD

**Issue by mnyhome** [zhblue/hustoj#159]
您好，我是在3月的时候安装了您的hustoj（使用您的自动安装脚本），现在更新了WEB端后几乎所有页面都是空白。经排查发现如果没有pdo页面即可打开。使用phpinfo显示pdo_mysql是enabled的。烦请您帮忙解决一下问题，谢谢！

**Comment by zhblue** [comment]
try
sudo apt-get install php-pdo
此外更新时冲突请选tc

**Comment by mnyhome** [comment]
@zhblue 您好，php-db安装、重启apache2后页面还是空白。。。
话说tc是神马？
谢谢您的帮助。

**Comment by zhblue** [comment]
你可以试试先把老的目录备份后改名，然后检出一份最新版本到原始位置，修改db_info.inc.php，连接好数据库。如果页面正常，把其他参数复制过来，把upload目录复制过来，基本就可以了。

**Comment by mnyhome** [comment]
@zhblue 您好，这个方法我是尝试过的，但页面还是一片空白。而且我还尝试过把所有php文件中的pdo字符改成mysqli，改完后页面能显示，但由于语法错误，题目等数据都无法显示，而且主题也没有了。。。
感谢您的帮助。

**Comment by zhblue** [comment]
你可以把db_info.inc.php第一行的报错打开，从Off改成On，看报错信息来推断问题原因。

**Comment by mnyhome** [comment]
您好，我找到问题所在了，新旧版本的db_info.inc.php是不兼容的，直接使用旧版db_info.inc.php会导致错误，十分抱歉占用了您的时间，感谢您的帮助！
