### ISSUE TITLE
数据明文传输问题

### ISSUE THREAD

**Issue by CaesarW** [zhblue/hustoj#160]
这几天在竞赛夏令营，他们使用的OJ是HUSTOJ，然后抓了一波包。明文密码与源码就出来了。

希望Encrypt一下。

如果本身没有这个问题就当我没说，谢谢！

**Comment by zhblue** [comment]
同学们的姿势越来越高了，要么让组织者先上一下https吧
我得找找有没有js版本的md5和sha1

**Comment by zhblue** [comment]
先修个登录凑合吧，如果可以上sniffer的话，难道要js撸个https出来？想想就放弃了……

**Comment by CaesarW** [comment]
嗯，谢谢回应。当然咯我们是不准备跟举办方说的。。。

PS: 希望能越做越好，MD化是坠吼的。。。

团队： @CaesarW @yalewoosoft @PromethiumL

**Comment by zhblue** [comment]
MD=MarkDown ?

**Comment by CaesarW** [comment]
Material Design

**Comment by zhblue** [comment]
装死.jpg

**Comment by CaesarW** [comment]
其实主要还是主办方技术不足，他们用的是nginx服务器，加上https只要加一个certificate就行了。。

**Comment by virusdefender** [comment]
这问题和 oj 本身啥关系，你能抓包的话，也可以替换掉加密的 js 变成明文的。

总结：除了 https，前端加密不靠谱。

**Comment by yalewoosoft** [comment]
其实并不一定需要https。即使加了https，凭主办方的IQ，搞个证书劫持他们也会Trust。
只需要发送密码的时候hash一下。我没有学过js，但相信库还是好找的，也不会增加太多运算量。

**Comment by zhblue** [comment]
已经patch上了，不必再纠结
