### ISSUE TITLE
Judged的每次测试都是WA

### ISSUE THREAD

**Issue by tony1312** [zhblue/hustoj#173]
RT
![screenshot - 2017 08 07 - 22 36 47](https://user-images.githubusercontent.com/21166787/29031468-ef8a8774-7bc0-11e7-8df5-342baeeb05ad.png)

**Comment by tony1312** [comment]
用标程也是这样QwQ

**Comment by zhblue** [comment]
如果A+B没有问题，一般就不是系统问题，是题目数据或标程的问题

**Comment by tony1312** [comment]
可是数据和题目在虚拟机上可以正常使用啊

**Comment by tony1312** [comment]
为什么他的运行信息输出的都是`1d0`？

**Comment by zhblue** [comment]
百度 diff输出含义

**Comment by zhblue** [comment]
检查对应的.in文件是否以空行结尾，若无，补上。

**Comment by tony1312** [comment]
可是为什么还有一些WA连wa的信息都没有QwQ?

**Comment by tony1312** [comment]
哦，我看看，谢谢

**Comment by zhblue** [comment]
我也不知道，注意文本文件的unix格式和windows格式区别

**Comment by tony1312** [comment]
请问judged有debug模式吗？

**Comment by tony1312** [comment]
![20170812170717](https://user-images.githubusercontent.com/21166787/29239448-960c9bfa-7f81-11e7-8b7c-bfe98dee07f4.png)
这个调试信息是？

**Comment by tony1312** [comment]
好像系统的设置显示judge用户已经禁用了

**Comment by tony1312** [comment]
不过启动好像要添加新密码

**Comment by tony1312** [comment]
judge用户是有密码的吗？

**Comment by tony1312** [comment]
debug模式下好像一堆挂载失败，似乎重定向标准输入输出炸了，`user.out`是空的

<=返回信息=>
http://pastebin.ubuntu.com/25297618/

**Comment by tony1312** [comment]
好吧，总算找到原因了，安装脚本少装了FP 编译器2333

**Comment by tony1312** [comment]
谢谢
