### ISSUE TITLE
admin界面存在bug

### ISSUE THREAD

**Issue by jizhuozhi** [zhblue/hustoj#186]
使用seeOj的时候没有发生跳转，而是直接在admin管理界面刷新出了index界面，学生党能力有限orz，希望大大能调试一下。在这里给大大跪了orz

**Comment by jizhuozhi** [comment]
和上一个问题一样，也是php7分支的

**Comment by jizhuozhi** [comment]
对啦，顺便还有一个问题，admin文件夹里的problem.php源码里默认添加的题目都是defunct=Y的，这样的僵尸题目导入之后好不方便的，我自己手动把数据库语句中的Y改成了N

**Comment by zhblue** [comment]
这两个都是feature不是bug
SeeOJ以前的作用是分屏，右侧有个横栏可拉，同时查看排名与状态。
新题一般用作比赛、考试，不希望提前漏题，因此默认不激活。

**Comment by jizhuozhi** [comment]
哦哦，明白啦，谢谢大大
