### ISSUE TITLE
请问评测机要如何扩栈？

### ISSUE THREAD

**Issue by hyzgh** [zhblue/hustoj#190]

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/blob/master/trunk/core/judge_client/judge_client.cc#L925
我只能提供这个位置，可以修改编译参数，其他信息请自行查阅各编译器的文档。

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/blob/master/trunk/core/judge_client/judge_client.cc#L1741
还有这里有个默认设置，你可以试试
