### ISSUE TITLE
OJ不能判含有<bits/stdc++.h>头文件的C++程序

### ISSUE THREAD

**Issue by hyzgh** [zhblue/hustoj#200]
请问有办法可以让OJ支持判含有<bits/stdc++.h>头文件的C++程序吗?

**Comment by zhblue** [comment]
```
#include <bits/stdc++.h>
#include <iostream>
 
using namespace std;
 
int  main()
 
{
 
    int a,b;
 
    cin >> a >> b;
 
    cout << a+b << endl;
 
    return 0;
 
}
/**************************************************************
    Problem: 1000
    User: zhblue
    Language: C++
    Result: 正确
    Time:3 ms
    Memory:1704 kb
****************************************************************/
```

**Comment by hyzgh** [comment]
![oj](https://user-images.githubusercontent.com/31174102/32724240-68c5c4c8-c8ab-11e7-9645-2a1aed49d879.png)
不含bits/stdc++.h的时候是可以编译成功的，但是加了之后就提示编译错误，辅助解释提示virtual memory exhausted: Cannot allocate memory。请问这种情况要怎么办？

**Comment by zhblue** [comment]
尽量提供更多详细信息，包括不限于发行版，版本号，安装方式，安装时间，机器配置

**Comment by kadragon** [comment]
same issue
![image](https://user-images.githubusercontent.com/4111693/32871243-3fe85358-cac3-11e7-85d7-393ff4e112d3.png)

ubuntu 16.04 lts
![image](https://user-images.githubusercontent.com/4111693/32871304-951966a0-cac3-11e7-9674-54ac3649b1a3.png)

install using script / 1 month ago
![image](https://user-images.githubusercontent.com/4111693/32871348-dabff19c-cac3-11e7-9377-4cc220bd0bc6.png)

system memory
![image](https://user-images.githubusercontent.com/4111693/32871379-05e9cc58-cac4-11e7-96bb-50881a3eb6c9.png)

请问这种情况要怎么办？

**Comment by zhblue** [comment]
try this:
modify judge.conf set 
OJ_COMPILE_CHROOT=0
and reboot

**Comment by kadragon** [comment]
![image](https://user-images.githubusercontent.com/4111693/32871663-c5067996-cac5-11e7-9b06-5d655fe584ea.png)

Sadly, I have already set it up.

**Comment by zhblue** [comment]
then try 14.04
chinese "不推荐" means "NOT recommended"

**Comment by zhblue** [comment]
last possible saver
https://github.com/zhblue/hustoj/blob/master/trunk/core/judge_client/judge_client.cc#L982
change these 2 line , double 256 to 512 ,or even 1024
and re-execute sudo ./make.sh under core

**Comment by kadragon** [comment]
https://github.com/zhblue/hustoj/blob/master/trunk/core/judge_client/judge_client.cc#L982
change these 2 line , double 256 to 512 ,or even 1024

problem solve!! thx!
