### ISSUE TITLE
输入数据问题

### ISSUE THREAD

**Issue by robot2018** [zhblue/hustoj#229]
输入
输入一行，包含一个正整数n。

对于这种题目要求，也需要用while（）语句来控制测试用例吗？系统不是每次都调用程序吗？

**Comment by robot2018** [comment]
顺便问下大牛们，这种题目如果出现在蓝桥杯比赛时，是否需要while语句？蓝桥杯的系统是否是一个点调用一次程序，踩点给分，有哪位大牛知道的麻烦帮忙解答下，谢谢

**Comment by zhblue** [comment]
每组测试数据.in/,out跑一次，在一组数据内部的n条也好，EOF也罢，0/-1结束也罢，都需要自己控制输入输出。参见tk.hustoj.com 1000-1007
