### ISSUE TITLE
评测系统卡读入

### ISSUE THREAD

**Issue by africamonkey** [zhblue/hustoj#23]
`#include <cstdio>
int main() {
while (1) getchar();
}`
我们拿这段代码来提交A+B Problem，时限1秒。
在评测时，到终端输入top查看进程。
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                         
 6364 root      20   0  101560   2428   1844 S  29.3  0.0   0:02.54 judge_client                    
 6385 judge     39  19    1080      4      0 t   2.0  0.0   0:00.19 Main 
此时Main进程消耗CPU%异常低，judge_client的CPU%异常高，这也说明了为什么这段小小的代码评测这么久。
此时的Main进程已经读到EOF了还在不停地读，降低了CPU%。
最终出来的结果是：
problem_id=1000	result=Time Limit Exceed	memory=1080 KB	**time=324 ms**	code_length=62 B
注意加粗的324ms，这是由于评测时间过长，judge_client强行终止进程，可是该程序并没有跑满1秒。在这样的情况下终止进程显然有失公平性。
希望您能告知我如何解决卡读入的问题，谢谢！

**Comment by zhblue** [comment]
出于对ddos类攻击的预防，不建议进行修改。
题目不应靠大量的io来提高耗时，而是巧妙的算法要求，让少量的数据产生大量的计算。
比如求第10000个素数的值，输入短短几个字节，足够CPU跑很久。

一定要让这种io调用多的程序通过，可以去掉对PTRACE的相关调用，但同时应对提交者进行实名认证，以免攻击发生数据丢失。

**Comment by zhblue** [comment]
getchar()阻塞后几乎不消耗CPU，如果就这样让它几乎不消耗的运行完1秒的CPU，时间可以拖很久。
结果就是只要不停地交此类程序，服务器进程数会激增，最终内存耗尽，结局类似fork炸弹。

**Comment by africamonkey** [comment]
谢谢您详细的回答！主要是现在的OI题有时出现10M的输入文件，用Pascal语言读起来非常慢，在OJ上还没跑够时限就被判超时，让我很苦恼。
关于实名认证，我认为这是个很好的建议。我回去可以把judge_client改成“通过实名认证的用户去掉ptrace的调用”。

**Comment by zhblue** [comment]
try set OJ_SHM_RUN＝1 in judge.conf
