### ISSUE TITLE
File Not Exist

### ISSUE THREAD

**Issue by billchenchina** [zhblue/hustoj#231]
https://github.com/zhblue/hustoj/blob/f61021d763d88fd10f8e8dad473b6cbc70ec539a/trunk/web/template/bs3/nav.php#L18

Perhaps be `../../include/online.php`?

**Comment by billchenchina** [comment]
具体是这样的，在访问`/discuss3/discuss.php`时会报错

```PHP Fatal error:  require_once(): Failed opening required './include/online.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/judge/src/web/template/bs3/nav.php on line 18```

**Comment by billchenchina** [comment]
目前我是把discuss3下的php文件（除了`discuss3/index.php`和`discuss3/oj-header.php`）都放到了webroot，把相对路径修了修凑合用。。。希望尽快修复

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/commit/b046c975781fe4941b01ba17e7a468715918c3e6

**Comment by billchenchina** [comment]
Solved.
