### ISSUE TITLE
安装时的一点问题

### ISSUE THREAD

**Issue by 1481767320** [zhblue/hustoj#253]
张老师，我在安装时不小心执行了多次安装文件，现在无法访问网站，该怎么解决？
我用的是ubuntu16.04.4LTS，麻烦给一个解决方案，谢谢！

**Comment by zhblue** [comment]
可能是/etc/nginx/sites-enabled/default文件的语法出现错误，检查其中的{ ...}匹配情况，删除多余的}

**Comment by 1481767320** [comment]
好的，马上我看看

**Comment by 1481767320** [comment]
能不能通过卸载nginx后再安装来解决？

**Comment by zhblue** [comment]
可以，要用purge，不能用remove

**Comment by 1481767320** [comment]
好的，谢谢

**Comment by 1481767320** [comment]
直接重装系统解决(^_^)反正没数据
实在是懒得改代码了
