### ISSUE TITLE
Compiler memory limit overflow

### ISSUE THREAD

**Issue by amir-s** [zhblue/hustoj#257]
Here:
https://github.com/zhblue/hustoj/blob/94c62a95d48d79ead302ca55cab02aa0bc802c78/trunk/core/judge_client/judge_client.cc#L987-L990

since `STD_MB` is defined to be `#define STD_MB 1048576`, `STD_MB<<11` would overflow and become negative.

A solution could be to define it as `long long`, or `unsgined`.

```
#define STD_MB 1048576LL
```

**Comment by zhblue** [comment]
Thank you!
