### ISSUE TITLE
Apply memory limit to run the solution

### ISSUE THREAD

**Issue by amir-s** [zhblue/hustoj#258]
I noticed that the memory limit applied to the solution as with `setrlimit(RLIMIT_AS, ...)` only for C, C++ and FPC. Why is that?

https://github.com/zhblue/hustoj/blob/94c62a95d48d79ead302ca55cab02aa0bc802c78/trunk/core/judge_client/judge_client.cc#L1781-L1784

That limit can be safely removed for C, C++ and FPC, and their memory usage can be checked like all the other languages.

Or the limit could be set to `2GB` to let all the languages including JVM based ones to operate properly.

**Comment by zhblue** [comment]
Limit all solutions' memory usage might help server to save more memory for parallel running solutions.
most ACM/ICPC contests use C/C++/FPC，this settings can help prevent DoS (submit many memory costing solutions to slow down the whole system) attack. 
As to Java and other languages, it's recommended that setup independent judge server for each language with OJ_LANG_SET in judge.conf.  It works faster than put everything on one single server.

**Comment by amir-s** [comment]
you're right! it totally makes sense!
thanks for the explanation!
