### ISSUE TITLE
针对远古版本有什么升级方法吗？

### ISSUE THREAD

**Issue by xiekeyi98** [zhblue/hustoj#264]
接手了我们学校祖传OJ，是2013年的版本，服务器内部一团乱麻
使用[博客](http://www.hustoj.com/?p=47&replytocom=21)中的方法升级失败。
因为网上资料较少，迫于无奈写了该issue求助。
**很抱歉于百忙之中打扰到各位开发者。非常感谢各位的耐心帮助**
有几个问题需要解决：
1. 对于远古版本有什么升级的方法吗？
2. 如果无法升级，是否可以卸载重装？该如何卸载呢，只要把`/var/www/Judgeonline/`和/`HUSTOJ`等相关文件夹删除就可以了吗？
3.  有什么办法备份原来的文件吗？我准备尝试直接dump数据库，然后安装完毕后restore回去。不知道有没有更好的方法，也害怕早期数据库表结构，新OJ难以识别。

4.发现一个疑似bug，就是用OJ功能导出problem的时候，如果导出的序号大于题库中的号，就会下载失败，不知道新版本是否修复。（另外似乎只导出了题目，没有导出数据？）

最后再次感谢各位百忙之中的帮助

**Comment by zhblue** [comment]
微信公号给你回复了：
先找个机器装上最新版本，然后还原老的数据库备份上去，把/home/judge/data目录和/home/judge/src/web/upload用老的对应文件夹覆盖。 再去管理后台，点击一次更新数据库

**Comment by zhblue** [comment]
备份方法，参考install/bak.sh，注意老版本的web在/var/www里面,新版本在/home/judge/src/web里面，其他基本一致。

**Comment by zhblue** [comment]
因为最新版本适配的是Ubuntu的14.04/16.04/18.04 所配套的nginx php mysql 以及各语言编译器。
你2013年的系统一定是没法直接运行最新版的，所以需要重新安装一个新版本。
如果需要在老的硬件上安装，至少需要把数据全部 备份好，然后重装一个Ubuntu14.04。
但是如果没有经过迁移测试，很难确认数据是否备份好了，因此稳妥起见，还是平行安装最新版本在另一个机器上，待数据迁移测试成功后，再对老系统做回归升级。

**Comment by zhblue** [comment]
最新版本的系统，install目录里的bak.sh和restore.sh是可以配套使用的。

**Comment by xiekeyi98** [comment]
非常感谢您，我去尝试一下。

**Comment by xiekeyi98** [comment]
对于其他问题都能较好解决，不过早起版本是apache，自己apache跑了不止一个网站，现在脚本内却默认安装nginx……
比较费劲

**Comment by xiekeyi98** [comment]
您好，很抱歉再打扰到您@zblue，还有一些问题希望能得到您的帮助：
1. 我服务器在跑apache，安装脚本中会安装nginx，导致冲突问题。
2. 我在新电脑上成功安装后，再导入回表等信息后，会出现无限**编译中**的情况。查询issues后，发现是缺少添加judger字段。在这里有一些问题： 1. judger字段的数据类型是什么？  2. in_date的数据timedate类型似乎不在新版本mysql中受支持，我更改成了 datestamp类型是否可以？
3. 我在**想当然**的进行了一些操作后，现在出现了新机器的服务器无法打开，重启nginx ，用root重启judged，给web文件夹`chmod -R +777 web`等均不行，检查nginx的相关设置均无误。并且发现，访问`http://IP地址/` 无法打开(HTTP 500 ），但是可以通过`http://ip地址/admin`等正常打开子文件夹。
这是我新机器 : [OJ](http://140.143.200.161/admin/)

**Comment by xiekeyi98** [comment]
我这边解决了这些问题，直接覆盖安装后，并更改nginx监听端口后问题解决。
但是有两个问题：
1. 公告无法更改.
2. 某一个管理员账号，提交总是提示 两次提交不能超过10s.
