### ISSUE TITLE
测试运行失败，提示两次提交间隔10s等问题。

### ISSUE THREAD

**Issue by xiekeyi98** [zhblue/hustoj#265]
您好，在使用中遇到了几个问题：

1.某个账户，提交总是会提示 **You should not submit more than twice in 10 second** , 账号是个管理员账号，但是其他管理员账号等均正常。
2.测试运行功能出现了一些问题，如下：
![image](https://user-images.githubusercontent.com/7782671/39574584-4ef29612-4f0a-11e8-98dc-1a95fa750a62.png)
3.   在 [FAQ](https://github.com/zhblue/hustoj/blob/master/wiki/FAQ.md)中，看到issue#1应该解决了管理员没有查看别人代码权限的问题，但是很抱歉我没找到issue#1，自己在数据库中也没有找到相关选项修改，希望能得到一些帮助。

**Comment by zhblue** [comment]
后台，给自己加source_browser权限后重新登录。
扫一下你图里的二维码，那个公众号会回答一些常见问题。

**Comment by zhblue** [comment]
你要看看你的这个“某个帐户”的上次提交，是否发生在未来的时间，这可能与你的数据库和系统时钟不匹配导致。

**Comment by zhblue** [comment]
尽量使用火狐、谷歌浏览器，不要用奇怪的360之类国产浏览器，甚至是ie。
如果学校机房只有ie，请在db_info.inc.php里找到bs3，修改为ie

**Comment by xiekeyi98** [comment]
非常感谢您。
好的，谢谢您。
我查到自己账户时间确实出了一些问题，尽管老版时间正常。

**Comment by zhblue** [comment]
时钟问题，参考db_info.inc.php末尾两句注释掉的代码
https://github.com/zhblue/hustoj/blob/master/trunk/web/include/db_info.inc.php#L87

**Comment by xiekeyi98** [comment]
这边还有一个问题是：
目前我们这里是新老OJ并行。
老OJ下可以新建比赛，新OJ下新建比赛失败
返回语句：
![image](https://user-images.githubusercontent.com/7782671/39617311-c80e3360-4fb1-11e8-8f47-d24448976fa6.png)

查了一下感觉数据库没什么问题：
![image](https://user-images.githubusercontent.com/7782671/39617333-e6bb3542-4fb1-11e8-9a90-029cf7774438.png)

感觉问题可能出在contest_add.php中：
![image](https://user-images.githubusercontent.com/7782671/39617359-fe3f4104-4fb1-11e8-88b4-07ffd0a9d0fd.png)


和老板对比了一下发现php有了较大改动，因为自己不太熟悉php。
还得麻烦您协助排查一下

**Comment by zhblue** [comment]
老系统升级中一个关键步骤是在新的web后台，点击一次更新数据库，以修订数据库结构，适应新功能。
你的数据库明显少了字段。如不能更新成功，可以对照新版db.sql，手工增加新的字段

**Comment by xiekeyi98** [comment]
好的，谢谢您，因为我这边已经反复在后台更新过数据库了，更新前大部分数据都不对，更新后大多都可以了。
我一开始以为，是php使用的sql语句有问题，或者是数据库权限有问题呢，那我对比一下db.sql。

**Comment by xiekeyi98** [comment]
非常非常感谢您，
添加password字段后问题解决。
![image](https://user-images.githubusercontent.com/7782671/39619397-460b48cc-4fba-11e8-9454-df3a23192a2e.png)

-------

另外有一个小feature可以建议一下：
开启了WA后自动显示对比数据功能以后，在比赛状态中，选手一样可以查看数据。
我认为可以添加默认情况下，比赛中是关闭这个功能的。

**Comment by zhblue** [comment]
很多老师用比赛来布置作业，主要面向初学者，因此这个功能还是要开放的。
如果是比较严谨的现场赛，可以全局关闭该功能。

**Comment by xiekeyi98** [comment]
明白了，是我没考虑到这种情况。
非常感谢张老师您。
