### ISSUE TITLE
永久编译中

### ISSUE THREAD

**Issue by jackcxiao** [zhblue/hustoj#267]
解决了永久pending,出现了永久编译中的问题，但是在/home/judge/date中也有对应的in 和out 文件，想问你一下这种情况是怎么回事，严格按照14.04的安装，不过是把数据库从本地 换到了另外一个服务器上去。

**Comment by jackcxiao** [comment]
已查阅到相关信息。

**Comment by Brucehml** [comment]
怎么解决的，我现在也这样
