### ISSUE TITLE
setMessage无法排版

### ISSUE THREAD

**Issue by jizhuozhi** [zhblue/hustoj#272]
对msg居中排版的时候，查看`msg.txt`发现返回给`setmsg.php`的文本串中间多了一些意想不到的标签`<p st<x>yle="text-align:center;">`

**Comment by zhblue** [comment]
这是为了防止XSS，禁止了style标签，用<center></center>就没事了。

**Comment by zhblue** [comment]
或者，在这里
https://github.com/zhblue/hustoj/blob/master/trunk/web/include/my_func.inc.php#L139
把style这个数组元素删除，就不会过滤了。

**Comment by jizhuozhi** [comment]
非常感谢，问题已经解决
