### ISSUE TITLE
是否可以一次性删除多个题目？

### ISSUE THREAD

**Issue by 591442386** [zhblue/hustoj#287]
如题，请大佬解答。

**Comment by zhblue** [comment]
删题需要确认文件系统的可操作性，并且涉及数据库和测试数据的删除，单个题目的删除操作都应尽量避免。大量题目的删除，建议手工从命令行删除文件，然后从数据库用sql删除。操作前做好数据备份，以免删库跑路。

**Comment by 591442386** [comment]
张老师是否可以提供一下文件的位置以及数据库中的表名称呢？

**Comment by 591442386** [comment]
好的，谢谢！

**Comment by 591442386** [comment]
但删除了这些题目之后，题目页面出现了大片空白，是否可以删除它们（或者修改当前题目的序号呢？）

**Comment by zhblue** [comment]
发送“彩蛋”到微信公众号hustoj

**Comment by 591442386** [comment]
找到了，谢谢张老师！
