### ISSUE TITLE
Problem Editor

### ISSUE THREAD

**Issue by jizhuozhi** [zhblue/hustoj#293]
最新的problem editor编辑问题提交后，部分字符会消失，例如`hello,world`在提交后会显示为`helloworld`

**Comment by melongist** [comment]
ok! :) I will fix it...

When we use Kindeditor, if we put ',' character, it would be change to other character..

So, It can be fix like below...

...
`$description = str_replace(",", "&#44; ", `$description);`
...

**Comment by jizhuozhi** [comment]
Understood ! :) thank you
