### ISSUE TITLE
在Ubuntu 16.04中MLE会被误报成RE

### ISSUE THREAD

**Issue by ycq3** [zhblue/hustoj#303]
以A+B为例，程序代码如下：
`#include<iostream>
#include<cmath>
#include<cstring>
#include<algorithm>
#include<string>
using namespace std;

int main() {
        int k=30000;
        while(k--){
                new char [25555];
        }
        int a,b;
        while(cin>>a>>b){
                cout<<a+b<<endl;
        }
        return 0;
}
`
在Ubuntu16.04中报 Runtime Error:Segmentation fault，14版本中正常。
我的系统信息如下：Ubuntu 16.04 LTS 32位，内存4G

**Comment by zhblue** [comment]
include部分不完整，请重新发一下

**Comment by zhblue** [comment]
在腾讯云32位16.04测试正常，怀疑与32位有关。
近期修补过一个32位上的内存相关bug，建议更新一下judged，然后测试。

**Comment by ycq3** [comment]
首先非常感谢您的回答，但是我经过尝试问题依旧，使用的已经是最新版本的Judge和Judge_client,在32位系统上出现RE错误而64位系统没有问题。可能您需要在32位系统上测试一下

**Comment by zhblue** [comment]
点击RE，看一下详细内容是否有提示

**Comment by ycq3** [comment]
报错内容如下：Runtime Error:Segmentation fault。如果您那边没有出现这个问题那么有可能是我环境的问题，我重装一下试试看

**Comment by zhblue** [comment]
特意在阿里云购买了一台32位16.04, 安装导入A+B，提交代码
```
#include<iostream>
using namespace std;
 
int main() {
int k=30000;
while(k--){
new char [25555];
}
int a,b;
while(cin>>a>>b){
cout<<a+b<<endl;
}
return 0;
}
/**************************************************************
    Problem: 1000
    User: admin
    Language: C++
    Result: 内存超限
****************************************************************/
```

**Comment by zhblue** [comment]
检查下题目设置的内存大小是否超过了物理内存的大小？

**Comment by zhblue** [comment]
另外，测试数据应该以.in .out结尾，区分大小写，数据应与程序预期一致。

**Comment by ycq3** [comment]
感谢作者的测试，后经查是由于机房设备过旧的问题导致，您的评测机给我的开发提供了不少灵感，再次表示感谢。
