### ISSUE TITLE
Is is possible to make default for python 2.X and python 3.X ? 

### ISSUE THREAD

**Issue by melongist** [zhblue/hustoj#304]
There is a desire to support the Python programming language by default.

Also, there is a saying that the Python programming language that is enabled by default does not work easily.

On the other hand, there is a demand that you also support python 3.X without special installation and setup.

Is there a way to easily install and use the 3.x version of python?
Or is there a way to support the 2.X and 3.X versions together by default?

**Comment by zhblue** [comment]
Both 2 and 3 Python works in a special way:
declare your code interpreter with shell style statement:
```
#!/python2
```
or
```
#!/python3
```
by default python3

**Comment by melongist** [comment]
Thank you~ :)
