### ISSUE TITLE
添加 python3 问题

### ISSUE THREAD

**Issue by wilsonjuxta** [zhblue/hustoj#309]
新增 python3 的时候，提交代码运行总是报`Fatal Python error: Failed to open /dev/urandom`错误。
代码如下
```
#!/python3
a,b=input().split()
print(int(a)+int(b))
```
服务上直接运行是可以的。请问下，这个需要怎么操作呢~

**Comment by zhblue** [comment]
try make a bind to the /dev/urandom file in chroot system
i'll do that later

**Comment by zhblue** [comment]
it should be done already ?
maybe you can try upgrade core and recompile it and install to /usr/bin
by using:
sudo svn up /home/judge/src/core
cd /home/judge/src/core
sudo bash make.sh

**Comment by zhblue** [comment]
刚刚装好输入法，请升级一下core然后编译安装再试试。

**Comment by wilsonjuxta** [comment]
谢谢回复~我们用的还是之前老版本的 core, 之前升级了不过一直都在 Compiling, 就又回到之前的了~~

**Comment by zhblue** [comment]
compiling... problem is caused by the difference between new version and the old one.
try update web at the same time and use the updatedatabase button in admin menu
or
try add a new field to table solution  judger char(16) null default 'local'
