### ISSUE TITLE
SIM显示了一个奇怪的id

### ISSUE THREAD

**Issue by KaitoHH** [zhblue/hustoj#310]
我使用docker部署，手动打开SIM开关后，状态旁边显示的SIM是一个奇怪的id
![qq 20180919225439](https://user-images.githubusercontent.com/13927774/45761563-0fee7180-bc5f-11e8-81a9-9937b757edde.png)

**Comment by zhblue** [comment]
可能是sim模块没有编译成功，比如却少flex

**Comment by KaitoHH** [comment]
感谢回复。所以我需要尝试进入该容器，手动检查一下SIM模块对吗，谢谢。

**Comment by zhblue** [comment]
是的，不太推荐使用docker，会有一些地方产生额外的故障，推荐用原生系统，docker尽量用volume存放测试数据、数据库、web目录，避免使用aufs，可能会造成磁盘空间耗尽。

**Comment by KaitoHH** [comment]
我仔细研究了一下 发现只有每次启动docker时候的第一次判题会正常调用SIM模块，之后就不会再调用SIM了。

**Comment by zhblue** [comment]
这恐怕只能表明docker并不是一个正常的运行环境，不管官方如何标榜它的透明兼容可维护，在这些诡异的事情发生的时候，还是推荐你用原生系统。

**Comment by KaitoHH** [comment]
好的，感谢回复。服务器上由于还有别的服务在运行，不太想破坏原有的系统环境，所以使用了docker来部署。我主要觉得这些问题还是由于`dockerfile`不够完善或者配置有误导致的，而不是docker本身的问题。由于我对hustoj的整个架构不是特别了解，所以我没办法进一步解决这个问题了。如果您愿意尝试解决的话，可以进一步联系我，我可以提供服务器的连接方式供解决，还可以直接通过bash连接到docker容器内部来调试问题。hustoj是一个优秀的开源OJ系统，再次感谢您的回复！

如果没有进一步回复，您可以关闭该issues。谢谢！

**Comment by zhblue** [comment]
sim是用一个子进程去运行的，也许你的docker环境限制了fork的数量？
docker我并不很熟悉，不过确实有公司在生产环境使用docker部署hustoj的判题端，因为sim好像不是静态编译的，请确保docker环境中有sim所需的.so文件，可以进入docker用ldd检查一下。

**Comment by KaitoHH** [comment]
你好，我已经解决了，我发现问题出在`awk`上，每次重新启动docker后的第一次评测会把`/etc/altervative`下的文件全部清空，导致之后的评测在调用`sim.sh`的时候提示找不到`awk`，我重新build了一个Docker解决了这些问题，这是我的Dockerfile文件
```
FROM shiningrise/hustoj:latest

RUN chmod +x /home/judge/src/core/make.sh
RUN cd /home/judge/src/core/ && ./make.sh
RUN cd /usr/bin && rm awk && cp -s mawk awk
```
希望提供一些参考，这样在下一次更新时也许可以修复这些问题。
再次感谢回复！
