### ISSUE TITLE
ZOJ模式下答案中的换行符，用户输出为空格时判为AC？

### ISSUE THREAD

**Issue by whuangxm** [zhblue/hustoj#324]
如果用户输出是
```1 2 3 4``` ，
答案是
```
1
2
3
4
```
判题结果为AC；但把`#define ZOJ_COM`注释掉，即变成PE（格式错误）。
这样是否合理？谢谢！

**Comment by zhblue** [comment]
这取决于出题人的意图，是否要考察格式。
如果要严格的PE，可以考虑注释掉下述定义
#define IGNORE_ESOL   //ignore the ending space char of lines while comparing
