### ISSUE TITLE
是否可以运行时间超过限制的时间的2倍再kill掉

### ISSUE THREAD

**Issue by taoting1234** [zhblue/hustoj#339]
是否可以运行时间超过限制的时间的2倍再kill掉，这样可以看是不是被卡常数了
比如这题时间1000ms，我的代码1300ms，显示运行1300ms，提示运行超时

**Comment by taoting1234** [comment]
![image](https://user-images.githubusercontent.com/19506467/47480380-cd721300-d862-11e8-9647-578a832fd27c.png)
实际上是显示1000ms超时，而不是提示2000ms超时

**Comment by zhblue** [comment]
凡是超时的都按限时去显示

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/blob/master/trunk/core/judge_client/judge_client.cc#L2542

**Comment by zhblue** [comment]
这样写的原因就是总是被问相关的问题，比如996ms为什么超时了，限时1秒为什么跑到2000ms？

**Comment by taoting1234** [comment]
好的，谢谢，我已经修改，感谢

**Comment by zhblue** [comment]
不客气
