### ISSUE TITLE
Could discuss support rich text editor or markdown editor?

### ISSUE THREAD

**Issue by jizhuozhi** [zhblue/hustoj#340]
I want to post a code 
```
#include <stdio.h>
int main(){
     printf("hello,world");
}
```
but all indents will be remove , so I got this
```
#include <stdio.h>
int main(){
printf("hello,world");
}
```
Is there any method to keep indents ?

**Comment by zhblue** [comment]
it's not recommended to post code public
still you can replace "discuss" with some full bbs system 
like disscuz or phpbb3
check bbs.php for detail

**Comment by jizhuozhi** [comment]
Thank you very much
