### ISSUE TITLE
Judge_client insert 0 as s_id into sim

### ISSUE THREAD

**Issue by jizhuozhi** [zhblue/hustoj#341]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/31175030/47497568-1939b200-d88d-11e8-9006-a59b263fe443.png">
Primary key is always 0 so no matter how many sim insert.

**Comment by jizhuozhi** [comment]
Web pages and database are running on centos7.

**Comment by zhblue** [comment]
manually add some debug log in judge_client.cc
try figure out what sql exactlly has been send to mysql/mariadb

**Comment by jizhuozhi** [comment]
![image](https://user-images.githubusercontent.com/31175030/47548919-08407d80-d92d-11e8-93c9-a2b0201fc746.png)
Here is sql query what's my judge_client executed and rows selected from sim table.
It seems nothing wrong but s_id is always 0.

**Comment by jizhuozhi** [comment]
Maybe not free result？

**Comment by zhblue** [comment]
what will it show?
`MariaDB[jol]>desc sim;`

**Comment by jizhuozhi** [comment]
![image](https://user-images.githubusercontent.com/31175030/47549552-011a6f00-d92f-11e8-90e3-06e17ad46a37.png)

**Comment by jizhuozhi** [comment]
I found a trigger from `db.sql`
```
delimiter //
drop trigger if exists simfilter//
create trigger simfilter
before insert on sim
for each row
begin
 declare new_user_id varchar(64);
 declare old_user_id varchar(64);
 select user_id from solution where solution_id=new.s_id into new_user_id;
 select user_id from solution where solution_id=new.sim_s_id into old_user_id;
 if old_user_id=new_user_id then
	set new.s_id=0;
 end if;
 
end;//
delimiter ;
```
Is that mean if two solutions is sumitted by same user, it will not insert?

**Comment by zhblue** [comment]
yes, "self-copy" will not be treated as cheat

**Comment by jizhuozhi** [comment]
![image](https://user-images.githubusercontent.com/31175030/47551866-e13a7980-d935-11e8-864f-04647353a86a.png)
I tried an other use to submit same code, it works , thank you!!!
