### ISSUE TITLE
代码提交页面，如果先手动改了输出框里的内容就会导致测试运行结果不会显示

### ISSUE THREAD

**Issue by taoting1234** [zhblue/hustoj#348]
代码提交页面，如果先手动改了输出框里的内容就会导致测试运行结果不会显示

**Comment by zhblue** [comment]
try this update
https://github.com/zhblue/hustoj/commit/2bd4e4c1b4407d5dfb168ad3d0f1bf3ed8929216

**Comment by taoting1234** [comment]
好的，已解决
