### ISSUE TITLE
关于re

### ISSUE THREAD

**Issue by taoting1234** [zhblue/hustoj#349]
![image](https://user-images.githubusercontent.com/19506467/47647905-6a121900-dbb3-11e8-8cc5-cf14f5efa0cc.png)
已经加了并重新编译，重启过judged，用debug模式显示
![image](https://user-images.githubusercontent.com/19506467/47647999-a6de1000-dbb3-11e8-97bd-310da7b57765.png)
都已经添加，还是提示这个CALLID:99

**Comment by taoting1234** [comment]
![image](https://user-images.githubusercontent.com/19506467/47648034-bd846700-dbb3-11e8-9d4b-9d3d5169a8e9.png)

**Comment by zhblue** [comment]
是用make.sh编译的么？
如果不是，需要手工覆盖新的judge_client到/usr/bin

**Comment by taoting1234** [comment]
是用make.sh编译的

**Comment by zhblue** [comment]
sudo ./make.sh ?

**Comment by taoting1234** [comment]
是的

**Comment by zhblue** [comment]
修改后你重新提交了那份代码或者重判了那个提交么？

**Comment by taoting1234** [comment]
重新提交了

**Comment by zhblue** [comment]
用debug模式去判这个提交呢？

**Comment by taoting1234** [comment]
就是上面那个截图

**Comment by taoting1234** [comment]
![image](https://user-images.githubusercontent.com/19506467/47648474-19032480-dbb5-11e8-9cf2-885850b24401.png)
ifconfig|grep 'inet'|awk -F: '{printf $2}'|awk  '{printf $1}'
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f /home/judge/run0//dev 2>/dev/null
/bin/umount -f /home/judge/run0//lib 2>/dev/null
/bin/umount -f /home/judge/run0//lib64 2>/dev/null
/bin/umount -f /home/judge/run0//etc/alternatives 2>/dev/null
/bin/umount -f /home/judge/run0//usr 2>/dev/null
/bin/umount -f /home/judge/run0//bin 2>/dev/null
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f bin usr lib lib64 etc/alternatives proc dev 2>/dev/null
/bin/umount -f /home/judge/run0//* 2>/dev/null
/bin/umount -f /home/judge/run0//log/* 2>/dev/null
/bin/umount -f /home/judge/run0//log/etc/alternatives 2>/dev/null
/bin/rm -rf /home/judge/run0//log/* 2>/dev/null
mkdir /home/judge/run0//log/ 2>/dev/null
/bin/mv /home/judge/run0//* /home/judge/run0//log/ 2>/dev/null
/bin/mkdir -p /dev/shm/hustoj//home/judge/run0/  2>/dev/null
/bin/ln -s /dev/shm/hustoj//home/judge/run0/ /home/judge/  2>/dev/null
/bin/chown judge /dev/shm/hustoj//home/judge/run0/  2>/dev/null
chmod 755 /dev/shm/hustoj//home/judge/run0/  2>/dev/null
/bin/ln -s /home/judge/data /dev/shm/hustoj//home/judge/  2>/dev/null
Main=Main.cchown judge /home/judge/run0//Main.c
time: 1 mem: 128
status=0
/bin/umount -f bin usr lib lib64 etc/alternatives proc dev 2>/dev/null
/bin/umount -f /home/judge/run0//* 2>/dev/null
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f /home/judge/run0//dev 2>/dev/null
/bin/umount -f /home/judge/run0//lib 2>/dev/null
/bin/umount -f /home/judge/run0//lib64 2>/dev/null
/bin/umount -f /home/judge/run0//etc/alternatives 2>/dev/null
/bin/umount -f /home/judge/run0//usr 2>/dev/null
/bin/umount -f /home/judge/run0//bin 2>/dev/null
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f bin usr lib lib64 etc/alternatives proc dev 2>/dev/null
/bin/umount -f /home/judge/run0//* 2>/dev/null
/bin/umount -f /home/judge/run0//log/* 2>/dev/null
/bin/umount -f /home/judge/run0//log/etc/alternatives 2>/dev/null
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f /home/judge/run0//dev 2>/dev/null
/bin/umount -f /home/judge/run0//lib 2>/dev/null
/bin/umount -f /home/judge/run0//lib64 2>/dev/null
/bin/umount -f /home/judge/run0//etc/alternatives 2>/dev/null
/bin/umount -f /home/judge/run0//usr 2>/dev/null
/bin/umount -f /home/judge/run0//bin 2>/dev/null
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f bin usr lib lib64 etc/alternatives proc dev 2>/dev/null
/bin/umount -f /home/judge/run0//* 2>/dev/null
/bin/umount -f /home/judge/run0//log/* 2>/dev/null
/bin/umount -f /home/judge/run0//log/etc/alternatives 2>/dev/null
/bin/cp '/home/judge/data/1579/test.in' /home/judge/run0//data.in
/bin/cp /home/judge/data/1579/*.dic /home/judge/run0// 2>/dev/null
init_call_counter:0
pid=56489 judging /home/judge/data/1579/test.in
/bin/grep 'python2' Main.py 2>/dev/null
/bin/cp '/home/judge/data/1579/sample.in' /home/judge/run0//data.in
/bin/cp /home/judge/data/1579/*.dic /home/judge/run0// 2>/dev/null
init_call_counter:0
pid=56496 judging /home/judge/data/1579/sample.in
/bin/grep 'python2' Main.py 2>/dev/null
/usr/bin/sim.sh Main.c 1579
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f /home/judge/run0//dev 2>/dev/null
/bin/umount -f /home/judge/run0//lib 2>/dev/null
/bin/umount -f /home/judge/run0//lib64 2>/dev/null
/bin/umount -f /home/judge/run0//etc/alternatives 2>/dev/null
/bin/umount -f /home/judge/run0//usr 2>/dev/null
/bin/umount -f /home/judge/run0//bin 2>/dev/null
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f bin usr lib lib64 etc/alternatives proc dev 2>/dev/null
/bin/umount -f /home/judge/run0//* 2>/dev/null
/bin/umount -f /home/judge/run0//log/* 2>/dev/null
/bin/umount -f /home/judge/run0//log/etc/alternatives 2>/dev/null
/bin/rm -rf /home/judge/run0//log/* 2>/dev/null
mkdir /home/judge/run0//log/ 2>/dev/null
/bin/mv /home/judge/run0//* /home/judge/run0//log/ 2>/dev/null
result=4
int LANG_CV[256]={0,1,5,12,21,59,63,89,158,231,0};
int LANG_CC[256]={HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,0};

**Comment by zhblue** [comment]
这里有点奇怪，你的RE说有99，但是debug模式里没有。
而且debug模式判出来是AC的result=4，你在前台应该能看到AC的结果。

**Comment by zhblue** [comment]
你的RE是76380但是你的debug跑的是76458，这两个提交的代码是相同的么？

**Comment by taoting1234** [comment]
![image](https://user-images.githubusercontent.com/19506467/47648618-81ea9c80-dbb5-11e8-8ba5-24ece247b894.png)
debug模式判一下就过了

**Comment by taoting1234** [comment]
但是直接交确实re

**Comment by taoting1234** [comment]
![image](https://user-images.githubusercontent.com/19506467/47648672-a2b2f200-dbb5-11e8-8698-bd6e5e90937c.png)
代码全部相同

**Comment by taoting1234** [comment]
还有，我如果最后不加c的参数的话
![image](https://user-images.githubusercontent.com/19506467/47648765-ec9bd800-dbb5-11e8-8359-65ae92dd2689.png)
debug就是re

**Comment by taoting1234** [comment]
ifconfig|grep 'inet'|awk -F: '{printf $2}'|awk  '{printf $1}'
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f /home/judge/run0//dev 2>/dev/null
/bin/umount -f /home/judge/run0//lib 2>/dev/null
/bin/umount -f /home/judge/run0//lib64 2>/dev/null
/bin/umount -f /home/judge/run0//etc/alternatives 2>/dev/null
/bin/umount -f /home/judge/run0//usr 2>/dev/null
/bin/umount -f /home/judge/run0//bin 2>/dev/null
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f bin usr lib lib64 etc/alternatives proc dev 2>/dev/null
/bin/umount -f /home/judge/run0//* 2>/dev/null
/bin/umount -f /home/judge/run0//log/* 2>/dev/null
/bin/umount -f /home/judge/run0//log/etc/alternatives 2>/dev/null
/bin/rm -rf /home/judge/run0//log/* 2>/dev/null
mkdir /home/judge/run0//log/ 2>/dev/null
/bin/mv /home/judge/run0//* /home/judge/run0//log/ 2>/dev/null
/bin/mkdir -p /dev/shm/hustoj//home/judge/run0/  2>/dev/null
/bin/ln -s /dev/shm/hustoj//home/judge/run0/ /home/judge/  2>/dev/null
/bin/chown judge /dev/shm/hustoj//home/judge/run0/  2>/dev/null
chmod 755 /dev/shm/hustoj//home/judge/run0/  2>/dev/null
/bin/ln -s /home/judge/data /dev/shm/hustoj//home/judge/  2>/dev/null
Main=Main.cchown judge /home/judge/run0//Main.c
time: 1 mem: 128
status=0
/bin/umount -f bin usr lib lib64 etc/alternatives proc dev 2>/dev/null
/bin/umount -f /home/judge/run0//* 2>/dev/null
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f /home/judge/run0//dev 2>/dev/null
/bin/umount -f /home/judge/run0//lib 2>/dev/null
/bin/umount -f /home/judge/run0//lib64 2>/dev/null
/bin/umount -f /home/judge/run0//etc/alternatives 2>/dev/null
/bin/umount -f /home/judge/run0//usr 2>/dev/null
/bin/umount -f /home/judge/run0//bin 2>/dev/null
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f bin usr lib lib64 etc/alternatives proc dev 2>/dev/null
/bin/umount -f /home/judge/run0//* 2>/dev/null
/bin/umount -f /home/judge/run0//log/* 2>/dev/null
/bin/umount -f /home/judge/run0//log/etc/alternatives 2>/dev/null
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f /home/judge/run0//dev 2>/dev/null
/bin/umount -f /home/judge/run0//lib 2>/dev/null
/bin/umount -f /home/judge/run0//lib64 2>/dev/null
/bin/umount -f /home/judge/run0//etc/alternatives 2>/dev/null
/bin/umount -f /home/judge/run0//usr 2>/dev/null
/bin/umount -f /home/judge/run0//bin 2>/dev/null
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f bin usr lib lib64 etc/alternatives proc dev 2>/dev/null
/bin/umount -f /home/judge/run0//* 2>/dev/null
/bin/umount -f /home/judge/run0//log/* 2>/dev/null
/bin/umount -f /home/judge/run0//log/etc/alternatives 2>/dev/null
/bin/cp '/home/judge/data/1579/test.in' /home/judge/run0//data.in
/bin/cp /home/judge/data/1579/*.dic /home/judge/run0// 2>/dev/null
init_call_counter:0
pid=60213 judging /home/judge/data/1579/test.in
/bin/grep 'python2' Main.py 2>/dev/null
[ERROR] A Not allowed system call: runid:76458 CALLID:99
 TO FIX THIS , ask admin to add the CALLID into corresponding LANG_XXV[] located at okcalls32/64.h ,
and recompile judge_client. 
if you are admin and you don't know what to do ,
chinese explaination can be found on https://zhuanlan.zhihu.com/p/24498599

[ERROR] A Not allowed system call: runid:76458 CALLID:99
 TO FIX THIS , ask admin to add the CALLID into corresponding LANG_XXV[] located at okcalls32/64.h ,
and recompile judge_client. 
if you are admin and you don't know what to do ,
chinese explaination can be found on https://zhuanlan.zhihu.com/p/24498599

WTERMSIG=9
Killed
/bin/cp '/home/judge/data/1579/sample.in' /home/judge/run0//data.in
/bin/cp /home/judge/data/1579/*.dic /home/judge/run0// 2>/dev/null
init_call_counter:0
pid=60220 judging /home/judge/data/1579/sample.in
/bin/grep 'python2' Main.py 2>/dev/null
add RE info of 76458..... 
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f /home/judge/run0//dev 2>/dev/null
/bin/umount -f /home/judge/run0//lib 2>/dev/null
/bin/umount -f /home/judge/run0//lib64 2>/dev/null
/bin/umount -f /home/judge/run0//etc/alternatives 2>/dev/null
/bin/umount -f /home/judge/run0//usr 2>/dev/null
/bin/umount -f /home/judge/run0//bin 2>/dev/null
/bin/umount -f /home/judge/run0//proc 2>/dev/null
/bin/umount -f bin usr lib lib64 etc/alternatives proc dev 2>/dev/null
/bin/umount -f /home/judge/run0//* 2>/dev/null
/bin/umount -f /home/judge/run0//log/* 2>/dev/null
/bin/umount -f /home/judge/run0//log/etc/alternatives 2>/dev/null
/bin/rm -rf /home/judge/run0//log/* 2>/dev/null
mkdir /home/judge/run0//log/ 2>/dev/null
/bin/mv /home/judge/run0//* /home/judge/run0//log/ 2>/dev/null
result=10

**Comment by zhblue** [comment]
你是加32还是64呢？

**Comment by taoting1234** [comment]
64

**Comment by zhblue** [comment]
是否有测试数据文件非常大的情况？

**Comment by taoting1234** [comment]
8M的数据

**Comment by taoting1234** [comment]
可能是这个原因
https://blog.pintia.cn/2018/06/27/glibc-segmentation-fault/

**Comment by taoting1234** [comment]
c的qsort就会re
c++的sort是ac

**Comment by zhblue** [comment]
你的代码里也用了qsort ?

**Comment by taoting1234** [comment]
是的

**Comment by zhblue** [comment]
可否发送这个答案和触发RE的数据到我的邮箱 10982766@企鹅.com

**Comment by zhblue** [comment]
结论是需要按顺序添加新的callid
