### ISSUE TITLE
已有lnmp环境如何安装

### ISSUE THREAD

**Issue by YoufuYu** [zhblue/hustoj#352]
作者你好，打扰了。我的服务器已经安装了nginx,mysql,php，请问一下可不可以不用一键脚本安装，而是像常规的网站那样安装。

**Comment by zhblue** [comment]
可以参考早期手动安装的说明
https://github.com/zhblue/hustoj/blob/2ae69872857def0c91f0cf89495caa8db76b4855/trunk/install/README
所需的db.sql在install目录
php代码在web目录
判题代码在core目录
可以从Release下载打包版本解压。

**Comment by YoufuYu** [comment]
我按照安装说明里面新建普通用户后报了500错误，还有就是我一直都没找到连接接数据库的配置文件

**Comment by YoufuYu** [comment]
连接数据库配置文件找到了，500错误还是没有解决

**Comment by zhblue** [comment]
检查nginx日志文件

**Comment by zhblue** [comment]
error.log

**Comment by YoufuYu** [comment]
2018/11/09 10:44:49 [notice] 28962#0: signal process started
2018/11/09 10:45:34 [notice] 29008#0: signal process started
额，打开就只有这个......

**Comment by zhblue** [comment]
打开db_info.inc.php第一行的报错显示

**Comment by zhblue** [comment]
安装可能依赖的php模块，参考标准安装脚本

**Comment by zhblue** [comment]
可以写一个phpinfo.php，然后对照安装脚本，看缺什么。
最好装一个memecached，可以加速页面显示，提高并发数量。
