### ISSUE TITLE
关于okcalls64.h的一个问题

### ISSUE THREAD

**Issue by likole** [zhblue/hustoj#359]
本机环境:Ubuntu 16.04 LTS 64位
提示需要添加新的系统调用,添加了新的CALLID并编译后,发现依然找不到需要的CALLID
调试后发现,貌似64位的SYS_read的系统调用号为0,会导致数组中SYS_read后面的CALLID都失效
(不懂是不是所有64位的SYS_read都为0,如果是的话,个人觉得可以去掉)

**Comment by zhblue** [comment]
0是个特例，当这个callid为0的时候只能放在数组最前面

**Comment by likole** [comment]
但在数组的中间部分也出现了SYS_read

**Comment by zhblue** [comment]
这个是32位系统历史遗留问题，新加的均以数字为准。如有意进行清理，可以手工删除。
