### ISSUE TITLE
这个判题核心是否可以集成到其它web应用？

### ISSUE THREAD

**Issue by maxlv7** [zhblue/hustoj#374]
我这边想单独做web端，采用tornado。请问这个判题核心可以单独使用吗？

**Comment by zhblue** [comment]
可以单独使用，可以用共享数据库或者模拟HTTP_JUDGE服务端两种方式使用。

**Comment by maxlv7** [comment]
> 可以单独使用，可以用共享数据库或者模拟HTTP_JUDGE服务端两种方式使用。

好的 我试试
