### ISSUE TITLE
排名的模糊搜索，如果搜索结果超过50个，点击51~100看下一页就不再是搜索状态

### ISSUE THREAD

**Issue by iamwinter** [zhblue/hustoj#381]
排名的模糊搜索，搜索结果显示前50个，如果我想看51~100，点击后，并不是我搜索的结果。希望作者解决一下

**Comment by zhblue** [comment]
收到，待解决

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/commit/67e43bc0adc72cbc1b905651a1b7ac11610d8eb3
