### ISSUE TITLE
Nginx安装时配置虚拟主机

### ISSUE THREAD

**Issue by jizhuozhi** [zhblue/hustoj#389]
张老师，我想请教一下，可否将安装脚本改为在安装HUSTOJ的时候将配置文件以虚拟主机的形式放到conf.d下或site-enabled目录下，而不直接更改nginx.conf，这样可以避免安装中断后再次安装出现的一些问题

**Comment by zhblue** [comment]
可以，我也考虑过，暂时没有时间去做。
我倾向于把sites-available里的default复制一个hustoj，还是放在sites-available里，
然后删除原来sites-enabled里面的软连接default，然后建一个新的软连接hustoj，连接到hustoj上。

**Comment by jizhuozhi** [comment]
我的想法是在Ubuntu 下删除sites-enabled中对sites-available/default的软连接（sites-enabled保留），而Centos7因为我当初改的脚本是直接从[https://nginx.org](https://nginx.org)下载的nginx.rpm，所以没有sites-*文件夹，只有conf.d，这样我们可以写出一个通用的虚拟主机配置文件hustoj.conf，放到conf.d替换掉原有的default.conf

**Comment by jizhuozhi** [comment]
这样可以保证两个系统的配置基本一致，减少运维的难度

**Comment by zhblue** [comment]
那你可以先拿centos的安装脚本来改造，ubuntu的暂时维持原装。

**Comment by jizhuozhi** [comment]
Centos7中确实是有这一行
```shell
DBPASS=`tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1`
```
我的简单做法就是当一切任务完成后再更改密码（放到FPC和CSharp前），这样就保证了更改数据库密码的操作一定是在一切就绪后执行的

**Comment by zhblue** [comment]
当然可以，请提交符合该描述的PR，我来审阅通过

**Comment by jizhuozhi** [comment]
请稍等，正在重新克隆一个仓库，原有的仓库README被我进行了重改造，当前不适合进行PR。张老师也可以对我更改后的README提出一些建议——[传送门](http://gitlab.mgdream.com.cn/jiuming/hustoj)
