### ISSUE TITLE
Centos7 Python is not executable

### ISSUE THREAD

**Issue by jizhuozhi** [zhblue/hustoj#395]
Python is not executable in Centos7 ( no matter python2.7 or python3.6)
I try to run `judge_client 1036 0 /home/judge > debug.log` manually ( without DEBUG because there is no need to know what did , and debug.log is used to split stdout and stderr )

I got this stderr
```shell
...
cp: 写入"/home/judge/run0//usr/lib64/python2.7/uuid.pyc" 出错: 设备上没有空间
cp: 扩展"/home/judge/run0//usr/lib64/python2.7/uuid.pyc" 失败: 设备上没有空间
cp: 无法获取"/usr/local/lib/python*" 的文件状态(stat): 没有那个文件或目录
cp: 写入"/home/judge/run0//usr/include/python2.7/pyconfig-64.h" 出错: 设备上没有空间
cp: 扩展"/home/judge/run0//usr/include/python2.7/pyconfig-64.h" 失败: 设备上没有空间
cp: 无法获取"/usr/lib/libpython*" 的文件状态(stat): 没有那个文件或目录
/bin/grep: 写错误: 设备上没有空间
/bin/cp: 写入"/home/judge/run0//data.in" 出错: 设备上没有空间
/bin/cp: 扩展"/home/judge/run0//data.in" 失败: 设备上没有空间
sh: 第 0 行:echo: 写错误: 设备上没有空间
sh: 第 0 行:echo: 写错误: 设备上没有空间
head: 写入错误: 设备上没有空间
sh: 第 1 行:echo: 写错误: 设备上没有空间
/bin/cp: 写入"/home/judge/run0//data.in" 出错: 设备上没有空间
/bin/cp: 扩展"/home/judge/run0//data.in" 失败: 设备上没有空间
sh: 第 0 行:echo: 写错误: 设备上没有空间
sh: 第 0 行:echo: 写错误: 设备上没有空间
head: 写入错误: 设备上没有空间
sh: 第 1 行:echo: 写错误: 设备上没有空间
``` 

but stdout was nothing wrong

```shell
cid:0
nothing to do!
cid:0
cid:0
/1000/sample.in: mem=0 time=4
cid:0
/1000/sample.in: mem=0 time=4
/1000/test.in: mem=0 time=1
sql:[UPDATE `problem` SET `accepted`=(SELECT count(*) FROM `solution` WHERE `problem_id`=1000 AND `result`=4) WHERE `problem_id`=1000]
```

**Comment by jizhuozhi** [comment]
In order to count how much space it taked, I abstract `copy_python_runtime` and its dependencies to a special `.c` file and create a work directory named sandbox.

I used `du -h` and got this output

```shell
...
62M	./usr/lib64/python2.7
62M	./usr/lib64
0	./usr/local/lib
0	./usr/local
84M	./usr
0	./home/judge
0	./home
4.0K	./etc
1.1G	.
```
and used `df -h |grep /dev/shm` to know the limit space of /dev/shm

```shell
tmpfs                    910M     0  910M    0% /dev/shm
```

There is no doubt that device `tmpfs` is not big enough

**Comment by jizhuozhi** [comment]
Just now , I modified my `/etc/fstab` to enlarge device `tmpfs` to `2GB` , it was working.
I want to enlarge `tmpfs` when install HUSTOJ but I don't know how to decide its size , how about just 2GB or half of total memory ？

**Comment by jizhuozhi** [comment]
Debug is not showing what happened when python executed ( because of `/bin/grep 'python2' Main.py 2>/dev/null` all stdout were output to /dev/null ) .

So I created a sandbox manually ( as above ) , and run python script , got this exception

```shell
[root@localhost ~]# chroot sandbox
bash-4.2# /python Main.py < /1000/test.in > test.out
Can't open '/usr/share/abrt/conf.d/plugins/python.conf': No such file or directory
Can't open '/etc/abrt/plugins/python.conf': No such file or directory
Traceback (most recent call last):
  File "Main.py", line 1, in <module>
    a = input()
  File "<string>", line 1
    12345678 87654321
                    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by jizhuozhi** [comment]
There is a long way to run HUSTOJ in Centos7……

**Comment by jizhuozhi** [comment]
I reviewed `judge_client.cc` and I found this line `int py2 = execute_cmd("/bin/grep 'python2' Main.py 2>/dev/null");` ( in function `run_solution`), I don't know what's mean :( .

In my opinion , this line is executed after `chroot` opinion but there is no grep in sandbox ( even though /bin ) .

There are two way to fix this problem:
1. Copy `/usr/bin/grep` to sandbox
2. Check python2 before chroot and store as a global variable
I prefer to the second one , because of the answer of `what's a sandbox?`.

**Comment by jizhuozhi** [comment]
我怀疑拷贝的运行时环境那么大的原因在于我安装了GUI环境，所以我重新安装了一个最小安装Centos7

```shell
...
0	./dev
0	./home/judge
0	./home
4.0K	./etc
252M	.
```

按照`tmpfs=memory/2`的原则，HUSTOJ for Python最小的运行内存需要512MB

**Comment by zhblue** [comment]
try 
ldd /usr/bin/python3

**Comment by jizhuozhi** [comment]
No such command

```shell
[root@localhost sandbox]# Idd
-bash: Idd: 未找到命令
[root@localhost sandbox]# idd
-bash: idd: 未找到命令
```

**Comment by jizhuozhi** [comment]
No such file or directory

```shell
[root@localhost sandbox]# ldd /usr/bin/python3
ldd: /usr/bin/python3: 没有那个文件或目录
```

**Comment by zhblue** [comment]
那是个小写的L

**Comment by zhblue** [comment]
ldd /usr/bin/python3
        linux-vdso.so.1 =>  (0x00007fff6b9fe000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5e47ed1000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5e47b08000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5e47904000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f5e47701000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f5e474d7000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f5e472be000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5e46fb8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5e480ef000)

**Comment by zhblue** [comment]
ldd:
LDD(1)                     Linux Programmer's Manual                    LDD(1)

NAME
       ldd - print shared library dependencies

SYNOPSIS
       ldd [OPTION]... FILE...

DESCRIPTION
       ldd  prints  the  shared  libraries  required by each program or shared
       library specified on the command line.

   Security
       In the usual  case,  ldd  invokes  the  standard  dynamic  linker  (see
       ld.so(8))  with the LD_TRACE_LOADED_OBJECTS environment variable set to
       1, which causes the linker to display  the  library  dependencies.   Be
       aware,  however,  that  in some circumstances, some versions of ldd may
       attempt to obtain the dependency information by directly executing  the
       program.  Thus, you should never employ ldd on an untrusted executable,
       since this may result in the execution  of  arbitrary  code.   A  safer
       alternative when dealing with untrusted executables is:

不知道centos里是哪个包的，估计跟gcc/make/build相关的

**Comment by jizhuozhi** [comment]
刚刚是我复制粘贴错了，Centos7不同于Ubuntu16.*或Ubuntu18.*，Python3并不是系统的默认依赖，所以并没有默认安装

**Comment by jizhuozhi** [comment]
```shell
...
/bin/cp: 略过目录"/lib64/libuser"
/bin/cp: 略过目录"/lib64/libv4l"
/bin/cp: 略过目录"/lib64/libvirt"
/bin/cp: 写入"/home/judge/run0//lib64/libwebkit2gtk-4.0.so.37.28.5" 出错: 设备上没有空间
/bin/cp: 扩展"/home/judge/run0//lib64/libwebkit2gtk-4.0.so.37.28.5" 失败: 设备上没有空间
/bin/cp: 写入"/home/judge/run0//lib64/libwebkitgtk-3.0.so.0" 出错: 设备上没有空间
/bin/cp: 扩展"/home/judge/run0//lib64/libwebkitgtk-3.0.so.0" 失败: 设备上没有空间
/bin/cp: 写入"/home/judge/run0//lib64/libwebkitgtk-3.0.so.0.22.17" 出错: 设备上没有空间
/bin/cp: 扩展"/home/judge/run0//lib64/libwebkitgtk-3.0.so.0.22.17" 失败: 设备上没有空间
...
```
`tmpfs`不够大不是发生在`copy_python_runtime`，而是发生在`copy_shell_runtime`，可能是因为我安装Centos7带的GUI在`copy_shell_runtime`的时候也一并拷贝过去了

**Comment by zhblue** [comment]
可以先禁用SHM_RUN，建立真实的run0目录取代原来的软连接

**Comment by jizhuozhi** [comment]
我认为可以写在 README.md里，让服务器维护人员自己去决定要不要添加`tmpfs /dev/shm tmpfs size=2G 00`到`/etc/fstab`配置文件，毕竟真正的生产环境不会真的只用2GB的内存，更多的可能是调试时或者时教师备课用的虚拟机，这些内存都是可调的

**Comment by zhblue** [comment]
写在README.md我怕把人都吓跑了，可能单独在Wiki里写一个页面解释这个问题比较好。
README.md最多给个链接

**Comment by ZuyiWang** [comment]
> Just now , I modified my `/etc/fstab` to enlarge device `tmpfs` to `2GB` , it was working.
> I want to enlarge `tmpfs` when install HUSTOJ but I don't know how to decide its size , how about just 2GB or half of total memory ？
Hello，I have faced the same question as yours just now, but I don't know how to modified `/etc/fstab` to enlarge device `tmpfs` to `2GB`, and should I mount it again? Could you tell me how to do it? thanks!

**Comment by mjiuming** [comment]
Using vim to edit `/etc/fstab` and then insert this record into /etc/fstab

```shell
tmpfs /dev/shm tmpfs defaults,size=4096M 0 0
```

after that, you should remount `/dev/shm` just like this

```
umount /dev/shm 
mount /dev/shm
```

your problem should be resolved

**Comment by ZuyiWang** [comment]
Thank you! I get it.
