### ISSUE TITLE
答案唯一时，任意输出都判为正确

### ISSUE THREAD

**Issue by keven11111112** [zhblue/hustoj#397]
http://tk.hustoj.com/problemset.php?search=free
中的6192

**Comment by zhblue** [comment]
已修复，谢谢报告

**Comment by keven11111112** [comment]
请问改的哪个文件哪个地方？https://github.com/zhblue/hustoj.git里修复了吗？

**Comment by zhblue** [comment]
这是题目数据的问题，不是系统代码的问题，补充一个空文件test.in即可

**Comment by keven11111112** [comment]
谢谢
