### ISSUE TITLE
judged.cc里面一个函数返回了两次

### ISSUE THREAD

**Issue by igoing** [zhblue/hustoj#41]
[https://github.com/zhblue/hustoj/blob/master/trunk/core/judged/judged.cc#L313](https://github.com/zhblue/hustoj/blob/master/trunk/core/judged/judged.cc#L313)
[https://github.com/zhblue/hustoj/blob/master/trunk/core/judged/judged.cc#L332](https://github.com/zhblue/hustoj/blob/master/trunk/core/judged/judged.cc#L332)
是写错了还是其它原因？

**Comment by zhblue** [comment]
谢谢，可能是svn或git之类的工具自动合并产生的
