### ISSUE TITLE
安装之后 403 Forbidden

### ISSUE THREAD

**Issue by tesths** [zhblue/hustoj#412]
Ubuntu 16.04 新机器。
安装完成之后登录 127.0.0.1 显示 403 Forbidden。
且找不到 db_info.inc.php 文件，无 /home/judge/src/web/include/ 目录。

**Comment by zhblue** [comment]
可能是安装过程中github访问不通或过慢，导致源码没有下载完整。
可以再次执行脚本，或者下载Release栏目里的https://github.com/zhblue/hustoj/archive/19.03.27.tar.gz 文件，用相应的https://github.com/zhblue/hustoj/blob/master/trunk/install/install-ubuntu16-bytgz.sh 来安装
两个文件放一起，执行
`sudo ./install-ubuntu16-bytgz.sh 19.03.27.tar.gz`
