### ISSUE TITLE
I would like to refer to the source of Judge Engine of HUSTOJ and reproduce Judge Engine with cpp.

### ISSUE THREAD

**Issue by dalbodeule** [zhblue/hustoj#422]
I want to create OnlineJudge. I can create a website, but the JudgeEngine is not at my level. Things like security issues or runtime checks are too difficult. So I would like to refer to HUSTOJ's source and publish it under AGPL-3.0 license. Is this possible?

**Comment by zhblue** [comment]
the judged and judge_client of HUSTOJ is publish under GPLv2, you can use them under GPLv2.
i'm not sure if it works with AGPL-3.0
attention: sim(aka similarity) is not GPL.
check https://github.com/zhblue/hustoj/blob/master/trunk/core/sim/sim_3_01/README
HUSTOJ is composed of many "opensource" parts, which are using diverse licenses , you should use them on your own responsibilities.

**Comment by small-sunshines** [comment]
[Here](https://opensource.stackexchange.com/questions/8303/i-want-to-rewrite-the-gpl-2-software-with-agpl-3-0), it is possible to apply AGPLv3 for GPLv2 or later licenses.

**Comment by zhblue** [comment]
Glade to know that, Good Luck!
More issues are welcomed if you have any question on judge_client.cc.
