### ISSUE TITLE
安全系统重大漏洞？

### ISSUE THREAD

**Issue by cms42** [zhblue/hustoj#429]
RT，在commit/39dc281690994e620e85c8ed02e27b69610a6876（当前最新版）部署上进行测试时，这一份代码尝试调用bash但未被判RE:
```c++
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
 
int main(){
    char *argv[ ]={"bash", "-c", "echo test > abckhack.out", NULL};   
    char *envp[ ]={NULL};
    int t;
    t=syscall(SYS_execve,"/bin/bash",argv,envp);
    printf("ERROR WITH %d\n",t);
}
/**************************************************************
    Problem: 1002
    User: cms42_test
    Language: C
    Result: 答案错误
****************************************************************/
```
请重点关注@zhblue

**Comment by YYQHoro** [comment]
查看Diff答案对比 ERROR WITH -1，可以发现这里的echo返回值是-1，不是成功执行的0。对系统应该是无害的

**Comment by zhblue** [comment]
fixed on leatest commits 
try update and retest

**Comment by zhblue** [comment]
@cms42 Thank you for reporting and help.

**Comment by cms42** [comment]
It's my pleasure.

**Comment by cms42** [comment]
It seems to have been fixed
![img](https://user-images.githubusercontent.com/44895820/58745177-15ec5180-8480-11e9-91fb-141f6608829d.PNG)

**Comment by cms42** [comment]
我很遗憾地通知大家，这个漏洞仿佛死灰复燃了！

**Comment by cms42** [comment]
```Pascal
Program Example7;

{ Program to demonstrate the Execve function. }

Uses BaseUnix, strings;

Const Arg0 : PChar = '/bin/bash';
      Arg1 : Pchar = '-c';
      Arg2 : Pchar = 'echo Hacked';

Var PP : PPchar;


begin
  GetMem (PP,3*SizeOf(Pchar));
  PP[0]:=Arg0;
  PP[1]:=Arg1;
  PP[2]:=Arg2;
  PP[3]:=Nil;
  { Execute '/bin/bash -c echo Hacked', with current environment }
  { Envp is defined in system.inc }
  fpExecVe ('/bin/bash',pp,envp);
end.
```

**Comment by cms42** [comment]
问题大概是这样的：一日俺翻着okcalls32.h，忽然心血来潮，看看这个execve漏洞有没有被修复：

![okcalls32.h](https://i.jpg.dog/img/aa5371fb69d7352df7c71c1580448338.png)

结果我惊讶地发现，Pascal语言居然允许SYS_execve！

百度一下，Pascal还凑巧把Unix下的SYS_execve封装成了fpexecve()！

![Pascal文档](https://i.jpg.dog/img/7451bb073c3edee42e043e710a70336d.png)

遂抄一篇Example，略加改动提交到hustoj.com，居然没有RE？！

（好吧，我承认命令大概也是没有成功执行的）

**Comment by cms42** [comment]
俺略微查了一点资料，仿佛Java也可以调用execve？干脆全删了得了。

以及，最根本的解决方案，要不给所有实例默认开docker？

**Comment by zhblue** [comment]
是仅能调用一次，否则无法启动虚拟机

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/blob/master/trunk/core/judge_client/judge_client.cc#L385
除aarch64需特殊处理外，其他均覆盖为1

**Comment by cms42** [comment]
哦 好吧
