### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by jizhuozhi** [zhblue/hustoj#435]
出于私有云（k8s）的限制，我们要将hustoj构建成docker镜像才能部署，但是看了一下目前的dockerfile是基于debian构建的，在issues上发现存在若干未知的错误。我可以用ubuntu18.04重新构建并提交PR吗？

**Comment by zhblue** [comment]
建议PR另开一个子目录，将Ubuntu18.04版本的docker相关内容放置其中，并持续更新维护。

**Comment by jizhuozhi** [comment]
好的

**Comment by jizhuozhi** [comment]
构建好的镜像已经推送到`dockerHub`，运行方式
```shell
mkdir ~/volume
docker run -d           \
    --name hustoj       \
    -p 8080:80          \
    -p 2222:22          \
    -v ~/volume:/volume \
    mgdream/hustoj
```

**Comment by jizhuozhi** [comment]
Docker构建时可否’前端-服务器-判题机‘分别构建，以方便水平扩展web负载能力与判题机的分布式判题能力？

**Comment by zhblue** [comment]
这是个好主意，也是docker应该的用法，等你PR

**Comment by jizhuozhi** [comment]
web模块中是否存在代码对web外的模块有高耦合依赖？（譬如使用绝对路径引用/home/judge）

**Comment by jizhuozhi** [comment]
对于判题机的分离后的数据同步问题，我认为`Flyweight(享元)模式`是比较好的解决方案。
如果是单机运行多节点的话，可以多判题机容器共享同一个卷。
对于集群多节点，可能需要服务器运维人员手动搭建nfs共享卷来完成数据同步。

**Comment by zhblue** [comment]
HTTP judge 模式，判题机会自动按需下载测试数据，适合于分布式判题。

**Comment by zhblue** [comment]
也可以使用rsync+crontab自动同步数据
