### ISSUE TITLE
请问是否可以将评测端和web端分离部署

### ISSUE THREAD

**Issue by eventlOwOp** [zhblue/hustoj#449]
请问是否可以将评测端和web端分离部署,比如web用虚拟主机,评测用一些云容器完成
然后请问[judge.conf](https://github.com/zhblue/hustoj/blob/master/trunk/install/judge.conf)
中的OJ_HTTP_JUDGE是什么,请问可以通过http获取代码来评测吗

**Comment by bossbaby2005** [comment]
谢谢

**Comment by zhblue** [comment]
是的，可以，没错。
