### ISSUE TITLE
配色/颜色更改

### ISSUE THREAD

**Issue by BurnoutAg7** [zhblue/hustoj#452]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BlahDuckling747** [comment]
哦对不起，第一次提交issue把模板上传了
@zhblue 可不可以添加在管理员界面更改配色的功能，每次到后台挺麻烦的
如果不方便就算了，反正我也挺蒻的

**Comment by zhblue** [comment]
我倾向于让各位把全部源码文件当配置文件看，哪里不爽改哪里。

**Comment by BlahDuckling747** [comment]
好吧，其实我现在就是sweet/bing.css然后小改改:D

**Comment by zhblue** [comment]
你可以改到自己喜欢，然后把sweet名字改成sweet2，给个PR
