### ISSUE TITLE
出题人有误 / 永久编译中

### ISSUE THREAD

**Issue by BlahDuckling747** [zhblue/hustoj#453]
**出题人有误：**
a出了一道题目，后来这道题目被删掉了，然后b又出了一道题目，这两道题目编号相同，此时b出的题目显示出题人是a
_目前没有方法解决_

**永久编译中：**
a出了一道题目，有人提交了，然后删了这道题，如果重判这道题，提交记录显示永久编译中
_目前解决办法是出一道新题目再重判_

**Comment by zhblue** [comment]
推荐就是这样解决，感谢出题人背锅

**Comment by zhblue** [comment]
try https://github.com/zhblue/hustoj/commit/b9f24e054f091682bfad569f2b4a156eddb3c4d2

**Comment by BlahDuckling747** [comment]
感谢
