### ISSUE TITLE
附加代码问题

### ISSUE THREAD

**Issue by Yusnows** [zhblue/hustoj#465]
写了多个语言template，但是在切换语言的时候并不会把代码模板一起更换。
而且只有以.c为拓展名的template才会加载。

所用系统： Ubuntu16.04，Linux 4.15.0-60-generic
PHP 7.0.33-0ubuntu0.16.04.6 (cli) ( NTS )

**Comment by Yusnows** [comment]
附加一句，我已经确认过了文件拓展名是const_ini.php里面的了

**Comment by zhblue** [comment]
建议打开F12看一下，可能脚本出错了

**Comment by Yusnows** [comment]
> 建议打开F12看一下，可能脚本出错了

你好，因为前段时间比较忙，没来得及处理这个问题。现在我已经解决了。

主要问题是文件权限的问题，好像只有www-data use具有读写权限还不够，我把权限给到 other 都具有读写权限，就解决了,包括append代码文件也是如此。虽然不知道这个是否不具有普遍性，还是只是在我的电脑表现如此。

**Comment by zhblue** [comment]
可以检查下你的php进程是什么用户
