### ISSUE TITLE
登录时无法正确获取登录IP

### ISSUE THREAD

**Issue by mjiuming** [zhblue/hustoj#466]
使用反向代理服务器时（如通过HTTP网关对外提供访问入口），登录后得到的IP地址是HTTP网关的IP地址，而不是登录用户的IP地址
（ISSUE模板填的真烦人……）

**Comment by zhblue** [comment]
具体原因可能与反代的设置有关，请参考修改反代配置文件或如下源码：
https://github.com/zhblue/hustoj/blob/master/trunk/web/include/login-hustoj.php#L16
其中的HTTP_X_FORWARDED_FOR是需要在反代配置过的。
参考
https://blog.csdn.net/hellolingyun/article/details/34093223

**Comment by mjiuming** [comment]
真实发生的场景是：HTTP协议中与反向代理服务器相关的头部是有两个的：X-Forwarded-For/X-Real-IP，其中X-Real-IP是有值的，而X-Forwarded-For只有一个空格

**Comment by zhblue** [comment]
那您应该可以修改源码解决该问题，希望成功后提交一个PR

**Comment by mjiuming** [comment]
已修复
