### ISSUE TITLE
关于在提交界面是否允许测试运行的问题

### ISSUE THREAD

**Issue by ClearTrifles** [zhblue/hustoj#468]
我在db_info.inc.php文件中将``static  $OJ_TEST_RUN=true; ``但是在点击测试运行时，在测试运行下方会多一堆代码，除了修改这个文件之外还需要修改其他文件嘛？

**Comment by Yusnows** [comment]
我也遇到这个问题，而且在用户为管理员的时候，下方不会出现多余的代码，而用户为普通用户的时候会出现。

并且现在我启用了append代码功能后，admin用户测试运行也不成功了，但是也没有出现多余的代码就是一直在如图所示界面转圈
![Selection_070](https://user-images.githubusercontent.com/25427848/65112297-bf485a80-da11-11e9-81f5-a2e313173a15.jpg)
运行`ps aux | grep judge`得到以下输出
![Selection_072](https://user-images.githubusercontent.com/25427848/65112453-4b5a8200-da12-11e9-9009-29c5655547c1.jpg)

而在普通用户的情况下，点击测试运行就会出现
![Selection_073](https://user-images.githubusercontent.com/25427848/65112561-a5f3de00-da12-11e9-9b5e-3fc4ab945bfe.jpg)
![Selection_074](https://user-images.githubusercontent.com/25427848/65112568-ae4c1900-da12-11e9-8761-035c90f28939.jpg)

**Comment by zhblue** [comment]
1、检查db_info.inc.php中第一行的display_error是否Off
2、确认题目本身是开放可用的

**Comment by ClearTrifles** [comment]
> 
> 
> 我也遇到这个问题，而且在用户为管理员的时候，下方不会出现多余的代码，而用户为普通用户的时候会出现。
> 
> 并且现在我启用了append代码功能后，admin用户测试运行也不成功了，但是也没有出现多余的代码就是一直在如图所示界面转圈
> ![Selection_070](https://user-images.githubusercontent.com/25427848/65112297-bf485a80-da11-11e9-81f5-a2e313173a15.jpg)
> 运行`ps aux | grep judge`得到以下输出
> ![Selection_072](https://user-images.githubusercontent.com/25427848/65112453-4b5a8200-da12-11e9-9009-29c5655547c1.jpg)
> 
> 而在普通用户的情况下，点击测试运行就会出现
> ![Selection_073](https://user-images.githubusercontent.com/25427848/65112561-a5f3de00-da12-11e9-9b5e-3fc4ab945bfe.jpg)
> ![Selection_074](https://user-images.githubusercontent.com/25427848/65112568-ae4c1900-da12-11e9-8761-035c90f28939.jpg)

你解决这个问题了么？

**Comment by zhblue** [comment]
刚测试了一下，当题目没有启用或用于私有比赛时会出现这个现象。
请用开放练习的题目做测试。

**Comment by ClearTrifles** [comment]
> 
> 
> 刚测试了一下，当题目没有启用或用于私有比赛时会出现这个现象。
> 请用开放练习的题目做测试。

好的，老师，我刚才测试用管理员和非管理员都正常，google和火狐都可以，应该是没问题了。
