### ISSUE TITLE
sweet 皮肤不能注册用户

### ISSUE THREAD

**Issue by imcloudfloating** [zhblue/hustoj#483]
使用 sweet 皮肤，注册时跳转到 /register.php 是空白的，用户列表也没有新注册的用户。

**Comment by zhblue** [comment]
请先更新到最新版，并确认开启了注册功能。

**Comment by imcloudfloating** [comment]
注册功能是开启的，已经更新，其它皮肤都可以注册，只有 sweet 皮肤在跳转后是一个空白页面。

**Comment by zhblue** [comment]
已修复，请再次更新
