### ISSUE TITLE
使用python提交代码发生沙箱逃逸漏洞

### ISSUE THREAD

**Issue by taoting1234** [zhblue/hustoj#491]
![image](https://user-images.githubusercontent.com/19506467/66726449-00465a00-ee6c-11e9-8c52-14267c714b6b.png)
![image](https://user-images.githubusercontent.com/19506467/66726452-04727780-ee6c-11e9-9386-cb1612bd5302.png)
![image](https://user-images.githubusercontent.com/19506467/66726456-076d6800-ee6c-11e9-8d83-785fa5b7e997.png)

**Comment by zhblue** [comment]
这是一个chroot环境，里面的/etc/passwd是特意放的，否则Python会拒绝运行。

**Comment by taoting1234** [comment]
好的 谢谢张老师
