### ISSUE TITLE
非管理员无法在竞赛中测试运行

### ISSUE THREAD

**Issue by likole** [zhblue/hustoj#494]
非管理员在竞赛中测试运行，ajax结果会返回一个网页（提示Problem disabled），从而导致页面错乱。
![QQ图片20191017000306](https://user-images.githubusercontent.com/24356441/66937147-88498100-f071-11e9-99c4-464843a01162.jpg)
应该是submit.php中77行的判断导致的。$cid小于0，从而$res[0][1]为NULL。

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/commit/3fa1c1b77a01b9257ff4567f16be6520ef9a7d3f
时间仓促，请测试。
