### ISSUE TITLE
比赛账户能不能后台修改密码或删除

### ISSUE THREAD

**Issue by ULTRAMANSE** [zhblue/hustoj#496]
比赛用的账户能在oj后台进行修改删除吗

**Comment by zhblue** [comment]
可以再次用相同前缀生成，密码即重新覆盖。
不能删除，否则易产生教学事故

**Comment by ULTRAMANSE** [comment]
> 可以再次用相同前缀生成，密码即重新覆盖。
> 不能删除，否则易产生教学事故

好的，谢谢帮助
