### ISSUE TITLE
HUSTOJ在赛制下的缺陷

### ISSUE THREAD

**Issue by HibarigaokaRuri** [zhblue/hustoj#500]
1.在OI模式下 学生仍可以通过排名，个人信息，我的提交来查看当前代码是否通过。希望能在OI赛制下禁用这些网页。
2.可以在OI模式下暂时关闭discuss，站内信功能么
3.在OI模式下 竞赛列表内题目的状态里，可以看到当前题目的通过率，以及通过的用户，能在OI模式下禁用这些么。
麻烦作者了 由于本人对于PHP语言不太熟悉，无法自行修改进行Pr，麻烦您了。

**Comment by HibarigaokaRuri** [comment]
4.在OI赛制下，比赛时的提交记录仍会出现在状态里，我记得上次好像修过了，但是还是有一部分会出现在状态里，不知道是不是我的分布式评测才造成这个问题。

**Comment by zhblue** [comment]
1参考（考试）模式和（现场）赛模式。
发送括号里的词到微信公众号hustoj。

2 db_info.inc.php里有独立的内邮和论坛开关，设为false是关闭

3 建议截图标注说明，方便测试确认

4 更新时需同步更新全部Web服务器和判题机

**Comment by zhblue** [comment]
近期更新有修补上述问题，需在比赛标题中加入关键词“noip”，即可触发noip模式
