### ISSUE TITLE
请问是否可以把老版本的“未登录提交时提示登录”的功能加回来？

### ISSUE THREAD

**Issue by qczone** [zhblue/hustoj#502]
现在的版本关闭访客模式后，每次访问就得登录，有时候并不是做题，这样就会很麻烦，在没有关闭访客模式的情况下，一个账号登录之后时间久了，没注意的话再提交就成了guest，而且变成guest登录时可以查看guest以前的提交。能否把老版本的功能加回来，就是提交题目时提示登录，我觉得那样挺好的，既不影响OJ的访问，又不影响提交。

**Comment by zhblue** [comment]
那么请关闭访客和强制登陆

https://github.com/zhblue/hustoj/blob/master/trunk/web/include/db_info.inc.php#L52
