### ISSUE TITLE
如何将编译器的首选语言由C改为C++，直接在const.in.php中language_name直接交换两者位置后，没有用

### ISSUE THREAD

**Issue by KevinHuWho** [zhblue/hustoj#509]
如何将编译器的首选语言由C改为C++，直接在const.in.php中language_name直接交换两者位置后，没有用

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/blob/master/trunk/web/submitpage.php#L97
$lastlang=1;

**Comment by KevinHuWho** [comment]
非常感谢！
