### ISSUE TITLE
要怎麼解決一直pending

### ISSUE THREAD

**Issue by tico88612** [zhblue/hustoj#51]
我題目設定完成了
可是要怎麼解決 一直pending 的問題
我有甚麼沒設定好的嗎??

**Comment by zhblue** [comment]
检查/home/judge/etc/judge.conf的数据库设定
如没有错误运行sudo judged
如果运行后修复，在rc.local加入/usr/bin/judged

**Comment by rugiabaku** [comment]
sudo: judged: command not found
加入/usr/bin/judged 是加在哪?

**Comment by zhblue** [comment]
请在源码core目录下运行sudo ./make.sh
如果编译正常，将会产生/usr/bin/judged以及/usr/bin/judge_client这两个文件
rc.local的位置通常是/etc/rc.local 
功能类似windows的启动菜单，放在里面的命令会在启动时自动运行。

**Comment by rugiabaku** [comment]
root@ubuntu:/hustoj/hustoj-read-only/core# ls -l
total 16
drwxr-xr-x 2 root root 4096 Jun  9 09:15 judge_client
drwxr-xr-x 2 root root 4096 May 22 08:27 judged
-rwxr-xr-x 1 root root  487 May 22 08:27 make.sh
drwxr-xr-x 3 root root 4096 May 22 08:27 sim

root@ubuntu:/hustoj/hustoj-read-only/core# sh ./make.sh
./make.sh: 3: ./make.sh: make: not found
chmod: cannot access 'judged': No such file or directory
cp: cannot stat 'judged': No such file or directory
./make.sh: 7: ./make.sh: make: not found
chmod: cannot access 'judge_client': No such file or directory
cp: cannot stat 'judge_client': No such file or directory
./make.sh: 11: ./make.sh: make: not found
./make.sh: 12: ./make.sh: make: not found
cp: cannot stat 'sim_c.exe': No such file or directory
cp: cannot stat 'sim_java.exe': No such file or directory
cp: cannot stat 'sim_pasc.exe': No such file or directory
cp: cannot stat 'sim_text.exe': No such file or directory
cp: cannot stat 'sim_lisp.exe': No such file or directory
rm: cannot remove '/usr/bin/sim_rb': No such file or directory
rm: cannot remove '/usr/bin/sim_sh': No such file or directory
root@ubuntu:/hustoj/hustoj-read-only/core#

**Comment by rugiabaku** [comment]
root@ubuntu:/hustoj/hustoj-read-only/core# ls -l
total 16
drwxrwxrwx 2 root root 4096 Jun  9 09:15 judge_client
drwxrwxrwx 2 root root 4096 May 22 08:27 judged
-rwxr-xr-x 1 root root  487 May 22 08:27 make.sh
drwxr-xr-x 3 root root 4096 May 22 08:27 sim

root@ubuntu:/hustoj/hustoj-read-only/core# sudo ./make.sh
./make.sh: line 3: make: command not found
chmod: cannot access 'judged': No such file or directory
cp: cannot stat 'judged': No such file or directory
./make.sh: line 7: make: command not found
chmod: cannot access 'judge_client': No such file or directory
cp: cannot stat 'judge_client': No such file or directory
./make.sh: line 11: make: command not found
./make.sh: line 12: make: command not found
cp: cannot stat 'sim_c.exe': No such file or directory
cp: cannot stat 'sim_java.exe': No such file or directory
cp: cannot stat 'sim_pasc.exe': No such file or directory
cp: cannot stat 'sim_text.exe': No such file or directory
cp: cannot stat 'sim_lisp.exe': No such file or directory
rm: cannot remove '/usr/bin/sim_rb': No such file or directory
rm: cannot remove '/usr/bin/sim_sh': No such file or directory
root@ubuntu:/hustoj/hustoj-read-only/core#

**Comment by zhblue** [comment]
有很多依赖没装，建议看一下install目录下的安装脚本内容
ubuntu 14.04 需先运行下面的软件安装命令
apt-get install -y make flex g++ clang libmysqlclient-dev libmysql++-dev fp-compiler openjdk-7-jdk
ubuntu 16.04 需先运行下面的软件安装命令
apt-get install -y make flex g++ clang libmysqlclient-dev libmysql++-dev fp-compiler openjdk-8-jdk 
其他发行版请自行用对应的软件包管理器查找对应的软件包名称

**Comment by rugiabaku** [comment]
我是跟你主頁
ubuntu16.04，可以使用下面脚本
wget https://raw.githubusercontent.com/zhblue/hustoj/php7/trunk/install/install-ubuntu16.04.sh
chmod +x install-ubuntu16.04.sh
sudo ./install-ubuntu16.04.sh

**Comment by zhblue** [comment]
请检查你的软件源和网络连接，正常情况该脚本应该会完成所有依赖的安装。
sudo apt-get update 
看一下是否有报错

**Comment by rugiabaku** [comment]
root@ubuntu:~# cat /etc/issue
Ubuntu 16.04.2 LTS \n \l

root@ubuntu:~# sudo apt-get update
Hit:1 http://hk.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://hk.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://hk.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:5 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease
Fetched 102 kB in 10s (9,690 B/s)
Reading package lists... Done

**Comment by rugiabaku** [comment]
現在run完 sudo judged 之後
已經沒pending了, 但一直在Compiling ....

**Comment by zhblue** [comment]
重启一下sudo reboot

**Comment by rugiabaku** [comment]
重開完變404 Not Found.......

**Comment by zhblue** [comment]
请描述一下你ubuntu安装完成后做过哪些操作。
最好在一个全新的系统上运行安装脚本。

**Comment by rugiabaku** [comment]
我整部server重裝了
裝好ubuntu 16.04後執行了下面這些

sudo apt-get update  
sudo apt-get install subversion  
sudo svn co https://github.com/zhblue/hustoj/branches/php7/trunk/install hustoj 
cd hustoj  
sudo bash install-interactive.sh 
sudo judged
在rc.local加入/usr/bin/judged
judge.conf 跟 db_info.inc.php 都檢查過了
還有把舊資料的sql灌進去mysql (沒有Error)
然後reboot

還是卡在Compiling

**Comment by zhblue** [comment]
你检查的judge.conf 是/home/judge/etc/judge.conf这个么？
其中OJ_SHM_RUN设置是什么？

**Comment by rugiabaku** [comment]
沒有改過
OJ_SHM_RUN=0

**Comment by zhblue** [comment]
沒有改過是什么意思，你检查了
/home/judge/etc/judge.conf 里面的数据库帐号密码是否正确么？

**Comment by rugiabaku** [comment]
都檢查過很多次了

**Comment by zhblue** [comment]
后台更新一下数据库
sudo pkill -9 judged
sudo judged

**Comment by zhblue** [comment]
首页上的两种版本的安装脚本近期都做过测试，应该都可以用

Ubuntu14.04快速安装指南：

wget https://raw.githubusercontent.com/zhblue/hustoj/master/trunk/install/install-ubuntu14.04.sh
chmod +x install-ubuntu14.04.sh
sudo ./install-ubuntu14.04.sh

ubuntu16.04，可以使用下面脚本

wget https://raw.githubusercontent.com/zhblue/hustoj/php7/trunk/install/install-ubuntu16.04.sh
chmod +x install-ubuntu16.04.sh
sudo ./install-ubuntu16.04.sh

**Comment by rugiabaku** [comment]
sudo pkill -9 judged
sudo judged
run完了, 不行

**Comment by zhblue** [comment]
完了以后你重判题目了么？
检查下/home/judge/data/1000/目录下*.in *.out文件是否成对出现。

**Comment by rugiabaku** [comment]
重判了, 全部都在compiling
in out 文件都齊全

**Comment by zhblue** [comment]
提交的语言是什么，是否安装了相应的编译器？
是否有公网地址可以访问？

**Comment by rugiabaku** [comment]
用的是Pascal
沒裝過编译器, 要裝嗎?
這是內聯網用, 沒有接出互聯網

**Comment by zhblue** [comment]
需要安装
sudo apt-get install fp-compiler
或者
sudo apt-get install fpc

**Comment by rugiabaku** [comment]
兩句都執行了, 沒error
還是compiling....

**Comment by rugiabaku** [comment]
這樣一直轉圈

![default](https://user-images.githubusercontent.com/29416078/27126361-c02dc3ae-5129-11e7-9856-7671d95f4f26.png)

**Comment by zhblue** [comment]
sudo judge_client 1002 0 /home/judge debug P
把输出粘出来看看

**Comment by rugiabaku** [comment]
root@ubuntu:~# sudo judge_client 1002 0 /home/judge debug P
127.0.0.1
root
**********密碼過濾一下
judgeonline
3306
2
64
-Xms64M
-Xmx128M
0
0
http://127.0.0.1/JudgeOnline
admin
**********密碼過濾一下
0
0
1
umount: /home/judge/run0//proc: mountpoint not found
umount: /home/judge/run0//dev: mountpoint not found
umount: /home/judge/run0//lib: mountpoint not found
umount: /home/judge/run0//lib64: mountpoint not found
umount: /home/judge/run0//etc/alternatives: mountpoint not found
umount: /home/judge/run0//usr: mountpoint not found
umount: /home/judge/run0//bin: mountpoint not found
umount: /home/judge/run0//proc: mountpoint not found
umount: bin: mountpoint not found
umount: usr: mountpoint not found
umount: lib: mountpoint not found
umount: lib64: mountpoint not found
umount: etc/alternatives: mountpoint not found
umount: /proc: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
umount: dev: mountpoint not found
umount: /home/judge/run0//log: not mounted
umount: /home/judge/run0//log/*: mountpoint not found
umount: /home/judge/run0//log/etc/alternatives: mountpoint not found
mkdir: cannot create directory â€˜/home/judge/run0//log/â€™: File exists
/bin/mv: cannot move '/home/judge/run0//log' to a subdirectory of itself, '/home             /judge/run0//log/log'
Main=Main.pastime: 1 mem: 64
/usr/bin/ld.bfd: warning: link.res contains output sections; did you forget -T?
status=0
umount: dev: not mounted
umount: /home/judge/run0//Main: not mounted
umount: /home/judge/run0//Main.o: not mounted
umount: /home/judge/run0//Main.pas: not mounted
umount: /home/judge/run0//bin: not mounted
umount: /home/judge/run0//ce.txt: not mounted
umount: /home/judge/run0//dev: not mounted
umount: /home/judge/run0//etc: not mounted
umount: /home/judge/run0//lib: not mounted
umount: /home/judge/run0//lib64: not mounted
umount: /home/judge/run0//log: not mounted
umount: /home/judge/run0//proc: not mounted
umount: /home/judge/run0//tmp: not mounted
umount: /home/judge/run0//usr: not mounted
umount: /home/judge/run0//proc: not mounted
umount: /home/judge/run0//dev: not mounted
umount: /home/judge/run0//lib: not mounted
umount: /home/judge/run0//lib64: not mounted
umount: /home/judge/run0//etc/alternatives: not mounted
umount: /home/judge/run0//usr: not mounted
umount: /home/judge/run0//bin: not mounted
umount: /home/judge/run0//proc: not mounted
umount: bin: not mounted
umount: usr: not mounted
umount: lib: not mounted
umount: lib64: not mounted
umount: etc/alternatives: not mounted
umount: /proc: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
umount: dev: not mounted
umount: /home/judge/run0//Main: not mounted
umount: /home/judge/run0//Main.o: not mounted
umount: /home/judge/run0//Main.pas: not mounted
umount: /home/judge/run0//bin: not mounted
umount: /home/judge/run0//ce.txt: not mounted
umount: /home/judge/run0//dev: not mounted
umount: /home/judge/run0//etc: not mounted
umount: /home/judge/run0//lib: not mounted
umount: /home/judge/run0//lib64: not mounted
umount: /home/judge/run0//log: not mounted
umount: /home/judge/run0//proc: not mounted
umount: /home/judge/run0//tmp: not mounted
umount: /home/judge/run0//usr: not mounted
umount: /home/judge/run0//log/*: mountpoint not found
umount: /home/judge/run0//log/etc/alternatives: mountpoint not found
umount: /home/judge/run0//proc: not mounted
umount: /home/judge/run0//dev: not mounted
umount: /home/judge/run0//lib: not mounted
umount: /home/judge/run0//lib64: not mounted
umount: /home/judge/run0//etc/alternatives: not mounted
umount: /home/judge/run0//usr: not mounted
umount: /home/judge/run0//bin: not mounted
umount: /home/judge/run0//proc: not mounted
umount: bin: not mounted
umount: usr: not mounted
umount: lib: not mounted
umount: lib64: not mounted
umount: etc/alternatives: not mounted
umount: /proc: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
umount: dev: not mounted
umount: /home/judge/run0//Main: not mounted
umount: /home/judge/run0//Main.o: not mounted
umount: /home/judge/run0//Main.pas: not mounted
umount: /home/judge/run0//bin: not mounted
umount: /home/judge/run0//ce.txt: not mounted
umount: /home/judge/run0//dev: not mounted
umount: /home/judge/run0//etc: not mounted
umount: /home/judge/run0//lib: not mounted
umount: /home/judge/run0//lib64: not mounted
umount: /home/judge/run0//log: not mounted
umount: /home/judge/run0//proc: not mounted
umount: /home/judge/run0//tmp: not mounted
umount: /home/judge/run0//usr: not mounted
umount: /home/judge/run0//log/*: mountpoint not found
umount: /home/judge/run0//log/etc/alternatives: mountpoint not found
/bin/cp: cannot stat '/home/judge/data/1000/*.dic': No such file or directory
init_call_counter:2
pid=157140 judging /home/judge/data/1000/data2.in
/bin/grep: Main.py: No such file or directory
/bin/cp: cannot stat '/home/judge/data/1000/*.dic': No such file or directory
init_call_counter:2
pid=157147 judging /home/judge/data/1000/data1.in
/bin/grep: Main.py: No such file or directory
/bin/cp: cannot stat '/home/judge/data/1000/*.dic': No such file or directory
init_call_counter:2
pid=157154 judging /home/judge/data/1000/data3.in
/bin/grep: Main.py: No such file or directory
fail test /home/judge/data/1000/data3.in
add diff info of 1002.....
umount: /home/judge/run0//proc: not mounted
umount: /home/judge/run0//dev: not mounted
umount: /home/judge/run0//lib: not mounted
umount: /home/judge/run0//lib64: not mounted
umount: /home/judge/run0//etc/alternatives: not mounted
umount: /home/judge/run0//usr: not mounted
umount: /home/judge/run0//bin: not mounted
umount: /home/judge/run0//proc: not mounted
umount: bin: not mounted
umount: usr: not mounted
umount: lib: not mounted
umount: lib64: not mounted
umount: etc/alternatives: not mounted
umount: /proc: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
umount: dev: not mounted
umount: /home/judge/run0//Main: not mounted
umount: /home/judge/run0//Main.o: not mounted
umount: /home/judge/run0//Main.pas: not mounted
umount: /home/judge/run0//bin: not mounted
umount: /home/judge/run0//ce.txt: not mounted
umount: /home/judge/run0//data.in: not mounted
umount: /home/judge/run0//dev: not mounted
umount: /home/judge/run0//diff.out: not mounted
umount: /home/judge/run0//error.out: not mounted
umount: /home/judge/run0//etc: not mounted
umount: /home/judge/run0//lib: not mounted
umount: /home/judge/run0//lib64: not mounted
umount: /home/judge/run0//log: not mounted
umount: /home/judge/run0//proc: not mounted
umount: /home/judge/run0//tmp: not mounted
umount: /home/judge/run0//user.out: not mounted
umount: /home/judge/run0//usr: not mounted
umount: /home/judge/run0//log/*: mountpoint not found
umount: /home/judge/run0//log/etc/alternatives: mountpoint not found
mkdir: cannot create directory â€˜/home/judge/run0//log/â€™: File exists
/bin/mv: cannot move '/home/judge/run0//log' to a subdirectory of itself, '/home             /judge/run0//log/log'
result=6
int LANG_PV[256]={0,1,13,16,59,89,97,231,0};
int LANG_PC[256]={HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,HOJ_MA             X_LIMIT,HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,HOJ_MAX_LIMIT,0};
root@ubuntu:~#

**Comment by zhblue** [comment]
试试增加这一行最后的数字，比如200改为400或800，然后重新运行sudo ./make.sh这个操作。
https://github.com/zhblue/hustoj/blob/master/trunk/core/judged/judged.cc#L216

**Comment by rugiabaku** [comment]
这一行 是 哪一行?

**Comment by zhblue** [comment]
L216 = Line 216

**Comment by rugiabaku** [comment]
做好了, 都是一樣

**Comment by zhblue** [comment]
如果你有使用QQ可以联系我10982766
或者安装TeamViewer，然后发送机器序列号和密码到我的邮箱10982766@qq.com
然后我通过你在Windows的机器putty/ssh登录到服务器上帮你看看。

**Comment by rugiabaku** [comment]
剛發了, 謝謝

**Comment by zhblue** [comment]
结果是数据库结构太老，无法使用自动更新脚本更新，手工修订后正常了，写下来以备将来有人遇到类似问题。

**Comment by rugiabaku** [comment]
是呀....之前裝在Windows Server 2000, Mysql 4.0
我也已經人手改過結構的了
所以你見我沒用預設那個 jol , 另開一個judgeonline 然後參考jol結構已經修改了不少

**Comment by zhblue** [comment]
这么说原来的系统并不是hustoj，那现在居然能跑起来已经是奇迹了。

**Comment by rugiabaku** [comment]
之前是POJ免費版
我有參考你這一篇
https://github.com/zhblue/hustoj/blob/master/wiki/POJ2HUSTOJ.md

**Comment by zhblue** [comment]
这个已经有很多年了，欢迎使用HUSTOJ。
