### ISSUE TITLE
CSRF验证有缺陷可以被绕过

### ISSUE THREAD

**Issue by dzj0821** [zhblue/hustoj#511]
https://github.com/zhblue/hustoj/blob/5aa7effc33685afc316e3e69229fcc99e90a930f/trunk/web/include/db_info.inc.php#L113-L115
条件：OJ_CSRF开启，且模板为bs3
这里判断basename($_SERVER['PHP_SELF'])!="problem_judge"，可以通过访问http://localhost/xxx.php/problem_judge 的方式绕过

**Comment by zhblue** [comment]
谢谢指正，请问有好的修改建议么？

**Comment by zhblue** [comment]
尝试修订，请确认

**Comment by dzj0821** [comment]
没懂basename($_SERVER['PHP_SELF'])!="problem_judge"这个判断是判断啥的 可以解释一下吗

**Comment by zhblue** [comment]
这个是给HTTP判题的服务端开后门，现在已经改成判断SESSION中的http_judge标记

**Comment by dzj0821** [comment]
好的没问题了

**Comment by zhblue** [comment]
谢谢！

**Comment by dzj0821** [comment]
https://github.com/zhblue/hustoj/commit/662379d3c2646ed09cd8c51ec005cc6286efe8a6
已修复此问题
