### ISSUE TITLE
大文件评测时间抖动问题

### ISSUE THREAD

**Issue by mjiuming** [zhblue/hustoj#512]
因为HUSTOJ的测试数据是存储在文件系统中的，大文件因为读写数据会导致ptrace拦截READ系统调用，进入内核态，之后记录时间的时候会因为ptrace的频繁上下文切换导致时间抖动。

在现场赛大文件的时候会有较大的评测时间偏差。

可以尝试使用seccomp白名单+ptrace拦截混合方式来减少时间抖动。

**Comment by mjiuming** [comment]
[seccomp](http://man7.org/linux/man-pages/man2/seccomp.2.html)

**Comment by zhblue** [comment]
ptrace可以手动关闭，在judge.conf中。
前提是用docker做判题容器隔离。

**Comment by zhblue** [comment]
另外物理机可以启用SHM_RUN选项，在评测前将数据加载到内存中。

**Comment by zhblue** [comment]
如果能提供基于seccomp的PR，我很乐意测试

**Comment by mjiuming** [comment]
好的，下班后我试一下
