### ISSUE TITLE
在deepin15.11安装问题

### ISSUE THREAD

**Issue by jvhuaxia** [zhblue/hustoj#523]
在deepin15.11桌面版上安装
wget https://github.com/zhblue/hustoj/raw/master/trunk/install/install-deepin15.9.sh
sudo bash install-deepin15.9.sh
遇到问题
_gcc -DUNIX -DSOLARIS -s token.o lex.o stream.o text.o tokenarray.o debug.o ForEachFile.o fname.o Malloc.o any_int.o idf.o runs.o percentages.o sim.o options.o newargs.o hash.o compare.o add_run.o pass1.o pass2.o pass3.o textlang.o -o sim_text.exe
done!
grep: /etc/rc.local: 没有那个文件或目录
sed：无法读取 /etc/rc.local：没有那个文件或目录
grep: /var/spool/cron/crontabs/root: 没有那个文件或目录
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
Remember your database account for HUST Online Judge:
username:hustoj
password:e..........

之后登录出现UserName or Password Wrong!
我看库里的表内容都是空的

可以请问一下这个是什么问题吗

**Comment by zhblue** [comment]
安装脚本最后提示的是数据库账号密码，而不是Web的账号密码，请用admin作为用户名，自行注册一个账号。

**Comment by jvhuaxia** [comment]
了解 没注意看文档 哈哈 没问题了 :-)
