### ISSUE TITLE
无root权限:mount:Permission denied

### ISSUE THREAD

**Issue by eventlOwOp** [zhblue/hustoj#524]
在腾讯开发者平台cloud studio运行评测端,显示编译错误mount:Permission denied
安装评测端后使用httpjudge
提交显示编译错误mount:Permission denied
估计是没有root权限导致的
请问可以不使用root权限评测程序吗
谢谢

**Comment by zhblue** [comment]
不行，没有root权限很多事情都做不了。
不过你可以修改源码，把相关的地方都去掉，就可以无权限运行了，多年以前有个MIT的同学这样做过，仅供娱乐不适合生产环境。
建议至少上个标准云服务(给root的)，实在不行阿里云轻量级也是可以的。
