### ISSUE TITLE
status.php对应界面只能显示管理员提交的问题的状态，其他用户的无法显示

### ISSUE THREAD

**Issue by BOBMASRER** [zhblue/hustoj#525]
开发者您好,
    在使用该程序时，首页面的状态栏即地址http://url/status.php 界面下的提交只能显示管理员的提交并不能显示用户的提交，请问需要如何更改才能使所有用户的提交都能显示在这个界面上?

**Comment by zhblue** [comment]
默认情况下，如果用户的提交属于某个比赛，则仅在该比赛的状态中显示。

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/blob/master/trunk/web/status.php#L72
去掉该行WHERE子句中的
```
(contest_id=0 or contest_id is null)  and
```
可以显示比赛中的提交，但是将失去关于NOIP模式的某些特性，不建议修改。

**Comment by BOBMASRER** [comment]
好的,谢谢解决了！
