### ISSUE TITLE
生成账号时，覆盖了之前比赛的账号。

### ISSUE THREAD

**Issue by Zeng1998** [zhblue/hustoj#530]
在后台生成账号时候，忘记修改前缀名，导致生成的账号和昵称覆盖了之前比赛的昵称。
建议这里可以添加一个判断和提醒的功能。

**Comment by zhblue** [comment]
允许被覆盖，以支持考试时仅允许密码使用一次

**Comment by Zeng1998** [comment]
> 允许被覆盖，以支持考试时仅允许密码使用一次

因为忘记导出榜单，所以上一年的校赛的队员姓名被覆盖了，有点遗憾。

**Comment by zhblue** [comment]
好吧，先加个红字去
