### ISSUE TITLE
请问是否可以在数据库直接维护竞赛与作业里面的“竞赛&作业-用户“这个内容？

### ISSUE THREAD

**Issue by KittenCN** [zhblue/hustoj#533]
请问是否可以在数据库直接维护竞赛与作业里面的“竞赛&作业-用户“这个内容？具体是哪张表的哪个字段？我找了一圈没找到。。
还有讨论版貌似不能翻页，不知道如何修复。

**Comment by zhblue** [comment]
privilege表
讨论版是半成品，如有需求可以另外装phpbb3
