### ISSUE TITLE
One faqs.xx.txt file for each language? Not several faqs.xx.php for all each templates... ?

### ISSUE THREAD

**Issue by melongist** [zhblue/hustoj#537]
**Is your feature request related to a problem? Please describe.**
There are 18 faqs.php... faqs.php, faqs.cn.php, faqs.ug.php, faqs.cn.php... and for each templates...
There are so many files and the contents will be different, so I can't easily modify the faqs.php code.

**Describe the solution you'd like**
- 1 faqs.xx.txt for each languages..  at /lang/  like cn.php, ko.php etc.
- Make faqs.php read /lang/faqs.xx.txt file..
- And enabling to modify the faqs.xx.txt  contents with admin menu.   just like setmsg.php with msg.txt.

with google translation~

文件太多，内容也会有所不同，因此我无法轻松地修改faqs.php代码。
如何将由模板分隔的faqs.php放入/ lang /目录中，并为每种语言仅合并一个faqs.xx.php文件？ 如果这样做，您似乎只能为每种语言提供一种常见问题解答翻译。 而且，如果您更进一步，那么可以从管理菜单中修改faqs.xx.php文件的内容。 我考虑过将其另存为faqs.xx.txt文件，然后将其加载到msg.txt之类的faqs.php文件中。

**Comment by zhblue** [comment]
great idea, I'll look into it, find a better solution , maybe FAQ l10n can work with news

**Comment by zhblue** [comment]
check this quick solution
https://github.com/zhblue/hustoj/commit/0fa29283ed75196c4b0242db17aa9b8f47ffa3ea
now FAQ page can be easily updated by administrator from the admin menu 
the admin of each site can customize their own contents based on recent activities and students' really "frequently asked questions"

**Comment by melongist** [comment]
> check this quick solution
> [0fa2928](https://github.com/zhblue/hustoj/commit/0fa29283ed75196c4b0242db17aa9b8f47ffa3ea)
> now FAQ page can be easily updated by administrator from the admin menu
> the admin of each site can customize their own contents based on recent activities and students' really "frequently asked questions"

**Comment by melongist** [comment]
Thanks to zhblue~ :)
