### ISSUE TITLE
What is the exact purpose of '/admin/user_set_ip.php ?

### ISSUE THREAD

**Issue by melongist** [zhblue/hustoj#560]
**描述问题**
- admin menu's  user_set_ip.php make a log to  jol 'loginlog' table...

- I understood the loginlog table's log ex.. "log in ok", "no save" ... 

- but I don't understand the purpose of the log...  "set ip by .... "...  by admin menu's user_set_ip.php ... ??

Thank you all ~ :)

**Comment by zhblue** [comment]
when enable "OJ_EXAM_CONTEST_ID" , the login can be limited to the recent used ip of each user.
set ip meant to allow  one student account by pass this setting to change a diffrent seat if their alloced computer is broken during the exam.

**Comment by zhblue** [comment]
related code:
https://github.com/zhblue/hustoj/blob/master/trunk/web/include/login-hustoj.php#L25

**Comment by melongist** [comment]
Thank you :)
