### ISSUE TITLE
Mario模板不能登陆

### ISSUE THREAD

**Issue by zhblue** [zhblue/hustoj#586]
**描述问题**
请说清安装方式、基础系统、物理机环境、操作过程，遇到的问题

**如何复现**
1. 设置模板为mario
2. 浏览首页，无登陆按钮
3. F12-Network
4. 看到报错'swProfile.php' 404

@MX-Qulin

**Comment by MX-Qulin** [comment]
fixing

**Comment by MX-Qulin** [comment]
我的可能有些不通用的设置...

**Comment by MX-Qulin** [comment]
但早上貌似可以登 我试过的~

**Comment by MX-Qulin** [comment]
忘记上传了🤦‍

**Comment by MX-Qulin** [comment]
@zhblue  这个Issue能关了吗?
