### ISSUE TITLE
ubuntu 升级之后

### ISSUE THREAD

**Issue by i8023eva** [zhblue/hustoj#612]
之前用 Ubuntu16，最近升级成 18 之后，出502 Bad Gateway；
之前 php 是 7.0，升级之后变成 7.2，看错误是 php7.0-fpm 找不到；
求助(๑•̀ㅂ•́)و✧

**Comment by renbaoshuo** [comment]
备份一下数据库和测试样例再重装一下试试？
~~这大概是最简单的方法了~~

**Comment by zhblue** [comment]
编辑/etc/nginx/sites-enabled/default
把里面的php7.0-fpm改为php7.2-fpm就好了

**Comment by zhblue** [comment]
改完重启nginx

**Comment by i8023eva** [comment]
Y(^o^)Y 好了，谢谢
