### ISSUE TITLE
请问是否可以限制用户注册？

### ISSUE THREAD

**Issue by niyunsheng** [zhblue/hustoj#624]
是否可以只由管理员来注册账号，自己不能注册

**Comment by zhblue** [comment]
可以，设置db_info.inc.php中的选项，
https://github.com/zhblue/hustoj/blob/master/trunk/web/include/db_info.inc.php#L51
static  $OJ_REGISTER=true; //允许注册新用户
static  $OJ_REG_NEED_CONFIRM=false; //新注册用户需要审核
关闭注册后，管理员可以在后台“比赛队账户生成器”，生成指定数量的账户用于分配。
http://xxxx.xxxxx/admin/team_generate.php

**Comment by niyunsheng** [comment]
直接在数据库操作是否可行？修改jol库的user表

**Comment by zhblue** [comment]
可以，只要你能看懂生成密码的部分php代码就行。

**Comment by niyunsheng** [comment]
我能不生成密码，然后用admin账户更新密码吗？

**Comment by zhblue** [comment]
也可以

**Comment by niyunsheng** [comment]
非常感谢！
