### ISSUE TITLE
请问如何去除首页背景的水印呢？

### ISSUE THREAD

**Issue by niyunsheng** [zhblue/hustoj#625]
我查看了index.php以及其include的一些php页面，但是没有找到水印的地方，请问在哪里可以修改或者删除水印呢？

**Comment by zhblue** [comment]
直接替换图片？

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/blob/master/trunk/web/image/background.jpg

**Comment by niyunsheng** [comment]
非常感谢，替换图片就可以了

**Comment by MX-Qulin** [comment]
这是个好问题
