### ISSUE TITLE
被连续提交爆站了

### ISSUE THREAD

**Issue by KittenCN** [zhblue/hustoj#649]
前提，已更新至最新，且已在后台打开验证码；
重现如下，写一段很费时的代码，进行提交，填写验证码后，用连点工具每秒100次点击提交，在页面反应过来以后，就有了将近1000次的提交等待判定。。。
除了修改提交的规则，不知道还有什么解决方法

**Comment by renbaoshuo** [comment]
限制**单IP**并发？

**Comment by KittenCN** [comment]
如何限制?

**Comment by renbaoshuo** [comment]
> 如何限制? OJ没有找到相关的设置

自行百度 `nginx 限制并发数`

**Comment by zhblue** [comment]
再更新一下submit.php，之前有个调试开关忘记去掉了

**Comment by MX-Qulin** [comment]
> 再更新一下submit.php，之前有个调试开关忘记去掉了

??????
老版有吗?

**Comment by MX-Qulin** [comment]
> 再更新一下submit.php，之前有个调试开关忘记去掉了

??????
老版有吗?
