### ISSUE TITLE
I think... cookie login service have some error...

### ISSUE THREAD

**Issue by melongist** [zhblue/hustoj#661]
**描述问题**
I think... cookie login service have some error...

**如何复现**

If I try to log in again after a while, the login is not working, 
if I click login but the ID and PW input page does not appear so I can not log in.

**Expected behavior**
I have to clear the browser's cache to login again...,
after clear cache, then I can see the ID/PW input page again.

**Screenshots**

**Desktop (please complete the following information):**
 - OS : Ubuntu 20.04LTS
 - Browser : firefox
 - Version : latest

**Comment by MX-Qulin** [comment]
let me see see

**Comment by MX-Qulin** [comment]
emm.. my cookie(on my dev computer) works. 
Could you show me your website so i can check it?

**Comment by MX-Qulin** [comment]
> 
> 
> **描述问题**
> I think... cookie login service have some error...
> 
> **如何复现**
> Steps to reproduce the behavior:
> 
> If I try to log in again after a while, the login is not working,
> if I click login but the ID and PW input page does not appear so I can not log in.
> 
> **Expected behavior**
> I have to clear the browser's cache to login again...,
> after clear cache, then I can see the ID/PW input page again.
> 
> **Screenshots**
> 
> **Desktop (please complete the following information):**
> 
>     * OS : Ubuntu 20.04LTS
> 
>     * Browser : firefox
> 
>     * Version : latest

Actaully, after a while(PHP session timeout) and you go to "login.php", you needn't enter anything and login will done by cookie. Then you'll be redirected to index.php

**Comment by MX-Qulin** [comment]
@melongist i've checked. Cookie login is now working very well.

The only problem is that after login successfully, it can't redirect to index.php

i'll fix this in a few moment.

**Comment by melongist** [comment]
> @melongist i've checked. Cookie login is now working very well.
> 
> The only problem is that after login successfully, it can't redirect to index.php
> 
> i'll fix this in a few moment.

Thank you 👍

**Comment by MX-Qulin** [comment]
@melongist how do you do with ```After a while```? i test it by delete ```PHPSESSION```.

**Comment by MX-Qulin** [comment]
ok. fixed.

i'll make a pull request. you can use the code by #662

**Comment by MX-Qulin** [comment]
please test and report bug. Thanks:)

@melongist

**Comment by melongist** [comment]
> please test and report bug. Thanks:)
> 
> @melongist

OK~ I will test it ~ ^-^;

**Comment by melongist** [comment]
I couldn't reproduce the same situation, so I didn't test it exactly, but thank you. ^^

**Comment by MX-Qulin** [comment]
well....

**Comment by MX-Qulin** [comment]
@zhblue  帮着测一下呗?
