### ISSUE TITLE
新版本无法判定Hello World! 题目

### ISSUE THREAD

**Issue by youyu** [zhblue/hustoj#671]
用了最新版的HustOJ，发现只有指定输出的“Hello World！” 的题目，随便提交都是对的。以前的版本可以的。改了题目好像是，没有输入项，就不管输出正确与否了。
不知道其他人有这种情况不？

**Comment by zhblue** [comment]
即使没有输入，也要有对应的.in文件，比如sample.in / sample.out
test.in / test.out

**Comment by zhblue** [comment]
推荐这类题目，在样例输入处不要空着，可以写个
```
没有输入
```

**Comment by youyu** [comment]
谢谢，指导，解决了
