### ISSUE TITLE
判题结果都是编译错误（11），代码是正确的

### ISSUE THREAD

**Issue by qfsz168** [zhblue/hustoj#677]
**描述问题**
判题结果都是编译错误（11），代码是正确的

**如何复现**

juded是root执行的，服务器是ubuntu20
提交代码后，结果全是编译错误，编译信息里提示权限问题。

g++: error: Main.cc: Permission denied
或
gcc: error: Main.c: Permission denied

![image](https://user-images.githubusercontent.com/22514753/94218874-0a942380-ff18-11ea-8861-520b6a0348fd.png)

**Comment by zhblue** [comment]
试试更新一下？
install目录里的update-hustoj

**Comment by qfsz168** [comment]
> 请更新一下？
> install目录里的update-hustoj

更新没有解决这个问题。
误打误撞处理好了，删除并重建了一下judge用户就可以了。
感谢指导

**Comment by qfsz168** [comment]
误打误撞处理好了，删除并重建了一下judge用户就可以了。
