### ISSUE TITLE
在搭建分布式判题环境的过程中，配置好include/db_info.inc.php后，判题机所在服务器的web端显示sql error

### ISSUE THREAD

**Issue by schrodingercatss** [zhblue/hustoj#680]
**描述问题**
在搭建分布式判题环境的过程中，配置好include/db_info.inc.php后，判题机所在服务器的web端显示sql error，但判题机能正常运行。

**服务器环境**：
ubuntu18.04服务器版

**mysql 8.0授权命令**：
create user "judge2"@"%" identified by "mdltxdy";
grant all privileges on "judge2"@"%";
flush privileges;

**具体配置内容**：
```
// connect db 
static  $DB_HOST="10.7.10.122";  //数据库服务器ip或域名
static  $DB_NAME="jol";   //数据库名
static  $DB_USER="judge2";  //数据库账户
static  $DB_PASS="mdltxdy";  //数据库密码

static  $OJ_NAME="HUSTOJ";  //左上角显示的系统名称
static  $OJ_HOME="./";    //主页目录
static  $OJ_ADMIN="root@localhost";  //管理员email
static  $OJ_DATA="/home/judge/data";  //测试数据目录
static  $OJ_BBS=false; //设为"discuss3" 启用， "bbs" for phpBB3 bridge or "discuss" for mini-forum or false for close any 
static  $OJ_ONLINE=false;  //是否记录在线情况
static  $OJ_LANG="en";  //默认语言
static  $OJ_SIM=false;  //显示相似度
```
如何解决web端无法连接主服务器数据库的问题呢？

**Comment by renbaoshuo** [comment]
请检查数据库服务器的 `tcp/3306` 端口是否开放

**Comment by zhblue** [comment]
如果你的判题机是跟数据库在一起的，请先检查数据库服务器是否开放了 0.0.0.0 上 3306 的监听

**Comment by schrodingercatss** [comment]
> 如果你的判题机是跟数据库在一起的，请先检查数据库服务器是否开放了 0.0.0.0 上 3306 的监听
> 
> ```
> 检查/etc/mysql/my.cnf 确保
> 
> bind-address        = 0.0.0.0
> ```

检查完毕了，确实是按大佬的手册上的内容配置的，因为`my.cnf`中的内容是引用路径，所以`bind-address`这个放在了`mysql.conf.d`中，端口监听也已经开放
![0yvcvQ.png](https://s1.ax1x.com/2020/10/10/0yvcvQ.png)
![0yv2uj.png](https://s1.ax1x.com/2020/10/10/0yv2uj.png)
![0yxIeA.png](https://s1.ax1x.com/2020/10/10/0yxIeA.png)

**Comment by renbaoshuo** [comment]
防火墙的端口开了吗

**Comment by zhblue** [comment]
如果是阿里云，还有个访问策略的问题

**Comment by schrodingercatss** [comment]
> 如果是阿里云，还有个访问策略的问题
感谢两位dalao，是访问策略的问题，已经解决了。

**Comment by cwwang15** [comment]
您好！校园网下，使用 ubuntu20.04.sh 安装脚本在服务器自动安装后，前端会显示 SQL error, check your sql and /var/log/nginx/error.log ! 。登录/注册页面可以打开，但点击提交按钮后无反应。Mysql 远程连接已授权，端口也开启。未修改配置。请问这个问题是怎么产生的？有什么解决办法吗？谢谢！

**Comment by zhblue** [comment]
校园网，建议确认github访问无阻碍，WAF不会拦截请求
