### ISSUE TITLE
开启分布式判题后，提交C/C++代码显示/usr/bin/ld: cannot open output file Main: Permission denied

### ISSUE THREAD

**Issue by schrodingercatss** [zhblue/hustoj#681]
**描述问题**
系统：ubuntu18.04服务器版本

开启分布式判题后，提交正确的C/C++代码编译错误，错误信息为：
>/usr/bin/ld: cannot open output file Main: Permission denied
collect2: error: ld returned 1 exit status

但python代码可以正常判题。

在历史issue中尝试过更新hustoj，目前服务器上的hustoj所有版本均为最新，并且将`data`目录和`usr\bin`目录下的所有文件的权限修改为了777，仍无法解决。

**Comment by zhblue** [comment]
建议检查一下run0 run1 run2 run3 等目录的权限和存在与否
若没有，请手动建立，并配置为judge用户可以写入

**Comment by schrodingercatss** [comment]
run0 run1 等目录权限修改为777后，只要判题端开始判题，run0的权限立马变成了750，然后提示编译错误，
g++: error: Main.cc: Permission denied

**Comment by zhblue** [comment]
run0目录的属主属组改一下

**Comment by zhblue** [comment]
chown judge:root /home/judge/run?

**Comment by zhblue** [comment]
777 是有安全隐患的，尽量少用

**Comment by schrodingercatss** [comment]
> 777 是有安全隐患的，尽量少用


按照大佬说的更改了后run0文件拥有者为judge，所属组为root， 但仍然一判题就编译错误，错误信息与上面相同，并且权限被更改。

**Comment by zhblue** [comment]
df -i 
df 
看看是不是硬盘满了

**Comment by schrodingercatss** [comment]
> df -i
> df
> 看看是不是硬盘满了

硬盘空间应该还有很大的富余

**Comment by zhblue** [comment]
qq联系下10982766
