### ISSUE TITLE
分布式判题中，查重功能无法正常工作

### ISSUE THREAD

**Issue by schrodingercatss** [zhblue/hustoj#682]
在开启分布式判题后，同一份代码经过不同的判题机判题后，首次判题不会进行查重，而只有第二次判题机运行这份代码以后，才会进行查重，请问如何解决呢？

比如A代码在judge1上判题后，A代码再在judge2上判题不会被查重，只有再次在judge1或者judge2上运行A代码才会被查重

**Comment by zhblue** [comment]
分布式判题时不会回传相似参考代码。
要么后期集中重判查重，要么自己写脚本用rsync进行同步。
