### ISSUE TITLE
网站有问题，更新之后，无法正常判题，请问该如何解决？谢谢

### ISSUE THREAD

**Issue by nanersifang** [zhblue/hustoj#684]
![E{{E@Y17J07@U%7XEE~Z(74](https://user-images.githubusercontent.com/10044478/96539421-f4d70b80-12d5-11eb-8f14-5d125371a2be.png)

**Comment by zhblue** [comment]
更新后的必选操作是到后台更新一次数据库，否则库结构与程序不一致，是会无法判题的。
判题核心也要一并更新，编译。

**Comment by nanersifang** [comment]
> 更新后的必选操作是到后台更新一次数据库，否则库结构与程序不一致，是会无法判题的。
> 判题核心也要一并更新，编译。

谢谢啊，后台已经更新了数据库。请问怎么更新、编译判题核心啊？

**Comment by zhblue** [comment]
命令行下执行
```
sudo su
cd /home/judge/src/core
pkill -9 judged
bash make.sh
judged

```

**Comment by nanersifang** [comment]
> 命令行下执行
> 
> ```
> sudo su
> cd /home/judge/src/core
> pkill -9 judged
> bash make.sh
> judged
> ```

谢谢张老师，已经按您说的尝试过了，不过还是不行呢，不能判题，也打不开测试数据，继续请教您，万分感谢！还有后台也打不开数据测试了，也不能补充测试数据了，该如何是好啊张老师？再次感谢！
![1](https://user-images.githubusercontent.com/10044478/96667771-a89ed080-1394-11eb-85dc-23fec49b929f.png)
![2](https://user-images.githubusercontent.com/10044478/96667776-ac325780-1394-11eb-918c-52af43a5e43f.png)

**Comment by zhblue** [comment]
看一下data目录的属主、属组和权限位状态
修复试试
```
chown -R www-data:judge /home/judge/data
chown -R 750 /home/judge/data
```

**Comment by nanersifang** [comment]
> data目录的属主、属组和权限位状态

谢谢张老师，运行了这两句命令，还是不行呢，这是data文件夹的属性 ，该怎么办？谢谢
![3](https://user-images.githubusercontent.com/10044478/96692211-bd915900-13c0-11eb-8ec9-814b82fefcd5.png)

**Comment by nanersifang** [comment]
> 看一下data目录的属主、属组和权限位状态
> 修复试试
> 
> ```
> chown -R www-data:judge /home/judge/data
> chown -R 750 /home/judge/data
> ```
这是目前的状态
![5](https://user-images.githubusercontent.com/10044478/96693585-612f3900-13c2-11eb-9763-323c15c7118f.png)
![4](https://user-images.githubusercontent.com/10044478/96693572-5e344880-13c2-11eb-895d-0e036859da7a.png)

**Comment by nanersifang** [comment]
> 看一下data目录的属主、属组和权限位状态
> 修复试试
> 
> ```
> chown -R www-data:judge /home/judge/data
> chown -R 750 /home/judge/data
> ```

做完这些也把服务器重启了一遍，目前还是以上这个样子

**Comment by zhblue** [comment]
你为啥没有www-data用户？是用了宝塔么？

**Comment by zhblue** [comment]
qq联系我10982766

**Comment by nanersifang** [comment]
> qq联系我10982766

加您了张老师，谢谢您

**Comment by zhblue** [comment]
经查是网管大哥把服务器系统滚动升级到了20.04还自作主张加了open_basedir在nginx的fastcgi配置文件里的PHP_ADMIN_VALUE。
