### ISSUE TITLE
在使用special judge的时候，无论spj.cc里面的返回值为什么最后都会被判wa

### ISSUE THREAD

**Issue by schrodingercatss** [zhblue/hustoj#686]
使用环境，ubuntu18.04服务器版，hustoj最新版

按照要求在数据文件夹下编译spj.cc为spj，并且使用了`chmod + x spj`授权。
spj.cc代码如下：
```cpp
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<math.h>
#include<set>
#include<utility>
using namespace std;
 
int main(int argc, char* argv[]) {
    
    FILE * f_in=fopen(argv[1],"r");//测试输入
	FILE * f_out=fopen(argv[2],"r");//测试输出
	FILE * f_user=fopen(argv[3],"r");//用户输出
	int ret=0; //AC=0,WA=1
	
	/*****spj代码区域*******/
    double a,b;
	while(fscanf(f_out, "%lf", &a) != EOF)
	{
		fscanf(f_user,"%lf",&b);
		if(fabs(a-b)>1e-1) //WA 
		{
			ret=1;
			break;
		}
	}
	
	/*****spj-end********/ 
	
    fclose(f_in);
    fclose(f_out);
    fclose(f_user);
    return ret;

}
```

上述代码在主服务器上运行不管如何(即使直接return 0) 都会被判wa，但是上传到本地搭建的测试oj上spj能被正常运行。

**Comment by zhblue** [comment]
题目需要设置为special judge类型才会激活spj

**Comment by schrodingercatss** [comment]
已经设置了spj类型，题目上显示了红色的special judge

**Comment by schrodingercatss** [comment]
> 题目需要设置为special judge类型才会激活spj

![2.png](https://i.loli.net/2020/10/23/GxT7wM4K8L2oula.png)
![1.png](https://i.loli.net/2020/10/23/NhGAD1oZutUCkiH.png)

**Comment by zhblue** [comment]
试试在编译spj的时候加上-static参数，进行静态编译

**Comment by schrodingercatss** [comment]
> 试试在编译spj的时候加上-static参数，进行静态编译

重判后仍然是WA的

**Comment by zhblue** [comment]
是否尝试过 https://github.com/zhblue/hustoj/blob/master/wiki/SPJ.md 这里的A+B的spj ，能否在贵校系统中正确的工作？

**Comment by zhblue** [comment]
对2.in 2.out 也进行如上图1.in 1.out的测试，看看是否能正确输出$?为0
试试先sudo su为root再执行./spj 2.in 2.out user.out 和 echo $?

**Comment by schrodingercatss** [comment]
> 对2.in 2.out 也进行如上图1.in 1.out的测试，看看是否能正确输出?为0试试先sudosu为root再执行./spj2.in2.outuser.out和echo?

A + B 的spj能正常工作， 2.in 2.out这个的结果也正常返回0

**Comment by zhblue** [comment]
`上述代码在主服务器上运行不管如何(即使直接return 0) 都会被判wa，但是上传到本地搭建的测试oj上spj能被正常运行。`
两天服务器有何配置、系统环境、发行版版本上的区别么？
有没有可能有类似SELinux  \ AppArmor 之类的三方安全程序在工作？

**Comment by schrodingercatss** [comment]
> `上述代码在主服务器上运行不管如何(即使直接return 0) 都会被判wa，但是上传到本地搭建的测试oj上spj能被正常运行。`
> 两太服务器有何配置、系统环境、发行版版本上的区别么？
> 有没有可能有类似SELinux \ AppArmor 之类的三方安全程序在工作？

应该是没有第三方安全程序，这个直接从官方下的ubuntu18.04服务器版的系统，在学院的服务器上安装好后就是用脚本部署了您的hustoj，并在比赛前更新到了最新版，然后之前因为测试过A+B spj能正常运行，就没多想，结果比赛有一个二分的精度题的spj出锅了T^T

**Comment by zhblue** [comment]
精度？？？涉及浮点数么？

**Comment by zhblue** [comment]
学院的服务器与比赛时学生用的机器是相同版本的Ubuntu么？

**Comment by zhblue** [comment]
浮点数的实现由于与编译器类型、版本、操作系统类型相关，所以要特别特别小心，同一个代码在不同的操作系统和编译环境下可能会有不同的结果。

**Comment by schrodingercatss** [comment]
> 精度？？？涉及浮点数么？

对，标程输出的是0.65，有一些写法不同的可能会输出0.66，所以写了个special judge。

比赛时候的版本和服务器均为18.04的。
这个是spj题的文件，里面有标程和有精度误差的代码
文件：https://cowtransfer.com/s/75040cb4b58c49  取件码：tfct7z（24小时内有效）

**Comment by zhblue** [comment]
测试数据都是0字节？

**Comment by zhblue** [comment]
```
#include<stdio.h>
#include<math.h>
int main(int argc,char ** argv){
    FILE *fo=fopen(argv[2],"r");
    FILE *fu=fopen(argv[3],"r");
//    FILE *fd=fopen("diff.out","w");
    double o,u;
    while(fscanf(fo,"%lf",&o)!=EOF){
	if(EOF!=fscanf(fu,"%lf",&u)){
	   if(fabs(u-o)>1e-2){
	//	fprintf(fd,"%s\nout:%lf your:%lf\n",argv[1],o,u);		
	//	fclose(fd);
		return 1;
	   }
	}else{
		return 1;
	}

    }
    return 0;
}

```

**Comment by zhblue** [comment]
> > 题目需要设置为special judge类型才会激活spj
> 
> ![1.png](https://camo.githubusercontent.com/6387cc59eb82ff7c67ff655adc7260f085bc8176/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31302f32332f4e68474144316f5a757455436b69482e706e67)
> ![2.png](https://camo.githubusercontent.com/145381a85a798fedaaffbc0106fc7f8671e0d5e5/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31302f32332f4f53696d4b684155364851633873492e706e67)

我发现问题了，如你这图片中所示，测试数据都是属于root:root的，而对于非root用户是不可读的，而spj程序的执行权限是judge。因此spj根本无法访问到测试数据，因此直接出错退出了。
尝试修复权限
```
chown www-data:judge *
chmod 750 *
```

**Comment by schrodingercatss** [comment]
> 测试数据都是0字节？

dalao，不好意思，刚才因为着急赶着门禁关闭的时候回去导错了，因为学院不让学生使用vpn访问内网，明天我去学院试试这个spj的问题，感谢

**Comment by zhblue** [comment]
> > 测试数据都是0字节？
> 
> dalao，不好意思，刚才因为着急赶着门禁关闭的时候回去导错了，因为学院不让学生使用vpn访问内网，明天我去学院试试这个spj的问题，感谢

注意前面一条回复，重要！

**Comment by zhblue** [comment]
测试数据建议用web端上传、或者以fps形式导入，不容易出现权限问题。
正是因为你的权限是root的，对其他用户包括php都是不可读的，才会导出fps时产生0字节的测试数据。

**Comment by schrodingercatss** [comment]
> 测试数据建议用web端上传、或者以fps形式导入，不容易出现权限问题。
> 正是因为你的权限是root的，对其他用户包括php都是不可读的，才会导出fps时产生0字节的测试数据。

原来是这样，这个数据是老师在主服务器上弄好后我用同步命令传到其他服务器上的，用的root账号传过去的，没想到是这个的锅T^T，谢谢大佬了
