### ISSUE TITLE
首页赞助图片非HTTPS

### ISSUE THREAD

**Issue by sosyz** [zhblue/hustoj#689]
首页赞助图片非HTTPS，虽然说自己也能改（

**Comment by zhblue** [comment]
如果需要上https的话，赞助图片您可以去掉，谢谢报告！

**Comment by zhblue** [comment]
位置是template/bs3/js.php

**Comment by sosyz** [comment]
> 如果需要上https的话，赞助图片您可以去掉，谢谢报告！

明白了，感谢解答XD
