### ISSUE TITLE
hustoj竞赛和作业的一个严重bug

### ISSUE THREAD

**Issue by KrKing12138** [zhblue/hustoj#701]
经我们测试发现，hustoj在Edit竞赛和作业的时候，保存时会将选中的题目状态由Reversed变为Available，而该题目只是不会在problemset里出现，但是通过在status里面找到该题目的提交记录，然后点击进去就可以看到题面，即使该场竞赛还未开始或者受保护。

同样的情况，但是风险没有那么大的bug还有：

1.通过手动输入submitpage.php页面的id可以直接提交Reversed状态的题目的代码。
2.通过删除竞赛中提交页面的langmask参数，可以提交任意语言的代码。

该bug很有可能会导致题目在比赛开始前泄露，希望能够妥善处理!

**Comment by KrKing12138** [comment]
后面所提的两个bug在新版本中似乎已经修复了，但是主要的添加竞赛和作业导致题目泄露的这个bug仍存在。

**Comment by zhblue** [comment]
谢谢指出，已修复。
