### ISSUE TITLE
下载只下载了一个压缩包

### ISSUE THREAD

**Issue by zhijiejia** [zhblue/hustoj#709]
1. 请问现在下载下来完整的形式还是 所有文件都在judge文件夹里吗？
2. 我只下载了一个hustoj.tar.gz

**Comment by zhblue** [comment]
请仔细阅读首页说明，根据所用的Linux发行版选择合适的脚本执行，脚本已经存在于hustoj.tar.gz压缩包内的install目录

**Comment by MX-Qulin** [comment]
@zhblue 请关闭该issue
