### ISSUE TITLE
新版Wiki ,经常无法查看

### ISSUE THREAD

**Issue by youyu** [zhblue/hustoj#712]
提示：域名要卖

联系人： |  
电 话： |  
邮 箱： | bot@baoshuo.ren
钉 钉： |  
QQ： |  
微 信： |

**Comment by zhblue** [comment]
已从首页移除

**Comment by youyu** [comment]
现在不提供新版Wiki了

**Comment by renbaoshuo** [comment]
啊，我的错，把解析改错了...

新版 wiki 已经合并到这个项目里了，现在用 https://zhblue.github.io/hustoj/ 就能访问了。

**Comment by youyu** [comment]
> 啊，我的错，把解析改错了...
> 
> 新版 wiki 已经合并到这个项目里了，现在用 https://zhblue.github.io/hustoj/ 就能访问了。

大佬给力了
