### ISSUE TITLE
使用自定义输入模式时judge_client陷入死循环

### ISSUE THREAD

**Issue by LastHopeOfGPNU** [zhblue/hustoj#713]
在使用自定义输入模式(即problem_id=0)时，judge_client陷入死循环
怀疑在judge_client.cc的 2249、2251或2253行这三个循环中卡住
```
while (setgid(1536) != 0)
	sleep(1);
while (setuid(1536) != 0)
	sleep(1);
while (setresuid(1536, 1536, 1536) != 0)
	sleep(1);
```
理由是在debug模式下最后打印出

> chmod 760 xxx/user.out

请问这三个循环的作用是什么？该如何解决？

**Comment by zhblue** [comment]
确保切换到用户1536，建议检查系统的ulimit设定或者是否SELinux或AppArmor在干扰。
如果使用的是centos，建议更换为ubuntu

**Comment by LastHopeOfGPNU** [comment]
@zhblue debug了一下，发现不是这三个循环的问题，程序能正常切换到1536用户，乌龙了。。
发现其实是卡在运行./Main的环节，我猜是因为Main.c里面有 while(scanf(xxx) != EOF) 这样的语句，但是data.in是no end of line的
但奇怪的是在另外一台Ubuntu服务器上（这两台都是Ubuntu）不会卡住
总之我先close了，我再debug下吧

**Comment by zhblue** [comment]
也许你是你这个题目给的限时太长了，造成卡住的样子

**Comment by LastHopeOfGPNU** [comment]
@zhblue 我查看了/proc/<pid>/limits的内容，./Main确实设置了限制6秒CPU时间，但一直没被kill，是因为进程没拿到CPU资源？

**Comment by LastHopeOfGPNU** [comment]
@zhblue 查看/proc/<pid>/stat的内容，进程处于S(Sleeping)状态

**Comment by zhblue** [comment]
sleep的话，还有个ALARM会唤醒的

**Comment by LastHopeOfGPNU** [comment]
@zhblue 
将judge_client.cc的2269行：
`alarm( num_of_test * time_lmt / cpu_compensation);`
修改为：
`alarm( time_lmt / cpu_compensation);`
能成功退出超时程序，所以这个时候num_of_test为0？
但是不知道这种改动会不会产生副作用

**Comment by zhblue** [comment]
你的测试数据没有.in结尾？

**Comment by zhblue** [comment]
为这个问题打了个补丁，更新一下试试吧

**Comment by LastHopeOfGPNU** [comment]
@zhblue 已更新，感谢
