### ISSUE TITLE
Test data(*.in *.out) must be sorted by the difficulty of the problem or time complexity ... but..

### ISSUE THREAD

**Issue by melongist** [zhblue/hustoj#717]
**描述问题**
When using the problem xml upload/download function, the problem data(*.in *.out) is randomly mixed and uploaded again, and mixed.... 

**如何复现**
1. Upload problem data(*.in, *.out) depending on the difficulty and complexity of the problem by ascending order ... filename(dificulty, complexity.. ascending : test00, test01, ... , test99) 
2. Download the problem data with admin's xml menu.
3. Upload the xml file to HUSTOJ.

**Expected behavior**
The original problem data(*.in, *.out) is out of order ... mixed... ..  :(

**Additional context**
- The problem data(*.in, *out) must be uploaded by ascending order ... filename(dificulty, complexity.. ascending : test00, test01, ... , test99) 
- Because... DOMjudge(ICPC) and CMS(IOI) Contest Management Systems can use the same problem data(*.in, *out)
- This is because it is possible to score different points or weight/ratio depending on the individual scoring data.

So... I think it would be Ok?
(I'm not test yet...)
...

    $ret = "";
    $pdir = "$OJ_DATA/$pid/";  // <-- read problem file directory
    $files = scandir($pdir);  // <-- read all problem files(*.in, *.out)  
    sort($files)  // <-- sort by ascending file name
    
     foreach ($files as $file) { // ... each file data to xml ...

...

**Comment by zhblue** [comment]
a good suggestion, working code is welcome
try consider compatibility with  all old data files in all the installed systems

**Comment by zhblue** [comment]
i managed to make judge_client judge test cases with alpha sorted sequence.
take a test.

**Comment by melongist** [comment]
Wow~ zhblue you are making~ :) thank you~ :)
