### ISSUE TITLE
use_max_time not working ~?

### ISSUE THREAD

**Issue by melongist** [zhblue/hustoj#725]
**描述问题**
Currently, when a result for a judge comes out, 
the sum of each execution time for all judge data is recorded in DB as a result and displayed as a result.

**如何复现**
screenshot~ :)

**Expected behavior**
However, I think ... 
the longest of the execution time of each judge should be recorded as a result. In the case of scoring passed through AC, the longest execution time among all result times should be recorded in DB as the scoring result by default....  I think.

**Screenshots**
<img width="1077" alt="usemaxtime" src="https://user-images.githubusercontent.com/7741650/103774836-8b62cf80-5070-11eb-863b-4a7909d926c7.png">

**Additional context**
How can I fix it?
After making the following modifications in judge_client.cc,
it does not seem to work normally even if the file is compiled again.

//judge_client.cc
...
static int use_max_time = 1;
...

**Comment by zhblue** [comment]
after compiling ,  copy file `judge_client`  into `/usr/bin`

**Comment by melongist** [comment]
> after compiling , copy file `judge_client` into `/usr/bin`

... Hmm.. it's not working... 

But... I got it... :)



//judge_client.cc 
...
// read the configue file
void init_mysql_conf()
{
	FILE *fp = NULL;
	char buf[BUFFER_SIZE];
	host_name[0] = 0;
	user_name[0] = 0;
	password[0] = 0;
	db_name[0] = 0;
	port_number = 3306;
	max_running = 3;
	sleep_time = 3;
	strcpy(java_xms, "-Xms32m");
	strcpy(java_xmx, "-Xmx256m");
	sprintf(buf, "%s/etc/judge.conf", oj_home);      //<-----------   !!! 
	fp = fopen("./etc/judge.conf", "re");                   //<-----------   !!! 
	if (fp != NULL)
	{
		while (fgets(buf, BUFFER_SIZE - 1, fp))
		{
			read_buf(buf, "OJ_HOST_NAME", host_name);
			read_buf(buf, "OJ_USER_NAME", user_name);
			read_buf(buf, "OJ_PASSWORD", password);
			read_buf(buf, "OJ_DB_NAME", db_name);
			read_int(buf, "OJ_PORT_NUMBER", &port_number);
			read_int(buf, "OJ_JAVA_TIME_BONUS", &java_time_bonus);
			read_int(buf, "OJ_JAVA_MEMORY_BONUS", &java_memory_bonus);
			read_int(buf, "OJ_SIM_ENABLE", &sim_enable);
			read_buf(buf, "OJ_JAVA_XMS", java_xms);
			read_buf(buf, "OJ_JAVA_XMX", java_xmx);
			read_int(buf, "OJ_HTTP_JUDGE", &http_judge);
			read_buf(buf, "OJ_HTTP_BASEURL", http_baseurl);
			read_buf(buf, "OJ_HTTP_USERNAME", http_username);
			read_buf(buf, "OJ_HTTP_PASSWORD", http_password);
			read_int(buf, "OJ_HTTP_DOWNLOAD", &http_download);
			read_int(buf, "OJ_OI_MODE", &oi_mode);
			read_int(buf, "OJ_FULL_DIFF", &full_diff);
			read_int(buf, "OJ_SHM_RUN", &shm_run);
			read_int(buf, "OJ_USE_MAX_TIME", &use_max_time);  //<---  !!!  use_max_time re-asigned by judge.conf
			read_int(buf, "OJ_TIME_LIMIT_TO_TOTAL", &time_limit_to_total);
....

....

~

So~...  I can configure to use... use_max_time ... with below....
And it works... .. and... problem-rejudge needed to update DB

Thank you zhblue~ :)



// /home/judge/etc/judge.conf
...
#Using the longest case of test as final time 
OJ_USE_MAX_TIME=1           //<---  !!! 
#Judge TLE by total time 
OJ_TIME_LIMIT_TO_TOTAL=0
#Judge only listed languages
...



Thank you zhblue :)
