### ISSUE TITLE
无法查看选手提供的代码

### ISSUE THREAD

**Issue by Chen--Jian** [zhblue/hustoj#728]
提示：抱歉，您无法查看此消息！因为它不属于您，或者管理员设定系统状态为不显示此类信息。

已经按说明添加了source_browser权限

请问该如何操作？

感谢！

**Comment by zhblue** [comment]
重新登陆，权限生效

**Comment by Chen--Jian** [comment]
你好，目前状态页中，
点击结果，还是提示：抱歉，您无法查看此消息！因为它不属于您，或者管理员设定系统状态为不显示此类信息。
点击语言，可以查看代码了。
还有一个比较小白的问题，就是我这边添加的题目，提交后，显示：正确 AC:0%，内存 0kb，耗时 0ms
请问如何操作呢？
感谢。

**Comment by zhblue** [comment]
结果需要开OJ_SHOW_DIFF才能看。
全0的评测一般是你没给测试数据的原因，注意测试数据必须.in .out 结尾，区别大小写。

**Comment by Chen--Jian** [comment]
明白了，感谢回复~
