### ISSUE TITLE
寻求商务合作

### ISSUE THREAD

**Issue by specialzxw** [zhblue/hustoj#729]
你好，我们想有偿获取您 OJ 题库中的题目资源，有一些合作相关的事项，想向您咨询一下，可否留下您的微信或邮箱，方便我们联系您呢～

**Comment by zhblue** [comment]
可以先加官方群23361372，里面可能有更多潜在合作对象

**Comment by specialzxw** [comment]
请问题库的版权不是属于您的吗～
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by zhblue** [comment]
我的qq在题库页面上有，可以直接加。

**Comment by specialzxw** [comment]
嗯嗯，好的，在此之前，想先请问一下关于题库的版权不是属于您的呢～

**Comment by zhblue** [comment]
部分是，部分不是，仅供老师们自行使用，不建议二次商用。

**Comment by specialzxw** [comment]
嗯嗯，好的，谢谢～
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by specialzxw** [comment]
Hi wusuiwei，

&nbsp; &nbsp; &nbsp;我是蓝桥云课（www.lanqiao.cn）课程合作的负责人，近期偶然在 GitHub 关注到您分享的《autotest-spring-boote》项目，项目十分出色，我们很感兴趣，想邀请您和我们合作制作一门相关的课程。蓝桥云课平台作为蓝桥集团（大学生编程大赛蓝桥杯主办方）旗下的一员，拥有非常丰富的用户资源。我们的课程形式上有文字文档和视频两种，作者可选择自己喜欢的课程形式制作，我们将给予作者极大的创作自由。课程制作完毕后，进行上架销售，课程售价由作者决定，并提供相应销售分成给到作者，回馈作者的分享，实现双赢的合作。如果您对我们的邀请有兴趣的话，欢迎添加蓝桥云课课程合作官方微信账号 “shiyanloukecheng” ，了解具体合作详情，期待您的回复～

蓝桥云课课程合作负责人张仁凤
