### ISSUE TITLE
phpfm.php ... permissions not working

### ISSUE THREAD

**Issue by melongist** [zhblue/hustoj#743]
**描述问题**
admin/phpfm.php ... permissions not working

**如何复现**
1. admin menu - problem list - TestData

2. select file 
3. click permissions
4. error ... 
<img width="1440" alt="phpfmpermissionserror" src="https://user-images.githubusercontent.com/7741650/107129932-6d58eb00-690c-11eb-8a97-0369edaff355.png">

**Expected behavior**
If it works correctly ... 
... file permission check popup ... ?(Once upon a time I saw that pop-up window .... )

**Screenshots**
Attached.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - chrome 88.0.4324.150

**Additional context**
- I found the original phpfm updated to 1.7.9
  https://github.com/dulldusk/phpfm
- I tried updating to HUSTOJ's phpfm with 1.7.9 phpfm, but I couldn't update it for hustoj due to my lack of skills. :(

**Comment by zhblue** [comment]
the function is danger in cerntain situation, so it's removed on purpose

**Comment by melongist** [comment]
> the function is danger in cerntain situation, so it's removed on purpose

If so, it's needed to edit the permissions on the uploaded file.

**uploaded file have 711 permission**, not 644 ~


+ uploaded zip files, after decompress, have 644 permission ~correctly


<img width="1440" alt="uploadedfileneedtofix" src="https://user-images.githubusercontent.com/7741650/107137214-a2396200-694d-11eb-92ee-7cf749edd2dd.png">

**Comment by zhblue** [comment]
711 should works fine , why 644
if you need to access them with other soft 
try modify
0711 to 0644 here
https://github.com/zhblue/hustoj/blob/master/trunk/web/admin/phpfm.php#L2374
and here
https://github.com/zhblue/hustoj/blob/master/trunk/web/admin/phpfm.php#L2380

**Comment by melongist** [comment]
> 711 should works fine , why 644
> if you need to access them with other soft
> try modify
> 0711 to 0644 here
> https://github.com/zhblue/hustoj/blob/master/trunk/web/admin/phpfm.php#L2374
> and here
> https://github.com/zhblue/hustoj/blob/master/trunk/web/admin/phpfm.php#L2380

thank you~ :)
