### ISSUE TITLE
如何关闭提交页面的验证码？

### ISSUE THREAD

**Issue by blue1102** [zhblue/hustoj#749]
如何关闭提交页面的验证码？
找了半天也没找到对应参数，难道只能修改源代码吗？
请高人指点。

**Comment by MX-Qulin** [comment]
解决:db_info.inc.php里vcode设为false
但是如果提交过于频繁,强制验证码保护服务器.



在 2021-03-18 09:44:58，"blue1102" ***@***.***> 写道：

如何关闭提交页面的验证码？
找了半天也没找到对应参数，难道只能修改源代码吗？
请高人指点。

**Comment by blue1102** [comment]
db_info.inc.php里vcode设为false时候，登录时候无验证码了。
想实现：登录时候有验证码；提交时候不要验证码

**Comment by MX-Qulin** [comment]
你不怕别人提交10000份上去卡评测机?



在 2021-03-19 11:15:03，"blue1102" ***@***.***> 写道：

db_info.inc.php里vcode设为false时候，登录时候无验证码了。
想实现：登录时候有验证码；提交时候不要验证码

**Comment by zhblue** [comment]
可以在loginpage/login里手工开启

**Comment by blue1102** [comment]
好的，感谢，最终还得自行修改代码。
1.关闭参数中的验证码选项；
2.修改注册页面，打开验证码。
