### ISSUE TITLE
Successive judges with python, hustoj becomes unresponsive.

### ISSUE THREAD

**Issue by melongist** [zhblue/hustoj#751]
**描述问题**
If it runs successive judges with python, the hustoj system becomes unresponsive.

**Screenshots**
successive judges makes system unresponsive.
<img width="1440" alt="01" src="https://user-images.githubusercontent.com/7741650/111894017-98c21000-8a4a-11eb-9788-6d73e5351eb8.png">

After reboot, the causative judge is in judging...
<img width="1440" alt="02" src="https://user-images.githubusercontent.com/7741650/111894019-9fe91e00-8a4a-11eb-8c0e-a9426c1a893f.png">

After rejudging with admin-menu(rejudging), it became judged status.. 
<img width="1440" alt="03" src="https://user-images.githubusercontent.com/7741650/111894090-3c132500-8a4b-11eb-8bc5-9a2cf5a0bd83.png">

**Comment by melongist** [comment]
Maybe this is a similar situation...

https://github.com/zhblue/hustoj/issues/710

**Comment by zhblue** [comment]
check if runX dirs match OJ_RUNNING in judge.conf, run0 - run3 match 4.
try OJ_PYTHON_FREE=1 if your system run massive python solutions

**Comment by melongist** [comment]
OK I will testing this with 

OJ_RUNNING=2

Thank you~ :)

**Comment by melongist** [comment]
> check if runX dirs match OJ_RUNNING in judge.conf, run0 - run3 match 4.
> try OJ_PYTHON_FREE=1 if your system run massive python solutions


OJ_RUNNING=4 <-- It works a little, but under more many python judging load, the system hangs too.

OJ_PYTHON_FREE=1  <-- This works well!. Python judging proceeds fastly after using this method.

Thank you~ :)
