### ISSUE TITLE
关于 judge_client.cc 的一点问题

### ISSUE THREAD

**Issue by outloudvi** [zhblue/hustoj#76]
https://github.com/zhblue/hustoj/blob/master/trunk/core/judge_client/judge_client.cc#L2196

是否需要排除一下 lang=13 与 lang=14？那两个好像也是C/C++的样子……

**Comment by zhblue** [comment]
有道理啊😄

**Comment by outloudvi** [comment]
所以可以关咯？ :)

**Comment by zhblue** [comment]
你关吧
