### ISSUE TITLE
請問判題部份給分功能要如何啟用

### ISSUE THREAD

**Issue by tico88612** [zhblue/hustoj#77]
看到預覽圖片都有
Ex. 答案錯誤 18%
請問判題部份給分功能要如何啟用

**Comment by zhblue** [comment]
OJ_OI_MODE=1

**Comment by gongcy** [comment]
如果要具体显示出每个测试点正确或错误，该修改哪些地方？需要改判题内核吗？

**Comment by zhblue** [comment]
对

**Comment by gongcy** [comment]
那能请您指明在程序的哪里修改吗？我没找到。

**Comment by zhblue** [comment]
judge_client内大范围调整，不是一两处。
要求不高可以开OI_MODE+SHOW_DIFF凑合一下
