### ISSUE TITLE
问题页面title显示错误

### ISSUE THREAD

**Issue by youngbe** [zhblue/hustoj#779]
**描述问题**
ubuntu 20.04 使用官方脚本安装

**如何复现**
点击查看题目

![image](https://user-images.githubusercontent.com/24429886/130568874-5ddad396-353b-4529-b5eb-ff9651a4813d.png)

https://github.com/zhblue/hustoj/blob/master/trunk/web/template/bs3/problem.php#L12

这里是不是漏加了php？

**Comment by zhblue** [comment]
已修复，谢谢！
