### ISSUE TITLE
测试数据行首不可以有空行

### ISSUE THREAD

**Issue by youyu** [zhblue/hustoj#800]
例如列出一个集合的所有子集时，空集为空，不能用空行表示，当然可以用null表示，但是需要额外说明，不利于审题

**Comment by jizhuozhi** [comment]
这和OJ没关系，你`System.out.println(null)`输出的不就是`null`，OJ只是作了纯文本匹配

**Comment by zhblue** [comment]
![image](https://user-images.githubusercontent.com/3926566/148962391-a752072c-4f82-4f6f-a95d-69a8e17b4d33.png)
