### ISSUE TITLE
全局bool数组过大导致运行时RE

### ISSUE THREAD

**Issue by SecretPal** [zhblue/hustoj#814]
**描述问题**
评测的程序中包含过大的数组时会产生re
如声明全局数组bool a[876543210];
满足memory limit限制，但是运行时会报re

程序在服务器本地执行可以，但是通过OJ运行会有错误

不知道有没有人遇到过类似的问题？

**Comment by zhblue** [comment]
试试自己用malloc分配堆内存

**Comment by SecretPal** [comment]
我是oj维护者不是使用者…

我试了下其他oj没这个问题… 不知道是否是judger做了什么限制？

**Comment by jizhuozhi** [comment]
把代码贴出来，是不是在方法内栈上分配的，有的OJ会改方法栈大小所以在别的OJ不会RE。永远不要在栈上分配大数组

**Comment by SecretPal** [comment]
已解决，是其他oj的问题。
就是声明一个1e9的全局bool数组，应该是MLE，但是报了RE
有的OJ貌似有编译优化bool数组每个元素只占1bit

**Comment by jizhuozhi** [comment]
@SecretPal 如果没有什么问题可以把issue关闭了
