### ISSUE TITLE
How can I use "OJ_USE_MAX_TIME=1" in default release 22.02.23 docker? 

### ISSUE THREAD

**Issue by melongist** [zhblue/hustoj#819]
**描述问题**
judge.conf's "OJ_USE_MAX_TIME=1" setting is not working....

So, I tried to ... 

But I don't know how to enable "OJ_USE_MAX_TIME=1" in default docker...

How can I enable "OJ_USE_MAX_TIME=1" in default docker?

**如何复现**
Release 22.02.23's default setting is "OJ_USE_MAX=0"

**Expected behavior**
If I edit judge.conf's "OJ_USE_MAX_TIME=1" setting..

Release 22.02.23 HUSTOJ record the max time of results ...
But judged ... with like "OJ_USE_MAX_TIME=0" TLE... :(

But I want to judge results with the max time of all results, not sum of...

Thank you all~ :)

**Comment by zhblue** [comment]
try also set 
OJ_TIME_LIMIT_TO_TOTAL=0

**Comment by melongist** [comment]
Thank you~ It works!!!! :)

**Comment by melongist** [comment]
> try also set OJ_TIME_LIMIT_TO_TOTAL=0


Thank you~ It works!!!! :)
