### ISSUE TITLE
使用申请。

### ISSUE THREAD

**Issue by wierton** [zhblue/hustoj#82]
我们有一个项目，其中有一部分会用到hustoj，并会修改hustoj一部分代码，所以在这里咨询一下作者，是否允许复制修改源码，由于本人对GPL协议还不是很了解，所以想请问一下应该如何声明。
因为作者的项目中并没有看到LICENSE、COPYRIGHT之类的文件，所以声明使用的话是在README里注明一下吗？

**Comment by zhblue** [comment]
如果你们是打算开源的话，那么只能用GPL，如果不开源的话，只能自用。

**Comment by wierton** [comment]
开源的话是要在相应的源码目录下放上hustoj的GPL协议文件吗？但是并没有找到hustoj的协议文件。

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/blob/master/trunk/web/gpl-2.0.txt

https://github.com/zhblue/hustoj/blob/master/trunk/core/judge_client/judge_client.cc#L14

**Comment by wierton** [comment]
好的，谢谢！
