### ISSUE TITLE
在判题的时候，经过 gcc/g++ 降级操作，遇到 -std=c17 报错问题。

### ISSUE THREAD

**Issue by erlinux** [zhblue/hustoj#840]
**描述问题**
使用推荐方式在 ubuntu20 安装的判题系统
在判题的时候，经过 gcc/g++ 降级操作，遇到 -std=c17 报错问题。

**如何复现**
将 gcc/g++ 降级到 5.4 <- 蓝桥杯推荐版本
直接重新判题就会出现问题

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/17078378/173214645-f415c051-fb68-450a-b86c-6c7dc7b4bc60.png">
点开报错内容为： unrecognized command line option '-std=c17'

 
 
**Screenshots**
<img width="804" alt="image" src="https://user-images.githubusercontent.com/17078378/173214614-176bc1cd-5af1-4a0d-9342-3c81365b630b.png">
<img width="823" alt="image" src="https://user-images.githubusercontent.com/17078378/173214616-9080311e-6464-425f-ab72-faebf56f7941.png">

**Additional context**
我怀疑是 judged 配置文件配置问题导致的，但我尝试编辑后问题依然没有得到解决。
<img width="825" alt="image" src="https://user-images.githubusercontent.com/17078378/173214634-d2d1b403-b952-4425-b847-0253e564ace0.png">
配置已复原。希望可以得到帮助，感谢！

**Comment by zhblue** [comment]
如果要修改编译器，去看install目录下面的Dockerfile，判题并不是在原生系统跑的，而是在一个docker容器里跑，需要去修改Dockerfile并重新运行docker.sh来更新这个容器的镜像。

**Comment by erlinux** [comment]
好的，我研究一下。但是我有一个问题，就是我之前没有跑 docker 容器也是可以正常判题是为何呢？

**Comment by erlinux** [comment]
想问下，我现在是老版本。如果我从老版本升上去，需要做什么改动吗？以及您建议我升级到最新版本吗？

**Comment by erlinux** [comment]
直接执行 ./docker.sh 出现了这样的报错，docker 的网络是正常的。
```shell
E: Unable to locate package libmysqlclient-dev
The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends libmysqlclient-dev' returned a non-zero code: 100
```
有什么办法解决吗？

**Comment by erlinux** [comment]
直接执行 ./docker.sh 出现了这样的报错，docker 的网络是正常的。

这个有办法解决吗？

**Comment by zhblue** [comment]
需要修改Dockerfile，替换其下载源码的路径和版本

**Comment by erlinux** [comment]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/17078378/190662011-a300cf97-a331-4b98-97b1-f0d0604c8a90.png">
 修改 /home/judge/etc/judge.conf 配置文件后，问题得到解决

**Comment by erlinux** [comment]
想问下，我现在是老版本。如果我从老版本升上去，需要做什么改动吗？




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "zhblue/hustoj"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Jun 13, 2022 03:31 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [zhblue/hustoj] 在判题的时候，经过 gcc/g++ 降级操作，遇到 -std=c17 报错问题。 (Issue #840)





 
早期版本是没有默认开的，最新版本里默认开启了，但是你也可以关掉。
 /home/judge/etc/judge.conf

**Comment by zhblue** [comment]
取决于你的系统，如果用了docker就同样要修改dockerfile。可以先直接更新源码，修改judge.conf试试。
