### ISSUE TITLE
测试运行秒數越跑越快

### ISSUE THREAD

**Issue by tico88612** [zhblue/hustoj#85]
https://github.com/zhblue/hustoj/blob/master/trunk/web/template/classic/submitpage.php#L238
第238行 是 window.clearInterval() 不是  window.cleanInterval
加了intervalId會比較明確
https://github.com/tico88612/hustoj-1/blob/c230f514bd31c339bc70caced85e251fb17113dc/trunk/web/template/classic/submitpage.php
檢查一下其他的template有沒有這個問題

**Comment by zhblue** [comment]
谢谢，年久失修了，classic
