### ISSUE TITLE
phpfm.php's compress not working~

### ISSUE THREAD

**Issue by melongist** [zhblue/hustoj#850]
**描述问题**
phpfm.php  compress not working~ properly

**如何复现**
1. at TestData
2. select some files
3. click compress
5. blank ... and not compressed... 

**Screenshots**
<img width="1440" alt="cnw01" src="https://user-images.githubusercontent.com/92401080/178124763-49d91217-f558-444e-948a-a0d93a61013b.png">

<img width="1440" alt="cnw02" src="https://user-images.githubusercontent.com/92401080/178124768-54e29a00-ac3e-4e5b-89b3-3c3788eb5ebd.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser : chrome
 - Version : latest

**Comment by zhblue** [comment]
try run 
```
sudo apt-get install php-zip
```

**Comment by melongist** [comment]
> try run
> 
> ```
> sudo apt-get install php-zip
> ```

nop.. 

it does not works....yet,  after installing php-zip.

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/commit/428863556ca979bd4cd564832422d12f377ce5d5

**Comment by melongist** [comment]
> [4288635](https://github.com/zhblue/hustoj/commit/428863556ca979bd4cd564832422d12f377ce5d5)

Thank you~ 👍🏼
