### ISSUE TITLE
kindeditor image file upload not working~

### ISSUE THREAD

**Issue by melongist** [zhblue/hustoj#851]
**描述问题**

**如何复现**
1. ... at kindeditor
2. click img upload button
3. find img file...
4. click submit button
5. .. but it's not uploaded...  :(

**Expected behavior**
kindeditor file upload error....

**Screenshots**
<img width="1440" alt="kindeditorerr" src="https://user-images.githubusercontent.com/92401080/178129193-60595bb4-24a2-4e3f-8c8f-5feb41b0b11f.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: chrome
 - Version: latest

**Comment by zhblue** [comment]
looks like I need to install an instance of ubuntu22.04 to reproduce these problems.

**Comment by zhblue** [comment]
https://github.com/zhblue/hustoj/commit/aa023c41d02f63e8d3ba7edc7c0cc362c6c53e30

**Comment by melongist** [comment]
> [aa023c4](https://github.com/zhblue/hustoj/commit/aa023c41d02f63e8d3ba7edc7c0cc362c6c53e30)

Thank you 👍🏼
