### ISSUE TITLE
Java判题在报错Could not find or load main class Main

### ISSUE THREAD

**Issue by Matt-Dong123** [zhblue/hustoj#852]
用的是最新的版本，代码如下：
![image](https://user-images.githubusercontent.com/66734553/181966569-168c79c5-12a7-40cf-9559-0d02fe18dd6f.png)
报找不到Main.java
![image](https://user-images.githubusercontent.com/66734553/181967113-586d0d2f-6ac5-4e41-8228-f573b8fa7bf9.png)

这个要怎么解决呢，已经自己装完jdk了

**Comment by zhblue** [comment]
JDK是需要在docker容器里安装的，去看看install目录的Dockerfile文件，试试修改其中的openjdk16为openjdk17，然后重新运行sudo bash docker.sh，成功后重启服务器（必须重启服务器）。

**Comment by Matt-Dong123** [comment]
一样的问题，还是不能正常判题，并报运行错误

**Comment by Matt-Dong123** [comment]
一样的问题，还是不能正常判题，并报运行错误

**Comment by zhblue** [comment]
试试关闭USE_DOCKER，启用外部的java环境
