### ISSUE TITLE
如何配置 SMTP

### ISSUE THREAD

**Issue by xcx0902** [zhblue/hustoj#859]
当前配置为：
![image](https://user-images.githubusercontent.com/99001676/187417083-76881158-6fd9-4b72-827b-b9f09366cb8f.png)
但是无法发送邮件（跳转到了 lostpassword2.php，但是收件箱里没有邮件），如何修改？

**Comment by zhblue** [comment]
需要去邮箱服务商开通smtp功能，现在邮箱默认都不开的

**Comment by zhblue** [comment]
你可以把debug那个改成true，看看有没有什么报错

**Comment by xcx0902** [comment]
有报错，如下：
Trying to smtp.qq.com:587 220 newxmesmtplogicsvrszc13.qq.com XMail Esmtp QQ Mail Server. Connected to relay host smtp.qq.com > HELO localhost 250-newxmesmtplogicsvrszc13.qq.com-9.46.14.43-58753634 > AUTH LOGIN MzU2MjkwNzE0Nw== 250-SIZE 73400320 > eGN4MTIzNDU2 250 OK > MAIL FROM:<3562907147@qq.com> 334 UGFzc3dvcmQ6 > RCPT TO:<3562907147@qq.com> 535 Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256 Error: Remote host returned "535 Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256" Error: Error occurred while sending RCPT TO command. Error: Cannot send email to <3562907147@qq.com> Disconnected from remote host

**Comment by zhblue** [comment]
Please enter your authorization code to login.  这个提示的意思是你不应该输入邮箱的密码，而是在邮箱那边配置smpt的时候生成一个系统给你的密钥，把这个密钥放在这里。这样可以避免你的这个文件被黑客看到而导致你邮箱密码即QQ被盗。

**Comment by xcx0902** [comment]
修改成邮箱的授权码了，然后报错变成了：
Trying to smtp.qq.com:587 220 newxmesmtplogicsvrsza32.qq.com XMail Esmtp QQ Mail Server. Connected to relay host smtp.qq.com > HELO localhost 250-newxmesmtplogicsvrsza32.qq.com-9.138.20.14-15868053 > AUTH LOGIN MzU2MjkwNzE0Nw== 250-SIZE 73400320 > anBudXNhb21ia3NlY2lkaQ== 250 OK > MAIL FROM:<3562907147@qq.com> 334 UGFzc3dvcmQ6 > RCPT TO: 235 Authentication successful > DATA 502 Invalid input from <OJ-IP> to newxmesmtplogicsvrsza32.qq.com Error: Remote host returned "502 Invalid input from <OJ-IP> to newxmesmtplogicsvrsza32.qq.com" Error: Error occurred while sending DATA command. Error: Cannot send email to Disconnected from remote host

**Comment by zhblue** [comment]
你的发信内容可能有点问题

**Comment by xcx0902** [comment]
我把信的内容改成了 Hello，但是还是报错（内容与上面一样）。
![image](https://user-images.githubusercontent.com/99001676/187597980-4d2f2f67-f7cd-41aa-ba63-0ee17d2ad14a.png)

**Comment by zhblue** [comment]
你这hello是标题 mailtitle，不是 mailcontent

**Comment by xcx0902** [comment]
改成mailcontent后也没用

**Comment by xcx0902** [comment]
是不是格式的问题

**Comment by zhblue** [comment]
试试   $smtpuser = "$smtpusermail";//SMTP服务器的用户帐号

**Comment by xcx0902** [comment]
还是报错（内容一样）

**Comment by xcx0902** [comment]
用这个 python 代码测试了一下，可以使用 SMTP。
![image](https://user-images.githubusercontent.com/99001676/187599285-aec48016-fde6-44cf-b5fe-ec35cc35157f.png)

**Comment by zhblue** [comment]
那你看看这个email.class.php里面哪些地方跟你的python不一样，改改试试。
https://github.com/zhblue/hustoj/blob/master/trunk/web/include/email.class.php

**Comment by zhblue** [comment]
502 — The command is not implemented. It is valid but has not been activated by your provider. 
可能是QQ邮箱不支持某些头部，去注释掉77-100行里非必须的那些值看看。

**Comment by xcx0902** [comment]
现在没有报错了，但是没有邮件

**Comment by xcx0902** [comment]
我把那个 python 文件放到服务器上，然后让 PHP 直接跑那个脚本，结果可以正常使用了。。。

**Comment by zhblue** [comment]
也不是不能用
https://github.com/zhblue/hustoj/commit/3d1aef27b4adeaa42b5c52617350851f015f273d

**Comment by zhblue** [comment]
可能被归入广告邮件折叠在收件箱第一封信里面了。

**Comment by zengxs** [comment]
可以参考下我修改的 email.class.php 使用 PHPMailer 替换了手动实现的 smtp 协议之后可以正常发邮件
https://github.com/zengxs/hautoj/blob/hautoj/trunk/web/include/email.class.php

还有 @xcx0902 老哥你的评论里包含了 base64 的邮箱密码，建议删除
