### ISSUE TITLE
请问如何清除状态信息啊？

### ISSUE THREAD

**Issue by shifan-Z** [zhblue/hustoj#863]
请问如何批量清除状态栏下的历史提交信息？
![image](https://user-images.githubusercontent.com/54871708/190948949-f9744a03-19ed-42af-9364-5238fbf10d75.png)

**Comment by zhblue** [comment]
删除单条
```
sudo su
cd /home/judge/src/install
bash mysql.sh
myql>delete from solution where id = 12551;
```
修改 =12551为 < 12551 则删除所有小于12551的，修改为 where  id>=12000 and id<=12551; 则删除id ∈ [12000,12551]

**Comment by shifan-Z** [comment]
非常感谢！
