### ISSUE TITLE
添加私有比赛并指定用户列表时，如果有重复的用户ID，会导致部分用户无法进入比赛

### ISSUE THREAD

**Issue by neoshm126** [zhblue/hustoj#872]
建议在contest_add.php和contest_edit.php 往privilege表插入比赛权限之前，去个重。
经测试加上这行代码就行了。
$pieces = array_unique($pieces);

**Comment by zhblue** [comment]
加在哪一行最好能写一下

**Comment by neoshm126** [comment]
contest_edit.php 73行 $pieces = explode(',', $plist);后面
contest_add.php 73行 $pieces = explode(',', $plist);后面
