### ISSUE TITLE
Centos7环境下spj判题提示: 找不到用户 "www-data"

### ISSUE THREAD

**Issue by runnableAir** [zhblue/hustoj#882]
**描述问题**

起因是spj判题一直wa，但手动测试可以ac。此时使用的是 centos7
用 debug 后发现在 spj 判题一开始就出现错误，**提示找不到用户 `"www-data"`**。
换了一台 ubuntu 安装测试后没有该问题，对比后发现，centos 这边的测试数据所属用户为 "apache" ，而不是 "www-data"
修改了源码第 2663 行中的
```
execute_cmd("chown www-data:judge %s/data/%d/spj %s %s %s", oj_home, problem_id,infile, outfile, userfile);
```
将 www-data 改为 apache ，然后重新编译就没问题了

**Comment by zhblue** [comment]
如有可能，不要再使用centos了

**Comment by runnableAir** [comment]
> 如有可能，不要再使用centos了

确实，之后计划迁移了
