### ISSUE TITLE
如何设置内邮只能发送给拥有管理员权限的用户

### ISSUE THREAD

**Issue by PythonSmall-Q** [zhblue/hustoj#905]
如何设置内邮只能发送给拥有管理员权限的用户 @zhblue

**Comment by zhblue** [comment]
看这里
https://github.com/zhblue/hustoj/blob/master/trunk/web/mail.php#L87

**Comment by PythonSmall-Q** [comment]
没看懂，怎么设置给admin权限的 @zhblue

**Comment by PythonSmall-Q** [comment]
我看了看感觉意思是给source和admin但是我这里普通还是能发的

**Comment by PythonSmall-Q** [comment]
我懂了，是说发给其他人是发不出去的是吧
