### ISSUE TITLE
Is there a way to use modules such as NumPy and Pandas within Judge's Python environment?

### ISSUE THREAD

**Issue by pgworld** [zhblue/hustoj#915]
When executing code such as "import numpy" in the current environment, a compilation error occurs. The methods I have tried are:

- Executing "apt-get install python3-numpy" within the Judge server.
- Adding the line "RUN DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends python3-numpy" to "/home/judge/src/install/Dockerfile" and executing "docker.sh".

However, "import numpy" still does not work properly. Are there any other methods?

**Comment by zhblue** [comment]
the process that you made was right.
still new mods of python may introduce new SYSCALLs 
using DEBUG mode to determine them and add them to okcalls64.h
compile judge_client again with `make` command
set OJ_CLIENT_INTERNAL=0  to active the new compiled version for judged
reboot judged and make another  try

**Comment by pgworld** [comment]
Thanks to you, it was solved.
After adding the required system call number to /home/judge/src/core/judge_client/okcalls64.h and making judge_client, it works normally.
