### ISSUE TITLE
C++中使用万能头文件时，编译出错，服务器崩溃必须重启才恢复

### ISSUE THREAD

**Issue by Andy-qinyuhai** [zhblue/hustoj#925]
**描述问题**
请说清安装方式、基础系统、物理机环境、操作过程，遇到的问题

系统：Ubuntu 20.04
OJ代码已经同步更新至最新版本
OJ_USE_DOCKER=1 

**如何复现**
1. 在 'C++代码中 使用万能头文件 #include <bits/stdc++.h>提交代码时'
2. 系统卡在编译中
3. 系统无响应，必须重启才恢复

**Comment by zhblue** [comment]
机器内存多少，CPU几核？
oj_running设置多少？
具体代码是怎样的？可以在demo.hustoj.com测试一下。

**Comment by zhblue** [comment]
这个题目的测试数据是否齐备？runX目录是否齐备？

**Comment by zhblue** [comment]
如果您是中国大陆用户，请使用腾讯qq加入群23361372提问，我随时为您在线解答。

**Comment by Andy-qinyuhai** [comment]
谢谢回复！机器为GCP: e2-micro 内存1G, oj_running=1, 我重启后再次提交同样的代码就正常编译了，我再观察看看。

**Comment by zhblue** [comment]
内存太少了，1G内存的话光mysql、php、nginx就吃掉快一半了，通用头意味着所有头文件都一起编译了，很容易触发OOM killer。建议如果不能增加内存，可以修改mysql配置，减少内存消耗。

**Comment by Andy-qinyuhai** [comment]
感谢提醒，没注意这个mysql默认安装了8.0版本，我尝试关闭performance_schema后内存占用少了很多。
