### ISSUE TITLE
安装java后仍显示You need to install compiler VM or runtime for your language.

### ISSUE THREAD

**Issue by LastHopeOfGPNU** [zhblue/hustoj#945]
java和javac都在PATH里，也都软连接到/usr/bin下，但运行仍提示You need to install compiler VM or runtime for your language.

**Comment by zhblue** [comment]
新安装的系统，运行docker.sh成功后，需要重启后才能支持Java。

**Comment by LastHopeOfGPNU** [comment]
> 新安装的系统，运行docker.sh成功后，需要重启后才能支持Java。
java是必须使用docker吗？

**Comment by zhblue** [comment]
是的，最新版本默认都在容器里跑。

**Comment by LastHopeOfGPNU** [comment]
哪个版本可以使用OS本地的JDK？

**Comment by zhblue** [comment]
需要设置judge.conf，OJ_USE_DOCKER=0
