### ISSUE TITLE
部署完成后无法注册报500错误

### ISSUE THREAD

**Issue by Dameng23333** [zhblue/hustoj#955]
按照教程部署完成，但是无法注册，报500错误
错误日志：
Stack trace:
#0 {main}
  thrown in /home/judge/src/web/register.php on line 71" while reading response header from upstream, client: 172.16.62.251, server: _, request: "POST /register.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "172.16.62.101", referrer: "http://172.16.62.101/registerpage.php"
2023/08/05 08:25:01 [error] 3446230#3446230: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/judge/src/web/register.php:71

**Comment by zhblue** [comment]
按提示可能是数据库没有连接成功。

**Comment by Dameng23333** [comment]
ubuntu 23.04,以为是版本的问题，在另一台22.04的装了也是同样报错，按照教程把宝塔安装的东西都卸载了

**Comment by zhblue** [comment]
23.04不是长期服务lts版本。
用22.04安装，请选择纯净系统和自动脚本。
宝塔系统请按群共享说明。

**Comment by Dameng23333** [comment]
好的，我试一下
