### ISSUE TITLE
Problem_list does not appear on the admin page.

### ISSUE THREAD

**Issue by seohyun-kim** [zhblue/hustoj#965]
I hope this message finds you well. 
I have been using your hustoj project and have found it to be very helpful. 
However, I have encountered a specific issue that I am curious about.

I recently performed a database initialization and attempted to configure new problems. 

While the problem list appears correctly on the main user interface, I have noticed that when I access the admin page and try to view the problem list (located in the code at `/home/judge/src/web/admin/problem_list.php`), the list does not display.

|user page|admin page|
|------|---|
|![Untitled (1)](https://github.com/zhblue/hustoj/assets/61939286/870eb8af-f9b3-477f-af6b-4b1db524254d)|![Untitled (2)](https://github.com/zhblue/hustoj/assets/61939286/8a2bec00-34b9-4b2a-8feb-a9ce788f7953)|

In an effort to debug this issue, I added code to print the number of rows below the relevant code. 
[same code in github here](https://github.com/zhblue/hustoj/blob/003f03ad72ec495ae282f3648907ee6ef0960d3e/trunk/web/admin/problem_list.php#L28) 

- added code
    ```
    if ($row) {
        echo "Total Problem IDs: " . $row['ids'];
    } else {
        echo "No results found.";
    }
    ```
- result
![Untitled](https://github.com/zhblue/hustoj/assets/61939286/2e88f36b-7610-4147-85d7-fbae77fad30c)

----

I am wondering if you could provide some guidance on what might be causing this issue? Your assistance would be greatly appreciated.

Thank you for your time and consideration.

**Comment by zhblue** [comment]
if your database is not newly installed, try update it's structure to fix this problem by one of the following methods:

1. Click the [Update] Button in the  Menu System Admin  -> Update Database
2. execute the script from /home/judge/src/install/update.sql in your jol database
3. if not working , try update these two files ,and do it again.

**Comment by zhblue** [comment]
my best guess is the folloing lines:
```
alter table problem add column remote_oj varchar(16) default NULL after solved;
alter table problem add column remote_id varchar(32) default NULL after remote_oj;
alter table solution add column remote_oj char(16) not null default '' after judger;
alter table solution add column remote_id char(32) not null default '' after remote_oj;

```

**Comment by seohyun-kim** [comment]
Thank you so much for your prompt response.

I was able to resolve the issue with the first question you mentioned.
`1. Click the [Update] Button in the Menu System Admin -> Update Database`
It turns out it was a problem that could be solved with just one button press...haha 😅😅

Thank you for providing such a robust and excellent project as open source.👍

I truly appreciate your kind assistance. Wishing you a wonderful day ahead.
(And Thank you for following me as well.😍)
