### ISSUE TITLE
如何设置ssl

### ISSUE THREAD

**Issue by KittenCN** [zhblue/hustoj#981]
**描述问题**
我是在腾讯云的ubuntu系统下，用install.sh安装的系统，现在想用ssl访问，所以想咨询下，相关的设置该如何做。

**Comment by zhblue** [comment]
编辑/etc/nginx/sites-enabled/default

参考https://zhuanlan.zhihu.com/p/553921471

**Comment by KittenCN** [comment]
成功了，谢谢
